//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "AccountServiceExt.h"
#import "MMPreviewNodraggableWindowDelegate.h"
#import "NSPageControllerDelegate.h"
#import "NSSharingServiceDelegate.h"
#import "NSWindowDelegate.h"

@class MMPreviewNodraggableWindow, MMPreviewTitleButton, MMView, NSArray, NSButton, NSImageView, NSPageController, NSProgressIndicator, NSString, NSTextField, NSView, NSVisualEffectView;

@interface MMBasePreviewPanelWindowController : NSWindowController <AccountServiceExt, NSWindowDelegate, MMPreviewNodraggableWindowDelegate, NSSharingServiceDelegate, NSPageControllerDelegate>
{
    BOOL _allowMultipleItems;
    BOOL _isFullScreen;
    BOOL _isKeyDownNavigation;
    MMView *_containerView;
    NSVisualEffectView *_vibrantView;
    NSPageController *_pageController;
    NSArray *_previewItemList;
    NSView *_loadingViewContarner;
    NSProgressIndicator *_loadingView;
    NSTextField *_loadingLabel;
    NSView *_failedImageViewContainer;
    NSImageView *_failedImageView;
    NSTextField *_errMsgLabel;
    MMView *_mmTitlebarView;
    NSTextField *_mmTitleTextField;
    MMView *_windowControlContainer;
    MMView *_operationContainer;
    MMPreviewTitleButton *_nextItemButton;
    MMPreviewTitleButton *_prevItemButton;
    MMPreviewTitleButton *_openWithButton;
    MMPreviewTitleButton *_showMoreButton;
    MMPreviewTitleButton *_zoomOutButton;
    MMPreviewTitleButton *_zoomInButton;
    MMPreviewTitleButton *_rotateButton;
    NSButton *_mmCloseButton;
    NSButton *_mmFullScreenButton;
}

@property(nonatomic) BOOL isKeyDownNavigation; // @synthesize isKeyDownNavigation=_isKeyDownNavigation;
@property(nonatomic) BOOL isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(retain, nonatomic) NSButton *mmFullScreenButton; // @synthesize mmFullScreenButton=_mmFullScreenButton;
@property(retain, nonatomic) NSButton *mmCloseButton; // @synthesize mmCloseButton=_mmCloseButton;
@property(retain, nonatomic) MMPreviewTitleButton *rotateButton; // @synthesize rotateButton=_rotateButton;
@property(retain, nonatomic) MMPreviewTitleButton *zoomInButton; // @synthesize zoomInButton=_zoomInButton;
@property(retain, nonatomic) MMPreviewTitleButton *zoomOutButton; // @synthesize zoomOutButton=_zoomOutButton;
@property(retain, nonatomic) MMPreviewTitleButton *showMoreButton; // @synthesize showMoreButton=_showMoreButton;
@property(retain, nonatomic) MMPreviewTitleButton *openWithButton; // @synthesize openWithButton=_openWithButton;
@property(retain, nonatomic) MMPreviewTitleButton *prevItemButton; // @synthesize prevItemButton=_prevItemButton;
@property(retain, nonatomic) MMPreviewTitleButton *nextItemButton; // @synthesize nextItemButton=_nextItemButton;
@property(retain, nonatomic) MMView *operationContainer; // @synthesize operationContainer=_operationContainer;
@property(retain, nonatomic) MMView *windowControlContainer; // @synthesize windowControlContainer=_windowControlContainer;
@property(retain, nonatomic) NSTextField *mmTitleTextField; // @synthesize mmTitleTextField=_mmTitleTextField;
@property(retain, nonatomic) MMView *mmTitlebarView; // @synthesize mmTitlebarView=_mmTitlebarView;
@property __weak NSTextField *errMsgLabel; // @synthesize errMsgLabel=_errMsgLabel;
@property __weak NSImageView *failedImageView; // @synthesize failedImageView=_failedImageView;
@property __weak NSView *failedImageViewContainer; // @synthesize failedImageViewContainer=_failedImageViewContainer;
@property __weak NSTextField *loadingLabel; // @synthesize loadingLabel=_loadingLabel;
@property __weak NSProgressIndicator *loadingView; // @synthesize loadingView=_loadingView;
@property __weak NSView *loadingViewContarner; // @synthesize loadingViewContarner=_loadingViewContarner;
@property(retain, nonatomic) NSArray *previewItemList; // @synthesize previewItemList=_previewItemList;
@property(nonatomic) BOOL allowMultipleItems; // @synthesize allowMultipleItems=_allowMultipleItems;
@property(retain, nonatomic) NSPageController *pageController; // @synthesize pageController=_pageController;
@property(retain, nonatomic) NSVisualEffectView *vibrantView; // @synthesize vibrantView=_vibrantView;
@property(retain, nonatomic) MMView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (id)getPreviewTitle;
- (id)contentForShare;
- (void)_sharingServiceAction:(id)arg1;
- (void)_menuActionExport:(id)arg1;
- (void)_menuActionFavorite:(id)arg1;
- (void)forwardPreviewItem:(id)arg1 toContactsWithUserNames:(id)arg2;
- (void)sendPreviewItem:(id)arg1 toContactsWithUserNames:(id)arg2;
- (void)_menuActionForward:(id)arg1;
- (void)_menuActionCopy;
- (void)rightMouseSharingServiceAction:(id)arg1;
- (void)buttonSharingServiceAction:(id)arg1;
- (void)rightMouseMenuActionExport:(id)arg1;
- (void)buttonMenuActionExport:(id)arg1;
- (void)rightMouseMenuActionFavorite:(id)arg1;
- (void)buttonMenuActionFavorite:(id)arg1;
- (void)rightMouseMenuActionForward:(id)arg1;
- (void)buttonMenuActionForward:(id)arg1;
- (void)rightMouseMenuActionCopy;
- (void)buttonMenuActionCopy;
- (void)commonMenuActionCopy;
- (id)rightMouseMakeContextMenu;
- (id)buttonMakeContextMenu;
- (void)onUserLogout;
- (void)onCurrentNetworkLockStateWillChange:(BOOL)arg1;
- (void)onCurrentDeviceLockStateChanged:(BOOL)arg1;
- (void)closeWithMenu;
- (void)setupContextualMenu;
- (void)showMoreMenuInView:(id)arg1;
- (void)openWith:(id)arg1;
- (void)makeRotate:(id)arg1;
- (void)makeStandardSize:(id)arg1;
- (void)makeSmaller:(id)arg1;
- (void)makeLarger:(id)arg1;
- (void)copy:(id)arg1;
- (void)toggleFullScreenWithSender:(id)arg1;
- (void)closeWithSender:(id)arg1;
- (void)prevItem:(id)arg1;
- (void)nextItem:(id)arg1;
- (void)toggleLoadingView;
- (void)hideLoadingView;
- (void)setupOpenWithButton:(id)arg1;
- (void)openFileWithPath:(id)arg1 andIsByFolder:(BOOL)arg2;
- (struct CGRect)windowFrameRectOnInitialWithImageSize:(struct CGSize)arg1 andSourceFrameRect:(struct CGRect)arg2;
- (void)close;
- (void)show;
- (void)setupNavigationButtons;
- (void)setupTitle;
- (void)setupTitleBarView;
- (id)getCurrentPreviewItem;
- (void)setupPageController;
- (void)setupFailedImageView;
- (void)setupLoadingView;
- (void)observeKeyPathToChangeButtonStatus;
- (void)setupKeyDownHandler;
- (void)windowDidResize:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;
- (id)initWithWindowNibName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain) MMPreviewNodraggableWindow *window; // @dynamic window;

@end

