//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSColor, NSImage;

@interface MMImageEditButton : NSButton
{
    NSColor *_selectedColor;
    unsigned long long _fontSize;
    unsigned long long _type;
    NSColor *_colorBorderColor;
    NSColor *_fontBorderColor;
    NSColor *_fontColor;
    NSImage *_arrowImage;
}

@property(retain, nonatomic) NSImage *arrowImage; // @synthesize arrowImage=_arrowImage;
@property(retain, nonatomic) NSColor *fontColor; // @synthesize fontColor=_fontColor;
@property(retain, nonatomic) NSColor *fontBorderColor; // @synthesize fontBorderColor=_fontBorderColor;
@property(retain, nonatomic) NSColor *colorBorderColor; // @synthesize colorBorderColor=_colorBorderColor;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) unsigned long long fontSize; // @synthesize fontSize=_fontSize;
@property(retain, nonatomic) NSColor *selectedColor; // @synthesize selectedColor=_selectedColor;
- (void).cxx_destruct;
- (void)configAppearanceAndLayout;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

