//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMPreviewWindowController.h"

#import "IMessageExt.h"
#import "MMCDNDownloadMgrExt.h"
#import "MMPreviewChatMediaDataLogicDelegate.h"

@class MMPreviewChatMediaDataLogic, MessageData, NSString, WCContactData;

@interface MMPreviewChatMediaWindowController : MMPreviewWindowController <MMPreviewChatMediaDataLogicDelegate, IMessageExt, MMCDNDownloadMgrExt>
{
    MessageData *m_currentPreviewingMessage;
    WCContactData *m_chatContact;
    MMPreviewChatMediaDataLogic *m_dataLogic;
    unsigned long long m_order;
    unsigned long long m_preIndex;
    unsigned char isFirstOpen;
}

- (void).cxx_destruct;
- (void)cdnDownloadMgrDidFailedDownloadWithMessage:(id)arg1 type:(int)arg2;
- (void)cdnDownloadMgrDidFinishedDownloadWithMessage:(id)arg1 type:(int)arg2;
- (struct CGRect)pageController:(id)arg1 frameForObject:(id)arg2;
- (void)pageControllerDidEndLiveTransition:(id)arg1;
- (void)pageController:(id)arg1 didTransitionToObject:(id)arg2;
- (void)pageControllerWillStartLiveTransition:(id)arg1;
- (void)pageController:(id)arg1 prepareViewController:(id)arg2 withObject:(id)arg3;
- (id)pageController:(id)arg1 viewControllerForIdentifier:(id)arg2;
- (id)pageController:(id)arg1 identifierForObject:(id)arg2;
- (void)onDelMsg:(id)arg1 msgData:(id)arg2;
- (void)onMsgImgDataLogicLoadOKWithLast:(id)arg1 Next:(id)arg2;
- (void)edit;
- (id)_genPreviewItemWithMessage:(id)arg1;
- (void)openWith;
- (id)getCurrentPreviewItem;
- (void)setupPageController;
- (void)_showPreviewItem:(id)arg1 targetFrame:(struct CGRect)arg2;
- (void)show;
- (void)_preLoadImageToCache;
- (void)_updatePreviewList;
- (void)_initPreviewList;
- (void)_initDataLogic;
- (void)dealloc;
- (id)initWithChatContact:(id)arg1 InitialSelectedMessage:(id)arg2 AndOrder:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

