//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "IMMMessageVideoServiceExt.h"
#import "MMCDNDownloadMgrExt.h"
#import "MMFavoriteFileServiceExt.h"

@class AVPlayer, AVPlayerItem, MMAVPlayerView, MMButton, MMCircularProgressView, MMImageView, MMQLPreviewItem, NSString, TKStateMachine;

@interface MMPreviewVideoPlayerView : NSView <MMCDNDownloadMgrExt, IMMMessageVideoServiceExt, MMFavoriteFileServiceExt>
{
    unsigned char _shouldPlayVideo;
    unsigned char _isSwapingMouse;
    AVPlayer *_player;
    MMAVPlayerView *_playerView;
    AVPlayerItem *_playerItem;
    TKStateMachine *_stateMachine;
    MMQLPreviewItem *_previewItem;
    MMImageView *_thumbnailImageView;
    MMButton *_actionButton;
    MMImageView *_progressBgView;
    MMCircularProgressView *_progressView;
}

@property(retain, nonatomic) MMCircularProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) MMImageView *progressBgView; // @synthesize progressBgView=_progressBgView;
@property(retain, nonatomic) MMButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) MMImageView *thumbnailImageView; // @synthesize thumbnailImageView=_thumbnailImageView;
@property(retain, nonatomic) MMQLPreviewItem *previewItem; // @synthesize previewItem=_previewItem;
@property(retain, nonatomic) TKStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) MMAVPlayerView *playerView; // @synthesize playerView=_playerView;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(nonatomic) unsigned char isSwapingMouse; // @synthesize isSwapingMouse=_isSwapingMouse;
@property(nonatomic) unsigned char shouldPlayVideo; // @synthesize shouldPlayVideo=_shouldPlayVideo;
- (void).cxx_destruct;
- (void)favoriteFileService:(id)arg1 didFailDownloadWithFavItemData:(id)arg2 type:(int)arg3 taskID:(id)arg4;
- (void)favoriteFileService:(id)arg1 didFinishDownloadWithFavItemData:(id)arg2 type:(int)arg3 filePath:(id)arg4 taskID:(id)arg5;
- (void)favoriteFileService:(id)arg1 downloaded:(int)arg2 of:(int)arg3 WithFavItemData:(id)arg4 type:(int)arg5;
- (void)cdnDownloadMgrDidFailedDownloadWithMessage:(id)arg1 type:(int)arg2;
- (void)cdnDownloadMgrDidFinishedDownloadWithMessage:(id)arg1 type:(int)arg2;
- (void)messageVideoService:(id)arg1 didCancelDownloadWithMessage:(id)arg2;
- (void)messageVideoService:(id)arg1 didFailDownloadWithMessage:(id)arg2;
- (void)messageVideoService:(id)arg1 didFinishDownloadWithMessage:(id)arg2;
- (void)messageVideoService:(id)arg1 downloaded:(int)arg2 of:(int)arg3 withMessage:(id)arg4;
- (void)retryDownload:(id)arg1;
- (void)onPlayButtonClicked:(id)arg1;
- (void)onDownloadButtonClicked:(id)arg1;
- (void)_setupWithDataField;
- (void)_setupWithFav;
- (void)_setupWithMessage;
- (void)setupWithPreviewItem:(id)arg1;
- (unsigned char)startPlayVideo:(unsigned char)arg1;
- (void)resetVideoStatus;
- (void)_setupVideoPlayer;
- (BOOL)isAVPlayerViewSupported;
- (void)_fireStateEvent:(id)arg1;
- (void)_setupStateMachine;
- (void)_layoutProgressBgView;
- (void)_layoutActionButton;
- (void)_layoutThumbnailImageView;
- (void)_setupSubViews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

