//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface OpenIMContactCustomInfo : PBGeneratedMessage
{
    unsigned int hasDetailVisible:1;
    unsigned int hasDetail:1;
    unsigned int detailVisible;
    NSString *detail;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetDetail:) NSString *detail; // @synthesize detail;
@property(readonly, nonatomic) BOOL hasDetail; // @synthesize hasDetail;
@property(nonatomic, setter=SetDetailVisible:) unsigned int detailVisible; // @synthesize detailVisible;
@property(readonly, nonatomic) BOOL hasDetailVisible; // @synthesize hasDetailVisible;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

