//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSMutableDictionary, NSMutableSet, NSRecursiveLock, NSString;

@interface WCDBRepairMgr : MMService <MMService>
{
    NSMutableDictionary *m_repairInfoDic;
    NSMutableSet *m_corruptedDBTagSet;
    NSRecursiveLock *m_oLock;
    BOOL m_stopRepair;
    id <WCDBRepairDelegate> _delegate;
}

@property(nonatomic) __weak id <WCDBRepairDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getMetasFromDB:(id)arg1;
- (void)deleteDBWith:(id)arg1;
- (void)stopRepair;
- (void)repairCorruptedDBWith:(id)arg1;
- (void)p_repairAllCorruptedDB;
- (void)checkAndRepair;
- (void)addCorruptedDB:(id)arg1;
- (void)p_backupDBWith:(id)arg1;
- (void)registerRepairInfo:(id)arg1 recoverDBPath:(id)arg2 encryptKey:(id)arg3 pageSize:(int)arg4 raw:(BOOL)arg5 dbId:(id)arg6;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

