//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IFriendListMgrExt.h"
#import "MMService.h"

@class NSMutableDictionary, NSString;

@interface AddressBookFriendMgr : MMService <MMService, IFriendListMgrExt>
{
    NSMutableDictionary *m_friends;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (BOOL)trySyncAddressBookFriends;
- (void)onFriendListUpdated:(id)arg1 ErrorCode:(unsigned long)arg2 Message:(id)arg3;
- (id)getAddressBookFriends;
- (void)LoadData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

