//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AppPersonalInfoData : NSObject
{
    NSString *rank;
    BOOL shouldBold;
    unsigned long rankWeight;
}

@property(nonatomic) unsigned long rankWeight; // @synthesize rankWeight;
@property(nonatomic) BOOL shouldBold; // @synthesize shouldBold;
@property(retain, nonatomic) NSString *rank; // @synthesize rank;
- (void).cxx_destruct;
- (id)init;

@end

