//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ProtobufEventHandler.h"

@interface AuthEventHandler : ProtobufEventHandler
{
    struct ec_key_st *ecdh_key;
    unsigned int ct1;
}

- (BOOL)OnProtocolEncryptPack:(id)arg1 OutBuf:(struct AutoBuffer *)arg2 uin:(unsigned int)arg3;
- (BOOL)OnProtocolManualAuthEncryptPack:(id)arg1 OutBuf:(struct AutoBuffer *)arg2 uin:(unsigned int)arg3;
- (BOOL)OnProtocolAutoAuthEncryptPack:(id)arg1 OutBuf:(struct AutoBuffer *)arg2 uin:(unsigned int)arg3;
- (BOOL)OnProtocolHasCustomEncryptPack:(id)arg1;
- (void)OnProtocolConnectFail:(id)arg1;
- (void)OnProtocolResponse:(id)arg1 shouldContinue:(_Bool *)arg2;
- (void)changeForMessage:(id)arg1;
- (void)OnProtocolStart:(id)arg1 shouldContinue:(_Bool *)arg2;
- (void)dealloc;
- (id)init;

@end

