//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class DeviceRankInfo;

@interface BraceletRankInfoView : MMUIView
{
    DeviceRankInfo *m_rankInfo;
    BOOL m_isBotton;
    BOOL m_isFromFocus;
    BOOL m_bShowRedDot;
}

- (void).cxx_destruct;
- (void)initView;
- (void)addSeperateLine;
- (id)initWithDeviceRankInfo:(id)arg1 IsBottom:(BOOL)arg2 IsFromFocus:(BOOL)arg3 showRedDot:(BOOL)arg4;
- (id)initWithDeviceRankInfo:(id)arg1 IsBottom:(BOOL)arg2 IsFromFocus:(BOOL)arg3;

@end

