//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BrandArticleSearchLogicDelegateForController.h"
#import "MMSearchBarDelegate.h"
#import "MMWebViewDelegate.h"

@class BrandArticleSearchLogic, BrandArticleSearchResultLogic, MMSearchBar, NSString, UIButton, UIColor, UIImageView, UIView<YYWebViewInterface>;

@interface BrandArticleSearchController : NSObject <MMSearchBarDelegate, BrandArticleSearchLogicDelegateForController, MMWebViewDelegate>
{
    BOOL _isContainerInteractivePopEnabled;
    UIButton *_euSearchBarHitBtn;
    MMSearchBar *m_searchBar;
    BrandArticleSearchLogic *m_logic;
    BrandArticleSearchResultLogic *m_resultLogic;
    UIView<YYWebViewInterface> *m_resultView;
    NSString *m_resultViewQuery;
    BOOL _isDetailSearch;
    BOOL _isMoving;
    id <BrandArticleSearchControllerDelegate> m_delegate;
    UIColor *_backgroundColor;
    UIView<YYWebViewInterface> *_detailView;
    UIButton *_detailBackButton;
    NSString *_searchID;
    float _moveStartOffset;
    float _moveCurOffset;
    UIImageView *_bottomViewShadow;
    unsigned long long _detailSearchType;
}

+ (BOOL)isOpenSearchEntry;
@property(retain, nonatomic) UIImageView *bottomViewShadow; // @synthesize bottomViewShadow=_bottomViewShadow;
@property(nonatomic) float moveCurOffset; // @synthesize moveCurOffset=_moveCurOffset;
@property(nonatomic) float moveStartOffset; // @synthesize moveStartOffset=_moveStartOffset;
@property(nonatomic) BOOL isMoving; // @synthesize isMoving=_isMoving;
@property(retain, nonatomic) NSString *searchID; // @synthesize searchID=_searchID;
@property(nonatomic) unsigned long long detailSearchType; // @synthesize detailSearchType=_detailSearchType;
@property(nonatomic) BOOL isDetailSearch; // @synthesize isDetailSearch=_isDetailSearch;
@property(retain, nonatomic) UIButton *detailBackButton; // @synthesize detailBackButton=_detailBackButton;
@property(retain, nonatomic) UIView<YYWebViewInterface> *detailView; // @synthesize detailView=_detailView;
@property(nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) __weak id <BrandArticleSearchControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (id)onWebViewPassParams:(id)arg1;
- (void)restoreInteractivePop;
- (void)forbidInteractivePop;
- (id)urlParamsForDetailPage:(id)arg1 params:(id)arg2;
- (void)loadLocalHtmlForDetailPage:(id)arg1 params:(id)arg2;
- (id)getContainerVcView;
- (void)onRemoveDetailView;
- (void)moveDetailViewToRight;
- (void)updateMovingDetailView;
- (void)cancelMoveDetailView;
- (void)onClickDetailBack:(id)arg1;
- (void)handlePanGestureForDetailView:(id)arg1;
- (id)findSearchTextField;
- (id)makeNewDetailView:(id)arg1;
- (void)mmSearchDisplayControllerDidEndSearch;
- (void)mmSearchBarTextDidChange:(id)arg1;
- (BOOL)mmsearchBarShouldChangeTextInRange:(struct _NSRange)arg1 replacementText:(id)arg2;
- (void)mmsearchBarTextDidBeginEditing:(id)arg1;
- (void)reportClickSearch:(id)arg1;
- (void)mmsearchBarSearchButtonClicked:(id)arg1;
- (void)mmSearchDisplayControllerWillEndSearch;
- (void)mmSearchDisplayControllerDidBeginSearch;
- (void)mmSearchDisplayControllerWillBeginSearch;
- (void)onOpenMoreDetailWithParams:(id)arg1;
- (void)onSetSearchText:(id)arg1;
- (void)onOpenMsgSession:(id)arg1;
- (void)onOpenBrandProfile:(id)arg1 withParams:(id)arg2;
- (void)onOpenUrl:(id)arg1 withParams:(id)arg2;
- (void)onExitSearch;
- (void)openMsgSession:(id)arg1;
- (void)openBrandProfile:(id)arg1 withParams:(id)arg2;
- (void)openWebViewForUrl:(id)arg1 withParams:(id)arg2;
- (void)hideResultView;
- (void)showResultView;
- (void)clearDetailButton;
- (void)clearDetailView;
- (void)clearResultView;
- (void)setupResultView;
- (void)resetResultViewSuperView;
- (void)onClearSearchText;
- (void)resetStatusBarFontColor;
- (void)hideKeyboardForSearchBar;
- (void)hideSearchBarResultView;
- (float)searchBarBottomYPosToView:(id)arg1;
- (id)currentViewController;
- (void)finishSearchIfNeed;
- (void)onEuSearchBarHitBtnClick:(id)arg1;
- (void)onViewDidAppeared;
- (void)onViewWillBePushed;
- (void)onViewDidPop;
- (void)onViewWillBePoped;
- (void)removeCustomView;
- (BOOL)isActive;
- (id)getSearchBar;
- (id)initWithViewController:(id)arg1 tableView:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

