//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BTMsgSectionData;

@protocol BrandTimelineExposeReportLogicDelegate <NSObject>
- (unsigned int)msgIndexFormsgSectionData:(BTMsgSectionData *)arg1;
- (BOOL)isSectionLastNewMsgSection:(int)arg1;
@end

