//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTReaderItemCellViewModel.h"

#import "RichTextLayoutDelegate.h"

@class NSString;

@interface BTTextItemCellViewModel : BTReaderItemCellViewModel <RichTextLayoutDelegate>
{
    BOOL m_callFullText;
    NSString *m_contentPatternText;
    BOOL _isFullText;
}

+ (BOOL)canCreateViewModelWithReaderWrap:(id)arg1 msgWrap:(id)arg2;
@property(nonatomic) BOOL isFullText; // @synthesize isFullText=_isFullText;
- (void).cxx_destruct;
- (BOOL)shouldOpenNewLineAtY:(float)arg1 withLineHeight:(float)arg2 richTextView:(id)arg3;
- (id)coverImgURL;
- (id)titleLabelStyles;
@property(readonly, nonatomic) unsigned int parserTypes;
@property(readonly, nonatomic) BOOL canFullText;
@property(readonly, nonatomic) NSString *contentPatternText;
- (struct CGSize)titleSize;
- (float)viewHeight;
- (id)itemViewClassName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

