//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ChatRoomNoticeMsg : NSObject
{
    unsigned long createTime;
    unsigned long msgSvrID;
    NSString *chatRoomName;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *chatRoomName; // @synthesize chatRoomName;
@property(nonatomic) unsigned long msgSvrID; // @synthesize msgSvrID;
@property(nonatomic) unsigned long createTime; // @synthesize createTime;
- (void).cxx_destruct;
- (const map_69681069 *)getValueTagIndexMap;
- (id)getValueTypeTable;

@end

