//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMMDB;

@interface CMessageDB : NSObject
{
    CMMDB *m_oMMDB;
}

@property(retain, nonatomic) CMMDB *m_oMMDB; // @synthesize m_oMMDB;
- (void).cxx_destruct;
- (unsigned long)GetMinCreateTimeInMessage:(id)arg1;
- (unsigned long)GetMaxCreateTimeInMessage:(id)arg1;
- (BOOL)hasMsg:(id)arg1 fromCreateTime:(unsigned long)arg2 endTime:(unsigned long)arg3;
- (void)setMessageUnreadCondition:(struct WCTExpr *)arg1 from:(unsigned long)arg2;
- (id)getImageMsg:(id)arg1 beforeCreateTime:(unsigned long)arg2 limit:(int)arg3;
- (id)getImageMsg:(id)arg1 limit:(int)arg2;
- (void)setMessageUnreadCondition:(struct WCTExpr *)arg1;
- (void)setMessageUnreadConditionIncludingNewXML:(struct WCTExpr *)arg1;
- (void)fillDBMsg:(id)arg1 andProperty:(struct WCTPropertyList *)arg2 fromMsgWrap:(id)arg3 des:(unsigned long)arg4;
- (void)HandleMessage:(id)arg1 ChatName:(id)arg2 Des:(unsigned long)arg3;
- (id)GetLocalUsrName:(id)arg1;
- (unsigned long)GetUnReadCountInHello:(id)arg1;
- (unsigned long)GetCountInHello:(id)arg1;
- (unsigned long)GetSayHelloStatus:(id)arg1 LocalID:(unsigned long)arg2;
- (BOOL)SetSayHelloStatus:(id)arg1 LocalID:(unsigned long)arg2 Status:(unsigned long)arg3;
- (BOOL)ClearHelloUnRead:(id)arg1 HelloUser:(id)arg2;
- (void)DelHelloMsg:(id)arg1 HelloUser:(id)arg2;
- (id)GetHelloMsg:(id)arg1 HelloUser:(id)arg2 Limit:(int)arg3 OnlyTo:(BOOL)arg4;
- (id)GetDBHelloUsers:(id)arg1 Limit:(int)arg2 OnlyUnread:(BOOL)arg3;
- (id)GetHelloUsers:(id)arg1 Limit:(int)arg2 OnlyUnread:(BOOL)arg3;
- (id)GetHelloMsgForSyncRead:(id)arg1 Where:(const struct WCTExpr *)arg2;
- (id)GetHelloMsg:(id)arg1 Where:(const struct WCTExpr *)arg2 Order:(const list_6bfdf17e *)arg3 Limit:(int)arg4;
- (void)AddHelloMsg:(id)arg1 MsgWrap:(id)arg2 HelloUser:(id)arg3 OpCode:(unsigned long)arg4 DES:(unsigned long)arg5 checkCreateTime:(BOOL)arg6 status:(unsigned long)arg7;
- (unsigned long)GetImgOrVideoMsgCount:(id)arg1;
- (unsigned long)GetImgOrVideoMsgCount:(id)arg1 FromID:(unsigned long)arg2 CreateTime:(unsigned long)arg3;
- (unsigned long)GetImgOrVideoOrAppMsgMinCreateTime:(id)arg1;
- (id)GetImgOrVideoOrAppNextMsg:(id)arg1 StartCreateTime:(unsigned long)arg2 EndCreateTime:(unsigned long)arg3 Limit:(int)arg4 needFullMessage:(BOOL)arg5;
- (id)GetImgOrVideoOrAppLastMsg:(id)arg1 StartCreateTime:(unsigned long)arg2 EndCreateTime:(unsigned long)arg3 Limit:(int)arg4 needFullMessage:(BOOL)arg5;
- (id)GetImgOrVideoOrAppNextMsg:(id)arg1 FromID:(unsigned long)arg2 Limit:(int)arg3 CreateTime:(unsigned long)arg4;
- (id)GetImgOrVideoLastMsg:(id)arg1;
- (id)GetImgOrVideoOrAppLastMsg:(id)arg1 FromID:(unsigned long)arg2 Limit:(int)arg3 CreateTime:(unsigned long)arg4;
- (id)GetAppMsgList:(id)arg1 FromID:(unsigned long)arg2 CreateTime:(unsigned long)arg3 Limit:(int)arg4 Where:(struct WCTExpr)arg5;
- (id)GetAppMsgList:(id)arg1 FromID:(unsigned long)arg2 CreateTime:(unsigned long)arg3 Limit:(int)arg4;
- (id)GetAppMsgList:(id)arg1 AfterID:(unsigned long)arg2 CreateTime:(unsigned long)arg3 Limit:(int)arg4;
- (id)GetImgAndVideoMsgList:(id)arg1;
- (id)GetImgMsgList:(id)arg1;
- (id)GetMsgForFlowWall:(id)arg1 Where:(const struct WCTExpr *)arg2 Order:(const list_6bfdf17e *)arg3 Limit:(int)arg4;
- (unsigned long)GetImgMsgCount:(id)arg1;
- (unsigned long)GetImgMsgCount:(id)arg1 FromID:(unsigned long)arg2 CreateTime:(unsigned long)arg3;
- (id)GetImgLastMsg:(id)arg1;
- (id)GetImgLastMsg:(id)arg1 FromID:(unsigned long)arg2 Limit:(int)arg3 CreateTime:(unsigned long)arg4;
- (id)GetImgNextMsg:(id)arg1 FromID:(unsigned long)arg2 Limit:(int)arg3 CreateTime:(unsigned long)arg4;
- (id)GetLastVoipMsg:(id)arg1 AfterTime:(unsigned long)arg2;
- (void)UpdateVideoMessage:(id)arg1 MsgWrap:(id)arg2;
- (void)UpdateMessage:(id)arg1 MsgWrap:(id)arg2;
- (void)UpdateVoiceMessage:(id)arg1 MsgWrap:(id)arg2;
- (void)UpdateVoiceStatus:(id)arg1 LocalID:(unsigned long)arg2 DownloadStatus:(unsigned long)arg3;
- (id)getMessageWrapArray:(id)arg1 bizId:(id)arg2;
- (BOOL)addMessageToWCPayBizExtTable:(id)arg1;
- (id)getMessageWrapArray:(id)arg1 bizId:(id)arg2 onType:(unsigned long)arg3;
- (id)GetAllChatNameWithValidNewBizMsg:(unsigned long)arg1;
- (void)DelOverTimeNewBizMessageOnType:(unsigned long)arg1;
- (unsigned long)GetValidNewBizMsgCountByChatName:(id)arg1 bizType:(unsigned long)arg2;
- (unsigned long)GetAllValidNewBizMsgCount:(unsigned long)arg1;
- (void)ModBizMsg:(id)arg1 bizId:(id)arg2 bizStatus:(unsigned long)arg3 bizType:(unsigned long)arg4;
- (BOOL)addMessageToNewWCPayBizExtTable:(id)arg1 type:(int)arg2;
- (BOOL)AddBackupMessageToChatExt:(id)arg1 MsgWrap:(id)arg2;
- (BOOL)AddMessageToChatExt:(id)arg1 MsgWrap:(id)arg2;
- (unsigned long)GetMesCount:(id)arg1 MesType:(unsigned long)arg2;
- (unsigned long)GetAllMesCount:(id)arg1;
- (unsigned long)GetUnReadCount:(id)arg1 CreateTimeLargerThan:(unsigned long)arg2;
- (unsigned long)GetUnReadCount:(id)arg1;
- (unsigned long)GetTextMsgCount:(id)arg1 FromID:(unsigned long)arg2 ToID:(unsigned long)arg3;
- (BOOL)isMessageExist:(id)arg1 MsgSvrId:(long long)arg2;
- (void)DelAllMsgs:(id)arg1;
- (void)AutoEmptyTrashTable;
- (void)EmptyTrashTable;
- (void)DelMsgForBatchDelete:(id)arg1 MsgList:(id)arg2;
- (void)DelMsg:(id)arg1 MsgList:(id)arg2 DelAll:(BOOL)arg3;
- (void)TransferMsgFromChatToDuplicate:(id)arg1;
- (void)ClearUnReadForSync:(id)arg1 CreateTime:(unsigned long)arg2;
- (BOOL)ClearUnRead:(id)arg1 FromID:(unsigned long)arg2 ToID:(unsigned long)arg3;
- (void)DropChatTable:(id)arg1;
- (void)ModVoipMsgStatus:(id)arg1 MsgWrap:(id)arg2;
- (void)ModMsgByBitSet:(id)arg1 MsgWrap:(id)arg2 BitSet:(unsigned long)arg3;
- (void)ModLocationMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)ModMsg:(id)arg1 MsgWrap:(id)arg2;
- (BOOL)RemoveOldRevokeMessagesBefore:(unsigned long)arg1;
- (BOOL)InsertRevokeMessage:(id)arg1;
- (id)GetRevokeMessage:(long long)arg1;
- (id)GetFirstUnreadMsgIncludingNewXML:(id)arg1;
- (id)GetFirstUnreadMsg:(id)arg1;
- (id)GetLastMsgToUsr:(id)arg1;
- (id)GetLastMsgFromUsr:(id)arg1;
- (id)GetLastInsertMsg:(id)arg1;
- (id)GetLastMsg:(id)arg1;
- (id)GetTextMsg:(id)arg1 FromID:(unsigned long)arg2 Limit:(int)arg3;
- (id)GetTextMsg:(id)arg1 FromID:(unsigned long)arg2 ToID:(unsigned long)arg3;
- (id)GetMsg:(id)arg1 BizMsgClientID:(id)arg2;
- (id)GetMsg:(id)arg1 n64SvrID:(long long)arg2;
- (id)GetMsg:(id)arg1 LocalID:(unsigned long)arg2;
- (id)GetMsg:(id)arg1 LocalID:(unsigned long)arg2 hasError:(char *)arg3;
- (id)QueryMsgByCreateTime:(id)arg1 FromID:(unsigned long)arg2 FromCreateTime:(unsigned long)arg3 Limit:(int)arg4 Where:(const struct WCTExpr *)arg5;
- (id)GetDownMsgByCreateTime:(id)arg1 FromID:(unsigned long)arg2 FromCreateTime:(unsigned long)arg3 Limit:(int)arg4 LeftCount:(unsigned int *)arg5 FromSequence:(unsigned long)arg6;
- (id)GetDownMsgByCreateTime:(id)arg1 FromID:(unsigned long)arg2 FromCreateTime:(unsigned long)arg3 Limit:(int)arg4 LeftCount:(unsigned int *)arg5;
- (id)GetMsgByCreateTime:(id)arg1 FromID:(unsigned long)arg2 FromCreateTime:(unsigned long)arg3 Limit:(int)arg4 LeftCount:(unsigned int *)arg5 FromSequence:(unsigned long)arg6;
- (id)GetMsgByCreateTime:(id)arg1 FromID:(unsigned long)arg2 FromCreateTime:(unsigned long)arg3 Limit:(int)arg4 LeftCount:(unsigned int *)arg5;
- (id)GetDownMsg:(id)arg1 FromID:(unsigned long)arg2 Limit:(int)arg3;
- (id)GetMsg:(id)arg1 FromID:(unsigned long)arg2 Limit:(int)arg3;
- (id)GetMsgForSyncRead:(id)arg1 Where:(const struct WCTExpr *)arg2;
- (id)GetMsg:(id)arg1 Where:(const struct WCTExpr *)arg2 order:(const list_6bfdf17e *)arg3 Limit:(int)arg4 hasError:(char *)arg5;
- (id)GetFTSMsgRealChatUsrInTransaction:(id)arg1 forIdList:(id)arg2;
- (id)GetMsgForSimple:(id)arg1 Where:(const struct WCTExpr *)arg2 order:(const list_6bfdf17e *)arg3 Limit:(int)arg4 hasError:(char *)arg5;
- (id)GetMsg:(id)arg1 Where:(const struct WCTExpr *)arg2 order:(const list_6bfdf17e *)arg3 Limit:(int)arg4;
- (const list_6bfdf17e *)orderOfAscCreateTimeAndMsgLocalId;
- (const list_6bfdf17e *)orderOfDescCreateTimeAndMsgLocalId;
- (void)AddBackupMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)AddMsg:(id)arg1 MsgWrap:(id)arg2 withTimeFixed:(BOOL)arg3;
- (void)AddMsg:(id)arg1 MsgWrap:(id)arg2;
- (BOOL)runTransaction:(CDUnknownBlockType)arg1 event:(CDUnknownBlockType)arg2;
- (BOOL)runTransaction:(CDUnknownBlockType)arg1;
- (BOOL)rollbackTransaction;
- (BOOL)commitTransaction;
- (BOOL)beginTransaction;
- (void)InitDB:(id)arg1;
- (id)init;

@end

