//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface CSyncOplogWrap : NSObject
{
    unsigned long m_uiOplogID;
    unsigned long m_uiCmdID;
    NSMutableData *m_dtBuffer;
    unsigned long m_uiRetryCount;
    unsigned long m_uiItemID;
}

@property(nonatomic) unsigned long m_uiItemID; // @synthesize m_uiItemID;
@property(nonatomic) unsigned long m_uiRetryCount; // @synthesize m_uiRetryCount;
@property(retain, nonatomic) NSMutableData *m_dtBuffer; // @synthesize m_dtBuffer;
@property(nonatomic) unsigned long m_uiCmdID; // @synthesize m_uiCmdID;
@property(nonatomic) unsigned long m_uiOplogID; // @synthesize m_uiOplogID;
- (void).cxx_destruct;
- (id)init;

@end

