//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMessageWrap;

@interface CUploadVideoInfo : NSObject
{
    unsigned long m_uiUploadCount;
    unsigned long m_uiCurOffset;
    unsigned long m_uiCurOffsetCount;
    unsigned long m_uiZeroUploadCount;
    CMessageWrap *m_wrapMsg;
    unsigned long long m_ui64StartTime;
    unsigned long m_uiOpType;
    long m_nRetCode;
}

@property(nonatomic) long m_nRetCode; // @synthesize m_nRetCode;
@property(nonatomic) unsigned long m_uiOpType; // @synthesize m_uiOpType;
@property(nonatomic) unsigned long long m_ui64StartTime; // @synthesize m_ui64StartTime;
@property(retain, nonatomic) CMessageWrap *m_wrapMsg; // @synthesize m_wrapMsg;
@property(nonatomic) unsigned long m_uiZeroUploadCount; // @synthesize m_uiZeroUploadCount;
@property(nonatomic) unsigned long m_uiCurOffsetCount; // @synthesize m_uiCurOffsetCount;
@property(nonatomic) unsigned long m_uiCurOffset; // @synthesize m_uiCurOffset;
@property(nonatomic) unsigned long m_uiUploadCount; // @synthesize m_uiUploadCount;
- (void).cxx_destruct;
- (id)GetStatInfo;
- (id)description;
- (id)init;

@end

