//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSData, NSString;

@interface CUploadVoiceWrap : NSObject <WCTTableCoding>
{
    NSString *m_nsFromUsrName;
    NSString *m_nsToUsrName;
    long long m_n64SvrID;
    unsigned long m_uiLocalID;
    unsigned long m_uiOffset;
    unsigned long m_uiLen;
    unsigned long m_uiCreateTime;
    unsigned long m_uiVoiceLen;
    unsigned long m_uiVoiceTime;
    unsigned long m_uiVoiceFormat;
    unsigned long m_uiEndFlag;
    NSData *m_dtVoice;
    unsigned long m_uiRetryCount;
    unsigned long m_uiInsertQueueTime;
    unsigned long m_uiCancelFlag;
    unsigned long m_uiVoiceForwardFlag;
    unsigned long m_uiCgi;
    NSString *m_nsMsgThumbUrl;
    NSString *m_nsMsgSource;
    unsigned long m_uiStatus;
    NSString *m_nsExtend;
    NSString *ConStrRes2;
    NSString *ConStrRes3;
}

+ (const struct WCTProperty *)ConStrRes3;
+ (const struct WCTProperty *)ConStrRes2;
+ (const struct WCTProperty *)m_nsExtend;
+ (const struct WCTProperty *)m_uiVoiceFormat;
+ (const struct WCTProperty *)m_uiCancelFlag;
+ (const struct WCTProperty *)m_uiInsertQueueTime;
+ (const struct WCTProperty *)m_uiStatus;
+ (const struct WCTProperty *)m_uiRetryCount;
+ (const struct WCTProperty *)m_uiEndFlag;
+ (const struct WCTProperty *)m_uiVoiceTime;
+ (const struct WCTProperty *)m_uiLen;
+ (const struct WCTProperty *)m_uiOffset;
+ (const struct WCTProperty *)m_uiCreateTime;
+ (const struct WCTProperty *)m_n64SvrID;
+ (const struct WCTProperty *)m_uiLocalID;
+ (const struct WCTProperty *)m_nsToUsrName;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(retain, nonatomic) NSString *ConStrRes3; // @synthesize ConStrRes3;
@property(retain, nonatomic) NSString *ConStrRes2; // @synthesize ConStrRes2;
@property(retain, nonatomic) NSString *m_nsExtend; // @synthesize m_nsExtend;
@property(nonatomic) unsigned long m_uiVoiceFormat; // @synthesize m_uiVoiceFormat;
@property(nonatomic) unsigned long m_uiCancelFlag; // @synthesize m_uiCancelFlag;
@property(nonatomic) unsigned long m_uiInsertQueueTime; // @synthesize m_uiInsertQueueTime;
@property(nonatomic) unsigned long m_uiStatus; // @synthesize m_uiStatus;
@property(nonatomic) unsigned long m_uiRetryCount; // @synthesize m_uiRetryCount;
@property(nonatomic) unsigned long m_uiEndFlag; // @synthesize m_uiEndFlag;
@property(nonatomic) unsigned long m_uiVoiceTime; // @synthesize m_uiVoiceTime;
@property(nonatomic) unsigned long m_uiLen; // @synthesize m_uiLen;
@property(nonatomic) unsigned long m_uiOffset; // @synthesize m_uiOffset;
@property(nonatomic) unsigned long m_uiCreateTime; // @synthesize m_uiCreateTime;
@property(nonatomic) long long m_n64SvrID; // @synthesize m_n64SvrID;
@property(nonatomic) unsigned long m_uiLocalID; // @synthesize m_uiLocalID;
@property(retain, nonatomic) NSString *m_nsToUsrName; // @synthesize m_nsToUsrName;
@property(retain, nonatomic) NSString *m_nsMsgSource; // @synthesize m_nsMsgSource;
@property(nonatomic) unsigned long m_uiCgi; // @synthesize m_uiCgi;
@property(nonatomic) unsigned long m_uiVoiceForwardFlag; // @synthesize m_uiVoiceForwardFlag;
@property(retain, nonatomic) NSData *m_dtVoice; // @synthesize m_dtVoice;
@property(nonatomic) unsigned long m_uiVoiceLen; // @synthesize m_uiVoiceLen;
@property(retain, nonatomic) NSString *m_nsFromUsrName; // @synthesize m_nsFromUsrName;
- (void).cxx_destruct;
- (id)description;
- (id)init;

// Remaining properties
@property(nonatomic) BOOL isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

