//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface DBBottle : NSObject <WCTTableCoding>
{
    BOOL isAutoIncrement;
    unsigned long _localId;
    unsigned long _serverId;
    NSString *_encryptUserName;
    NSString *_bottleId;
    NSString *_ext;
    long long lastInsertedRowID;
}

+ (const struct WCTProperty *)ext;
+ (const struct WCTProperty *)bottleId;
+ (const struct WCTProperty *)encryptUserName;
+ (const struct WCTProperty *)serverId;
+ (const struct WCTProperty *)localId;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(retain, nonatomic) NSString *ext; // @synthesize ext=_ext;
@property(retain, nonatomic) NSString *bottleId; // @synthesize bottleId=_bottleId;
@property(retain, nonatomic) NSString *encryptUserName; // @synthesize encryptUserName=_encryptUserName;
@property(nonatomic) unsigned long serverId; // @synthesize serverId=_serverId;
@property(nonatomic) unsigned long localId; // @synthesize localId=_localId;
@property(nonatomic) long long lastInsertedRowID; // @synthesize lastInsertedRowID;
@property(nonatomic) BOOL isAutoIncrement; // @synthesize isAutoIncrement;
- (void).cxx_destruct;

@end

