//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSData, NSString;

@protocol DownloadVoiceDelegate

@optional
- (void)OnRecvData:(NSString *)arg1 MesLocalID:(unsigned long)arg2 n64MesSvrID:(long long)arg3 CreateTime:(unsigned long)arg4 VoiceTime:(unsigned long)arg5 Offset:(unsigned long)arg6 Len:(unsigned long)arg7 Data:(NSData *)arg8 EndFlag:(unsigned long)arg9 ErrNo:(unsigned long)arg10;
@end

