//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "EditImageToolDelegate.h"

@class CALayer, EditImageUIView, NSString, UIColor;

@interface EditImageMosaicTool : MMObject <EditImageToolDelegate>
{
    struct CGPoint _initialPoint;
    BOOL _initial;
    struct CGPath *_path;
    EditImageUIView *tView;
    CALayer *sLayer;
    BOOL _needImageLayer;
    id <MosaicToolDelegate> _delegate;
    UIColor *_lineColor;
    float _lineWidth;
    unsigned long _penCount;
    unsigned int _style;
}

@property(nonatomic) unsigned int _style; // @synthesize _style;
@property(nonatomic) unsigned long _penCount; // @synthesize _penCount;
@property(nonatomic) float _lineWidth; // @synthesize _lineWidth;
@property(retain, nonatomic) UIColor *_lineColor; // @synthesize _lineColor;
@property(nonatomic) BOOL _needImageLayer; // @synthesize _needImageLayer;
@property(nonatomic) __weak id <MosaicToolDelegate> _delegate; // @synthesize _delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)drawLayer;
- (struct CGRect)addPathWithP2Point:(struct CGPoint)arg1 withP1Point:(struct CGPoint)arg2 withCPoint:(struct CGPoint)arg3;
- (void)setInitialPoint:(struct CGPoint)arg1;
- (id)createView:(struct CGRect)arg1;
- (id)createLayer:(struct CGRect)arg1;
- (void)dataRetriveFromDelegate;
- (id)initWithStyle:(unsigned int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

