//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTextView.h"

@class EditImageTextBgView, UIColor;

@interface EditImageTextView : MMTextView
{
    unsigned int _textStyle;
    UIColor *_mainColor;
    float _scale;
    EditImageTextBgView *_textBgView;
}

@property(retain, nonatomic) EditImageTextBgView *textBgView; // @synthesize textBgView=_textBgView;
@property(nonatomic) float scale; // @synthesize scale=_scale;
@property(retain, nonatomic) UIColor *mainColor; // @synthesize mainColor=_mainColor;
@property(nonatomic) unsigned int textStyle; // @synthesize textStyle=_textStyle;
- (void).cxx_destruct;
- (void)updateBackgroundRects;
- (void)textChanged:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

