//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "EditImageToolDelegate.h"

@class CAShapeLayer, NSString, UIColor, UIImage, UIImageView;

@interface EditImagePenTool : MMObject <EditImageToolDelegate>
{
    struct CGPath *_path;
    struct CGPoint _initialPoint;
    BOOL _initial;
    CAShapeLayer *slayer;
    UIImageView *tView;
    UIImage *_cacheImg;
    struct CGPath *_subpath;
    BOOL _useLayerOnly;
    struct CGPath *_relayPath;
    CAShapeLayer *_tmpLayer;
    struct CGPath *_tmpPath;
    BOOL _renderDone;
    unsigned long _penCountLimit;
    UIColor *_lineColor;
    float _lineWidth;
    unsigned long _penCount;
    id __delegate;
    unsigned int _lineStyle;
    float _penScale;
}

@property(nonatomic) float penScale; // @synthesize penScale=_penScale;
@property(nonatomic) unsigned int lineStyle; // @synthesize lineStyle=_lineStyle;
@property(nonatomic) __weak id _delegate; // @synthesize _delegate=__delegate;
@property(nonatomic) unsigned long _penCount; // @synthesize _penCount;
@property(nonatomic) float _lineWidth; // @synthesize _lineWidth;
@property(retain, nonatomic) UIColor *_lineColor; // @synthesize _lineColor;
- (void).cxx_destruct;
- (void)dealloc;
- (void)drawLayer;
- (void)updateCachedImage;
- (struct CGRect)addPathWithP2Point:(struct CGPoint)arg1 withP1Point:(struct CGPoint)arg2 withCPoint:(struct CGPoint)arg3;
- (void)setInitialPoint:(struct CGPoint)arg1;
- (id)createView:(struct CGRect)arg1;
- (id)createLayer:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

