//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSMutableArray, NSString;

@interface EmoticonDownloadMd5ListObject : MMObject <PBCoding>
{
    NSMutableArray *m_md5List;
    unsigned long m_lastUpdateTime;
}

+ (id)getSavePath;
+ (id)getSaveRootDir;
+ (BOOL)IsItemExist;
+ (id)Instance;
+ (void)initialize;
@property(nonatomic) unsigned long m_lastUpdateTime; // @synthesize m_lastUpdateTime;
@property(retain, nonatomic) NSMutableArray *m_md5List; // @synthesize m_md5List;
- (void).cxx_destruct;
- (void)stickyMd5List:(id)arg1;
- (id)getMd5List;
- (void)saveToFile;
- (unsigned int)completeCount;
- (unsigned int)totalCount;
- (void)checkCompleteForMd5Object:(id)arg1;
- (int)checkCompleteAndReturnNeedMd5DownloadCount;
- (void)checkComplete;
- (void)clearMd5List;
- (id)getUnCompleteMd5Object;
- (void)failedMd5:(id)arg1;
- (id)completeMd5:(id)arg1;
- (void)removeMd5:(id)arg1;
- (id)filterExistedMd5:(id)arg1;
- (void)addMd5ObjectList:(id)arg1;
- (void)updateLastUpdateTime;
- (BOOL)moreThanADaySinceLastUpdateTime;
- (id)init;
- (void)dealloc;
- (const map_69681069 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

