//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SimpleImgInfo, UIView;

@protocol FavImageFullScreenViewContainerDelegate <NSObject>
- (void)onFullScreenItemDragEnd;
- (void)onFullScreenItemDragBegin;
- (void)onFullScreenItemChangeAlpha:(float)arg1;
- (void)onWillLongPress:(UIView *)arg1 onImage:(SimpleImgInfo *)arg2;
- (void)onLongPressEvent:(UIView *)arg1 onImage:(SimpleImgInfo *)arg2;
- (BOOL)useAlphaAnimation;
- (BOOL)shouldAnimationWhenHide;
- (void)onAnimateFadeOut;
- (void)animationHideWithRotate;
- (void)onContainerAnimationHideStop;
- (void)onContainerAnimationHideStart;
- (void)onContainerAnimationShowStop;
- (void)onContainerAnimationShowStart;
@end

