//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MyFavoritesDB;

@interface FavoritesItemDB : NSObject
{
    MyFavoritesDB *_mmDB;
}

- (void).cxx_destruct;
- (id)getLastUpdateFavoritesItem;
- (id)getLastFavoritesItem;
- (BOOL)getFavoritesItemList:(id)arg1 From:(unsigned long)arg2 Limit:(int)arg3;
- (BOOL)getDeletedItemList:(id)arg1;
- (BOOL)updateItemXMLInFavItemDB:(id)arg1;
- (BOOL)updateItemLocalStatus:(id)arg1;
- (BOOL)getAsyncUploadFailedItemList:(id)arg1;
- (BOOL)getAsyncUploadingItemList:(id)arg1;
- (id)checkBeforeAddItemByFavId:(unsigned long)arg1 andLocalId:(unsigned long)arg2;
- (unsigned long)getMaxLastUpdateTimeByUsrname:(id)arg1;
- (unsigned long)getItemCountByFromUsr:(id)arg1 andToUsr:(id)arg2;
- (unsigned long)getItemCountByUsrname:(id)arg1;
- (BOOL)getAllFavoritesItems:(id)arg1;
- (BOOL)updateItemUpdateTime:(unsigned long)arg1 ByLocalId:(unsigned long)arg2;
- (BOOL)updateUpdateSeq:(unsigned long)arg1 ByFavId:(unsigned long)arg2;
- (BOOL)getNextPageFavoritesCapacityItemList:(id)arg1 andMinSize:(unsigned long)arg2;
- (BOOL)getFirstPageFavoritesCapacityItemList:(id)arg1;
- (BOOL)getNextPageNeedBatchGetFavoritesItemList:(id)arg1 byType:(int)arg2 andMinUpdateTime:(unsigned long)arg3;
- (BOOL)getFirstPageNeedBatchGetFavoritesItemList:(id)arg1 byType:(int)arg2;
- (BOOL)getNeedBatchGetFavoritesItemList:(id)arg1 byType:(int)arg2 andMinUpdateTime:(unsigned long)arg3;
- (BOOL)getNextPageFavoritesItemList:(id)arg1 byType:(int)arg2 andCurMinUpdateTime:(unsigned long)arg3;
- (BOOL)getFirstPageFavoritesItemListContainUnBatchGet:(id)arg1;
- (BOOL)getFirstPageFavoritesItemList:(id)arg1 byType:(int)arg2;
- (BOOL)updateItemInFavItemDBByFavObject:(id)arg1;
- (BOOL)updateItemInFavItemDB:(id)arg1;
- (BOOL)getDownloadFailedItemList:(id)arg1;
- (BOOL)getUploadFailedItemList:(id)arg1;
- (BOOL)getDownloadingItemList:(id)arg1;
- (BOOL)getUploadingItemList:(id)arg1;
- (BOOL)deleteFavoritesItemByLocalItemId:(unsigned long)arg1;
- (BOOL)deleteFavoritesItemById:(unsigned long)arg1;
- (id)getFavoritesItemBySourceId:(id)arg1;
- (id)getFavoritesItemByLocalId:(unsigned long)arg1;
- (id)getFavoritesItemById:(unsigned long)arg1;
- (id)getDBItemById:(unsigned long)arg1;
- (BOOL)insertNewRowInFavoritesItem:(id)arg1 XML:(id)arg2;
- (void)fillLegalItemsArray:(id)arg1 withDBItems:(id)arg2;
- (void)fillItemsArray:(id)arg1 withDBItems:(id)arg2;
- (void)fillDBFavItem:(id)arg1 fromFavObject:(id)arg2;
- (void)fillDBFavItem:(id)arg1 fromFavItem:(id)arg2 xml:(id)arg3;
- (void)fillDBFavItem:(id)arg1 fromFavItem:(id)arg2;
- (BOOL)getFavoritesItemValue:(id)arg1 fromDBItem:(id)arg2;
- (BOOL)runTransaction:(CDUnknownBlockType)arg1 event:(CDUnknownBlockType)arg2;
- (BOOL)runTransaction:(CDUnknownBlockType)arg1;
- (void)initDB:(id)arg1;
- (id)init;

@end

