//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface FavoritesCDNInfo : NSObject <WCTTableCoding>
{
    unsigned long localItemId;
    NSString *localDataID;
    NSString *cdnUrl;
    unsigned long size;
    long status;
    NSString *cdnKey;
    NSString *md5;
    NSString *head256Md5;
    long isThumb;
    long dataType;
    NSString *streamId;
    NSString *dataFmt;
    NSString *clientMsgID;
    unsigned long IntRes1;
    unsigned long IntRes2;
    NSString *StrRes1;
    NSString *StrRes2;
}

+ (const struct WCTProperty *)StrRes2;
+ (const struct WCTProperty *)StrRes1;
+ (const struct WCTProperty *)IntRes2;
+ (const struct WCTProperty *)IntRes1;
+ (const struct WCTProperty *)clientMsgID;
+ (const struct WCTProperty *)dataFmt;
+ (const struct WCTProperty *)streamId;
+ (const struct WCTProperty *)dataType;
+ (const struct WCTProperty *)isThumb;
+ (const struct WCTProperty *)head256Md5;
+ (const struct WCTProperty *)md5;
+ (const struct WCTProperty *)cdnKey;
+ (const struct WCTProperty *)status;
+ (const struct WCTProperty *)size;
+ (const struct WCTProperty *)cdnUrl;
+ (const struct WCTProperty *)localDataID;
+ (const struct WCTProperty *)localItemId;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(retain, nonatomic) NSString *StrRes2; // @synthesize StrRes2;
@property(retain, nonatomic) NSString *StrRes1; // @synthesize StrRes1;
@property(nonatomic) unsigned long IntRes2; // @synthesize IntRes2;
@property(nonatomic) unsigned long IntRes1; // @synthesize IntRes1;
@property(retain, nonatomic) NSString *clientMsgID; // @synthesize clientMsgID;
@property(retain, nonatomic) NSString *dataFmt; // @synthesize dataFmt;
@property(retain, nonatomic) NSString *streamId; // @synthesize streamId;
@property(nonatomic) long dataType; // @synthesize dataType;
@property(nonatomic) long isThumb; // @synthesize isThumb;
@property(retain, nonatomic) NSString *head256Md5; // @synthesize head256Md5;
@property(retain, nonatomic) NSString *md5; // @synthesize md5;
@property(retain, nonatomic) NSString *cdnKey; // @synthesize cdnKey;
@property(nonatomic) long status; // @synthesize status;
@property(nonatomic) unsigned long size; // @synthesize size;
@property(retain, nonatomic) NSString *cdnUrl; // @synthesize cdnUrl;
@property(retain, nonatomic) NSString *localDataID; // @synthesize localDataID;
@property(nonatomic) unsigned long localItemId; // @synthesize localItemId;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(nonatomic) BOOL isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

