//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "INetworkStatusMgrExt.h"
#import "PBMessageObserverDelegate.h"

@class FavoritesItemDB, NSMutableArray;

@interface FavoritesBatchGetMgr : MMObject <PBMessageObserverDelegate, INetworkStatusMgrExt>
{
    FavoritesItemDB *_favItemDB;
    NSMutableArray *_batchGetArray;
    id <FavoritesBatchGetMgrDelegate> _delegate;
    BOOL _isGetting;
    unsigned long _autoBatchGetCount;
    BOOL _hasStartBatchGet;
}

@property(nonatomic) __weak id <FavoritesBatchGetMgrDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)shouldBetchGetAll;
- (void)onNetworkStatusChange:(unsigned long)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)HandleBatchGetFavItemResp:(id)arg1 Event:(unsigned long)arg2;
- (void)asyncDoAddNewItemList:(id)arg1;
- (BOOL)checkConflict:(id)arg1 vs:(id)arg2;
- (void)TryStartBatchGet;
- (void)addBatchGetFavoritesItemList:(id)arg1;
- (void)dealloc;
- (void)initDB:(id)arg1;
- (id)init;

@end

