//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FavRightTopMenuData : NSObject
{
    unsigned long _tagId;
    NSString *_iconName;
    NSString *_title;
}

@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(nonatomic) unsigned long tagId; // @synthesize tagId=_tagId;
- (void).cxx_destruct;
- (id)initWithTagId:(unsigned long)arg1 iconName:(id)arg2 title:(id)arg3;

@end

