//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FavWeAppItem : NSObject
{
    NSString *_appUserName;
    NSString *_title;
    NSString *_desc;
    NSString *_thumbUrl;
    NSString *_pagePath;
    unsigned long _debugMode;
    NSString *_userName;
    NSString *_sourceDisplayName;
    NSString *_appId;
    unsigned long _appType;
    unsigned long _pkgType;
}

@property(nonatomic) unsigned long pkgType; // @synthesize pkgType=_pkgType;
@property(nonatomic) unsigned long appType; // @synthesize appType=_appType;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(copy, nonatomic) NSString *sourceDisplayName; // @synthesize sourceDisplayName=_sourceDisplayName;
@property(copy, nonatomic) NSString *pagePath; // @synthesize pagePath=_pagePath;
@property(copy, nonatomic) NSString *thumbUrl; // @synthesize thumbUrl=_thumbUrl;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

