//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSMutableDictionary, NSString;

@interface FBSDKLoginManagerLogger : NSObject
{
    NSString *_identifier;
    NSMutableDictionary *_extras;
    NSString *_lastResult;
    NSError *_lastError;
    unsigned int _loginBehavior;
}

+ (id)loggerFromParameters:(id)arg1;
- (void).cxx_destruct;
- (id)parametersForNewEventWithBehavior:(const unsigned int *)arg1;
- (id)identifierForBehavior:(unsigned int)arg1;
- (id)clientStateForBehavior:(unsigned int)arg1;
- (void)systemAuthDidShowDialog:(BOOL)arg1 isUnTOSedDevice:(BOOL)arg2;
- (void)willAttemptAppSwitchingBehavior;
- (id)parametersWithTimeStampAndClientState:(id)arg1 forLoginBehavior:(unsigned int)arg2;
- (void)endLoginWithResult:(unsigned int)arg1 error:(id)arg2;
- (void)startLoginWithBehavior:(unsigned int)arg1;
- (void)endEvent;
- (void)startEventWithBehavior:(unsigned int)arg1 isReauthorize:(BOOL)arg2;
- (id)init;

@end

