//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface FICEntityMetadata : NSObject <PBCoding>
{
    BOOL _hasImageCache;
    unsigned int entityIndex;
    unsigned int eliminationFactor;
    unsigned int LRUFactor;
    NSString *_entityUUID;
    unsigned int _entityUsedCount;
}

+ (void)initialize;
@property(nonatomic) BOOL hasImageCache; // @synthesize hasImageCache=_hasImageCache;
@property(nonatomic) unsigned int entityUsedCount; // @synthesize entityUsedCount=_entityUsedCount;
@property(retain, nonatomic) NSString *entityUUID; // @synthesize entityUUID=_entityUUID;
@property(nonatomic) unsigned int LRUFactor; // @synthesize LRUFactor;
@property(nonatomic) unsigned int eliminationFactor; // @synthesize eliminationFactor;
@property(nonatomic) unsigned int entityIndex; // @synthesize entityIndex;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (const map_69681069 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

