//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FTSTopHitDynamicUtil : NSObject
{
}

+ (int)ParseScoreInterval:(unsigned long)arg1;
+ (void)PrintLogs;
+ (BOOL)isSupportTopHitRemoval;
+ (unsigned long)CalDeclineScoreForMMGroup:(unsigned long)arg1;
+ (unsigned long)CalDeclineScore:(unsigned long)arg1;
+ (unsigned long)CalRaiseScore:(unsigned long)arg1;
+ (unsigned long)GetMaxDivScore;
+ (unsigned long)GetLeastDisplayScore;
+ (unsigned long)GetTopHitItemSurvivalDays;

@end

