//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FunctionSwitchUtil : NSObject
{
}

+ (void)setModPushExtStatusSwitch:(unsigned long)arg1 statusBit:(unsigned long)arg2 setOpen:(BOOL)arg3 sync:(BOOL)arg4;
+ (BOOL)addModPushSwitchOplog:(unsigned long)arg1 SwitchValue:(unsigned long)arg2 sync:(BOOL)arg3;
+ (void)setExtStatusSwitchInvertedAtServer:(unsigned long)arg1 statusBit:(unsigned long)arg2 setClose:(BOOL)arg3 sync:(BOOL)arg4;
+ (void)setExtStatusSwitch:(unsigned long)arg1 statusBit:(unsigned long)arg2 setOpen:(BOOL)arg3 sync:(BOOL)arg4;
+ (void)setStatusSwitch:(unsigned long)arg1 statusBit:(unsigned long)arg2 setOpen:(BOOL)arg3 sync:(BOOL)arg4;
+ (void)setPluginSwitch:(unsigned long)arg1 statusBit:(unsigned long)arg2 setOpen:(BOOL)arg3 sync:(BOOL)arg4;
+ (BOOL)addSwitchOplog:(unsigned long)arg1 SwitchValue:(unsigned long)arg2 sync:(BOOL)arg3;
+ (unsigned long)convertType:(unsigned long)arg1;

@end

