//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface FunctionMessage : NSObject <PBCoding>
{
    NSString *functionMsgId;
    NSString *chatName;
    unsigned long opType;
    long long msgSvrId;
    unsigned long long version;
}

+ (void)initialize;
@property(nonatomic) unsigned long opType; // @synthesize opType;
@property(retain, nonatomic) NSString *chatName; // @synthesize chatName;
@property(retain, nonatomic) NSString *functionMsgId; // @synthesize functionMsgId;
@property(nonatomic) unsigned long long version; // @synthesize version;
@property(nonatomic) long long msgSvrId; // @synthesize msgSvrId;
- (void).cxx_destruct;
- (const map_69681069 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

