//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSArray, NSString;

@interface GiftCenterData : MMObject <PBCoding>
{
    NSString *title;
    NSString *desc;
    unsigned long type;
    NSString *jumpUrl;
    NSString *imgUrl;
    NSArray *signGiftList;
    unsigned long positionId;
    NSString *externInfo;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *externInfo; // @synthesize externInfo;
@property(nonatomic) unsigned long positionId; // @synthesize positionId;
@property(retain, nonatomic) NSArray *signGiftList; // @synthesize signGiftList;
@property(retain, nonatomic) NSString *imgUrl; // @synthesize imgUrl;
@property(retain, nonatomic) NSString *jumpUrl; // @synthesize jumpUrl;
@property(nonatomic) unsigned long type; // @synthesize type;
@property(retain, nonatomic) NSString *desc; // @synthesize desc;
@property(retain, nonatomic) NSString *title; // @synthesize title;
- (void).cxx_destruct;
- (void)parse:(id)arg1;
- (const map_69681069 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

