//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@protocol IViewControllerExt <NSObject>

@optional
- (void)onViewDidAppear:(UIViewController *)arg1;
- (void)onViewWillAppear:(BOOL)arg1 landscapeForbidden:(BOOL)arg2;
@end

