//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "MMService.h"
#import "QMapViewDelegate.h"

@class MMTimer, NSMutableArray, NSMutableDictionary, NSString, QMapView, UIView;

@interface LocationThumbMgr : MMService <QMapViewDelegate, IMsgExt, MMService>
{
    QMapView *_mapView;
    UIView *_mapPinView;
    NSMutableDictionary *_taskDic;
    NSMutableArray *_taskQueue;
    MMTimer *_taskTimer;
    BOOL _isUpdating;
    BOOL _hasReportLocateError;
}

+ (id)getThumbPathWithChatname:(id)arg1 MsgLocalID:(unsigned long)arg2;
- (void).cxx_destruct;
- (void)OnDelMsg:(id)arg1 DelAll:(BOOL)arg2;
- (void)OnDelMsg:(id)arg1 MsgWrap:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 didFailToLocateUserWithError:(id)arg2;
- (void)mapViewDidFailLoadingMap:(id)arg1 withError:(id)arg2;
- (void)deleteThumbImageWithChatname:(id)arg1 MsgLocalID:(unsigned long)arg2;
- (void)saveThumbImage:(id)arg1 Chatname:(id)arg2 MsgLocalID:(unsigned long)arg3;
- (void)loadMapView:(id)arg1;
- (void)initMapView;
- (void)onTaskFailedWithError:(int)arg1;
- (void)asyncGenThumbImage;
- (void)deleteThumbTask:(id)arg1;
- (void)addThumbTask:(id)arg1;
- (void)startNextTask;
- (void)notifyTimeout;
- (void)onTimeout;
- (int)stopUpdate;
- (int)startUpdate;
- (int)deleteLocationThumb:(id)arg1 MsgLocalID:(unsigned long)arg2;
- (int)updateLocationThumb:(id)arg1;
- (id)getLocationThumb:(id)arg1 MsgLocalID:(unsigned long)arg2;
- (void)cleanResource;
- (void)enterForeground;
- (void)enterBackground;
- (void)dealloc;
- (BOOL)onServiceMemoryWarning;
- (void)onServiceReloadData;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

