//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MessageImageUtil : NSObject
{
}

+ (id)toProgressiveJpegData:(id)arg1 Msg:(id)arg2;
+ (BOOL)isProgressiveImageData:(id)arg1;
+ (BOOL)isProgressiveImage:(id)arg1;
+ (BOOL)isMessageThumbImageSizeOk:(id)arg1 path:(id)arg2;
+ (BOOL)isMessageThumbImageSizeOk:(id)arg1;
+ (BOOL)isMessageNormalImageSizeOk:(id)arg1;
+ (BOOL)isMessageHDImageSizeOk:(id)arg1;
+ (id)genThumbnailImage:(id)arg1;

@end

