//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MKMapView.h"

@interface MKMapView (ZoomLevel)
- (unsigned int)getCurrZoomLevel;
- (void)setCenterCoordinate:(struct CLLocationCoordinate2D)arg1 zoomLevel:(unsigned int)arg2 animated:(BOOL)arg3;
- (CDStruct_951efa70)coordinateSpanWithMapView:(id)arg1 centerCoordinate:(struct CLLocationCoordinate2D)arg2 andZoomLevel:(unsigned int)arg3;
- (double)pixelSpaceYToLatitude:(double)arg1;
- (double)pixelSpaceXToLongitude:(double)arg1;
- (double)latitudeToPixelSpaceY:(double)arg1;
- (double)longitudeToPixelSpaceX:(double)arg1;
@end

