//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMAlbumDataProviderForPHAssetFramework : NSObject
{
}

+ (id)firstAlbumWithShouldIncludeVideo:(BOOL)arg1 isOnlyShowVideo:(BOOL)arg2;
+ (id)getAlbumIdentifiers:(id)arg1 shouldIncludeVideo:(BOOL)arg2 isOnlyShowVideo:(BOOL)arg3;
+ (id)getAlbumIdentifier:(id)arg1 shouldIncludeVideo:(BOOL)arg2 isOnlyShowVideo:(BOOL)arg3;
+ (id)getAlbumFromAlbumType:(int)arg1 ForSubType:(int)arg2 shouldIncludeVideo:(BOOL)arg3 isOnlyShowVideo:(BOOL)arg4;
+ (id)getAlbumSortEndDateFromAlbumType:(int)arg1 ForSubType:(int)arg2 shouldIncludeVideo:(BOOL)arg3 isOnlyShowVideo:(BOOL)arg4;
+ (void)AllMMAlbumsForPHFrameworkWith:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2 shouldIncludeVideo:(BOOL)arg3 isOnlyShowVideo:(BOOL)arg4;

@end

