//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface MMAlbumDataProvider : MMObject
{
}

+ (void)tryUpdateAlbumChangeObserver;
+ (void)internalInitAlbumChangeObserver;
+ (void)tryInitAlbumChangeObserver;
+ (void)FetchLastMMAssetWith:(CDUnknownBlockType)arg1 inSecond:(double)arg2;
+ (void)FetchMMAlbumWithID:(id)arg1 With:(CDUnknownBlockType)arg2 errorBlock:(CDUnknownBlockType)arg3 shouldIncludeVideo:(BOOL)arg4 isOnlyShowVideo:(BOOL)arg5;
+ (void)FirstMMAlbumWith:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2 shouldIncludeVideo:(BOOL)arg3 isOnlyShowVideo:(BOOL)arg4;
+ (void)requestAuthorizeIfNeededWithResultBlock:(CDUnknownBlockType)arg1;
+ (BOOL)isUserAuthorize;
+ (BOOL)isAuthorize;
+ (void)AllMMAlbumsWith:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2 shouldIncludeVideo:(BOOL)arg3 isOnlyShowVideo:(BOOL)arg4;

@end

