//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIImageView.h"

#import "ICdnComMgrExt.h"

@class NSString, UIImage;

@interface MMCDNImageView : MMUIImageView <ICdnComMgrExt>
{
    UIImage *_defaultImage;
    NSString *_localSrcPath;
    NSString *_cdnUrl;
    NSString *_aesKey;
    unsigned long _datasize;
    NSString *_clientID;
    unsigned long _fileType;
    BOOL _isCompressImage;
    BOOL _isloaded;
    BOOL _autoDownloadNoWifi;
    BOOL _isClipImage;
    BOOL _isFromC2C;
    NSString *_localSrcTmpPath;
    BOOL _isNewFavList;
}

@property(nonatomic) BOOL isNewFavList; // @synthesize isNewFavList=_isNewFavList;
@property(nonatomic) BOOL isFromC2C; // @synthesize isFromC2C=_isFromC2C;
@property(nonatomic) BOOL isClipImage; // @synthesize isClipImage=_isClipImage;
@property(nonatomic) BOOL autoDownloadNoWifi; // @synthesize autoDownloadNoWifi=_autoDownloadNoWifi;
@property(nonatomic) BOOL isCompressImage; // @synthesize isCompressImage=_isCompressImage;
@property(nonatomic) unsigned long fileType; // @synthesize fileType=_fileType;
@property(nonatomic) unsigned long dataSize; // @synthesize dataSize=_datasize;
@property(retain, nonatomic) NSString *aesKey; // @synthesize aesKey=_aesKey;
@property(retain, nonatomic) NSString *cdnUrl; // @synthesize cdnUrl=_cdnUrl;
@property(retain, nonatomic) NSString *localSrcPath; // @synthesize localSrcPath=_localSrcPath;
- (void).cxx_destruct;
- (void)dealloc;
- (void)OnCdnDownload:(id)arg1;
- (void)stopLoadingImage;
- (BOOL)startLoadingImage;
- (void)loadingImageWithGCD;
- (id)clipImage:(id)arg1 withData:(id)arg2;
- (id)compressImage:(id)arg1;
- (void)setDefaultImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

