//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "WCDBCorruptReportExt.h"
#import "WCDBRestoreProtocol.h"

@class MMDBRestoreReport, NSString;

@interface MMDBRestoreManager : MMService <MMService, WCDBRestoreProtocol, WCDBCorruptReportExt>
{
    MMDBRestoreReport *m_reporter;
    BOOL m_needBinning;
    BOOL m_pauseBinning;
    int m_restoreCount;
    int m_restoreDoneCount;
}

@property BOOL m_pauseBinning; // @synthesize m_pauseBinning;
@property int m_restoreDoneCount; // @synthesize m_restoreDoneCount;
@property int m_restoreCount; // @synthesize m_restoreCount;
@property BOOL m_needBinning; // @synthesize m_needBinning;
- (void).cxx_destruct;
- (void)ReportDatabaseCorrupt:(id)arg1;
- (Class)classFromTableName:(id)arg1;
- (void)onRepairProgressUpdate:(float)arg1;
- (long long)restoreRequireSize;
- (id)errorDescription:(id)arg1;
- (BOOL)needRestore;
- (BOOL)needBinning;
- (int)binningCount;
- (void)resetInitMark:(BOOL)arg1;
- (BOOL)restoreWithError:(id *)arg1 isAutoRestore:(BOOL)arg2;
- (id)findBinningPathsFrom:(id)arg1;
- (id)binningDirectoriesFrom:(id)arg1;
- (BOOL)binning;
- (void)setupMMDB:(id)arg1;
- (void)clearBinning:(BOOL)arg1;
- (void)dealloc;
- (id)reporter;
- (void)onServiceInit;
- (void)checkRemindFromWechatTeam;
- (void)pauseBinning;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

