//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "crashReportConnectionDelegate.h"

@class MMCrashReportConnection, NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface MMDumpReportTask : NSObject <crashReportConnectionDelegate>
{
    NSMutableArray *m_arrUploadingItems;
    MMCrashReportConnection *m_connect;
    BOOL m_bUploading;
    NSString *m_nsUsrName;
    unsigned int m_totalUploadCount;
    unsigned int m_uploadedCount;
    NSObject<OS_dispatch_queue> *wxg_serialQueue;
    BOOL m_quickUpload;
    id <MMDumpReporterDelegate> m_delegate;
    unsigned int m_reportCntOneTime;
    NSMutableArray *m_arrReportData;
    NSString *m_nsTag;
    unsigned int m_reportType;
}

@property(nonatomic) BOOL m_quickUpload; // @synthesize m_quickUpload;
@property(nonatomic) unsigned int m_reportType; // @synthesize m_reportType;
@property(retain, nonatomic) NSString *m_nsTag; // @synthesize m_nsTag;
@property(retain, nonatomic) NSMutableArray *m_arrReportData; // @synthesize m_arrReportData;
@property(nonatomic) unsigned int m_reportCntOneTime; // @synthesize m_reportCntOneTime;
@property(nonatomic) __weak id <MMDumpReporterDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (unsigned int)getUploadFilesCount;
- (BOOL)filesEmpty;
- (id)getUsrName;
- (void)onUploadCrashCompleted:(BOOL)arg1 CrashWrap:(id)arg2;
- (void)uploadOneReportData;
- (void)upload;
- (void)cancelTask;
- (void)dealloc;
- (id)initWithDispatchQueue:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

