//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMComponentData.h"

@class MMMusicInfo, NSString;

@interface MMFavThumbComponentData : MMComponentData
{
    BOOL m_isCDN;
    NSString *m_datafmt;
    NSString *m_thumbUrl;
    NSString *m_ThumbPath;
    NSString *m_CDNThumbUrl;
    NSString *m_CDNThumbKey;
    unsigned long m_CDNThumbSize;
    int favType;
    MMMusicInfo *m_musicInfo;
}

@property(retain, nonatomic) MMMusicInfo *m_musicInfo; // @synthesize m_musicInfo;
@property(nonatomic) int favType; // @synthesize favType;
@property(nonatomic) unsigned long m_CDNThumbSize; // @synthesize m_CDNThumbSize;
@property(retain, nonatomic) NSString *m_CDNThumbKey; // @synthesize m_CDNThumbKey;
@property(retain, nonatomic) NSString *m_CDNThumbUrl; // @synthesize m_CDNThumbUrl;
@property(retain, nonatomic) NSString *m_ThumbPath; // @synthesize m_ThumbPath;
@property(nonatomic) BOOL m_isCDN; // @synthesize m_isCDN;
@property(retain, nonatomic) NSString *m_thumbUrl; // @synthesize m_thumbUrl;
@property(retain, nonatomic) NSString *m_datafmt; // @synthesize m_datafmt;
- (void).cxx_destruct;

@end

