//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMFICImageTableChunk, NSString;

@interface MMFICImageTableEntry : NSObject
{
    MMFICImageTableChunk *_imageTableChunk;
    void *_bytes;
    unsigned long _entryLength;
    unsigned long _imageLength;
    NSString *_entityUUID;
}

+ (unsigned long)entryLengthWithImageLength:(unsigned long)arg1;
@property(readonly, nonatomic) MMFICImageTableChunk *imageTableChunk; // @synthesize imageTableChunk=_imageTableChunk;
@property(retain, nonatomic) NSString *entityUUID; // @synthesize entityUUID=_entityUUID;
@property(readonly, nonatomic) unsigned long imageLength; // @synthesize imageLength=_imageLength;
@property(readonly, nonatomic) unsigned long entryLength; // @synthesize entryLength=_entryLength;
- (void).cxx_destruct;
- (BOOL)flush;
- (BOOL)checkValid;
- (id)initWithImageTableChunk:(id)arg1 bytes:(void *)arg2 entryLength:(unsigned long)arg3 imageLength:(unsigned long)arg4;
- (CDStruct_2c0d991e *)_tailMetadata;
- (CDStruct_2c0d991e *)_headMetadata;
@property(nonatomic) CDStruct_bd2f613f sourceImageUUIDBytes;
@property(nonatomic) CDStruct_bd2f613f entityUUIDBytes;
@property(readonly, nonatomic) void *imageAddress;
@property(readonly, nonatomic) void *entryAddress;

@end

