//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMFICImageTableChunk : NSObject
{
    unsigned int _index;
    void *_bytes;
    unsigned long _length;
    long long _fileOffset;
}

@property(readonly, nonatomic) unsigned long length; // @synthesize length=_length;
@property(readonly, nonatomic) long long fileOffset; // @synthesize fileOffset=_fileOffset;
@property(readonly, nonatomic) unsigned int index; // @synthesize index=_index;
@property(readonly, nonatomic) void *bytes; // @synthesize bytes=_bytes;
- (void)dealloc;
- (id)initWithFileDescriptor:(int)arg1 index:(unsigned int)arg2 length:(unsigned long)arg3;

@end

