//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "IContactMgrExt.h"
#import "IEnterpriseContactMgrExt.h"
#import "IHeadImageExt.h"
#import "IKFContactExt.h"
#import "IMsgExt.h"
#import "IStrangerContactMgrExt.h"
#import "LongPressImageViewDelegate.h"

@class MMUILongPressImageView, NSString, UIImage, UIImageView;

@interface MMHeadImageView : MMUIView <IKFContactExt, IEnterpriseContactMgrExt, LongPressImageViewDelegate, IMsgExt, IHeadImageExt, IContactMgrExt, IStrangerContactMgrExt>
{
    MMUILongPressImageView *_headImageView;
    UIImageView *_borderImageView;
    NSString *_nsHeadImgUrl;
    NSString *_nsUsrName;
    BOOL _bAutoUpdate;
    struct CGSize _imageSize;
    UIImage *_borderImage;
    UIImage *_borderImageHL;
    BOOL _addBorder;
    BOOL _bRoundedCorner;
    id _oTarget;
    SEL _selAction;
    id _object;
    id _oLongPressTarget;
    SEL _selLongPressAction;
    id _oLongPressObject;
    UIImageView *_sceneImageView;
    unsigned long _conerSize;
    UIImage *_defaultImage;
    unsigned char _headUseScene;
    unsigned char _headCategory;
    BOOL _isHeadImgExistedLocal;
}

@property(nonatomic) unsigned char headCategory; // @synthesize headCategory=_headCategory;
@property(nonatomic) unsigned char headUseScene; // @synthesize headUseScene=_headUseScene;
@property(retain, nonatomic) UIImage *defaultImage; // @synthesize defaultImage=_defaultImage;
@property(nonatomic) unsigned long conerSize; // @synthesize conerSize=_conerSize;
@property(readonly, nonatomic) NSString *nsUsrName; // @synthesize nsUsrName=_nsUsrName;
@property(nonatomic) BOOL addBorder; // @synthesize addBorder=_addBorder;
@property(retain, nonatomic) UIImage *borderImageHL; // @synthesize borderImageHL=_borderImageHL;
@property(retain, nonatomic) UIImage *borderImage; // @synthesize borderImage=_borderImage;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
- (void).cxx_destruct;
- (void)OnLongPress:(id)arg1;
- (void)OnPress:(id)arg1;
- (void)onModifyEnterpriseContact:(id)arg1;
- (void)onStrangerContactUpdated:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)addSceneImageView:(int)arg1;
- (void)updateHeadImage:(id)arg1;
- (void)setTargetForLongPress:(id)arg1 action:(SEL)arg2;
- (void)setTarget:(id)arg1 action:(SEL)arg2 withObject:(id)arg3;
- (void)setTarget:(id)arg1 action:(SEL)arg2;
- (void)onKFContactHeadImgUpdate:(id)arg1;
- (void)onHeadImageChange:(id)arg1;
- (void)updateExtensionRegister;
- (void)updateUsrName:(id)arg1 withHeadImgUrl:(id)arg2;
- (id)getRealUserName:(id)arg1;
- (void)doUpdateHeadImg:(BOOL)arg1;
- (void)checkAndUpdateImage;
- (void)setHeadImageByName:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (void)dealloc;
- (id)initWithUsrName:(id)arg1 headImgUrl:(id)arg2 bAutoUpdate:(BOOL)arg3 bRoundCorner:(BOOL)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

