//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MMLSDataItem : NSObject
{
    int fileType;
    NSString *filePath;
    unsigned long fileTime;
    NSString *session;
    NSString *userName;
    unsigned long mesLocalId;
    unsigned long long fileSize;
}

+ (BOOL)dataItemCompareItem:(id)arg1 withItem:(id)arg2;
@property(nonatomic) unsigned long mesLocalId; // @synthesize mesLocalId;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;
@property(retain, nonatomic) NSString *session; // @synthesize session;
@property(nonatomic) unsigned long fileTime; // @synthesize fileTime;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize;
@property(nonatomic) int fileType; // @synthesize fileType;
- (void).cxx_destruct;
- (id)init;

@end

