//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSearchBarDisplayController.h"

#import "EmoticonBoughtListMgrExt.h"
#import "EmoticonRecommendMgrExt.h"
#import "EmoticonStoreCellDelegate.h"
#import "EmoticonStoreMgrExt.h"
#import "EmotionCollectionFooterViewDelegate.h"
#import "LoopPageScrollViewDataSourceDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class EmotionCollectionFooterView, LoopPageScrollView, MMEmotionStoreNewSearchController, MMTimer, MMUIButton, NSMutableArray, NSString, UICollectionView, UICollectionViewFlowLayout, UIImageView, UIView, UIViewController;

@interface MMPersonalEmotionsViewController : MMSearchBarDisplayController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, EmoticonStoreMgrExt, EmoticonBoughtListMgrExt, LoopPageScrollViewDataSourceDelegate, EmoticonStoreCellDelegate, EmotionCollectionFooterViewDelegate, EmoticonRecommendMgrExt>
{
    UICollectionView *_collectionView;
    UICollectionViewFlowLayout *_layout;
    UIView *m_collectionHeaderView;
    MMUIButton *m_designerEmojiEntranceView;
    UIImageView *m_designerEmojiEntranceReddot;
    LoopPageScrollView *_bannerView;
    EmotionCollectionFooterView *_footerView;
    NSMutableArray *_storeItemArray;
    NSMutableArray *_storeAdsArray;
    unsigned long _scene;
    unsigned long _reqType;
    BOOL _isLoadedFromCache;
    unsigned long _topHotNum;
    MMTimer *_timer;
    UIView *_chartsContainerView;
    BOOL m_isOpenDesignerEmoji;
    UIViewController *m_contentsViewController;
    MMEmotionStoreNewSearchController *m_searchController;
}

- (void).cxx_destruct;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)OnEmoticonRecommendNewStateChangedForDesignerEmojiEntranceNew:(BOOL)arg1;
- (void)MMRefreshCollectionFooterDidTriggerRefresh:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)OnShowAlertWithIKnow:(id)arg1;
- (void)OnShowAlertWithOK:(id)arg1;
- (void)OnStopLoading;
- (void)OnStartLoadingAndShowStringBlocked:(id)arg1;
- (void)OnStopLoadingAndShowError:(id)arg1;
- (void)OnStopLoadingAndShowOK:(id)arg1;
- (void)OnStartLoadingAndShowString:(id)arg1;
- (void)openPageForBannerSet:(id)arg1 IsFromBanner:(BOOL)arg2;
- (void)didTapPageAtNum:(unsigned long)arg1;
- (void)didChangeToPage:(unsigned long)arg1;
- (int)totalNumOfPage;
- (id)viewForPage:(id)arg1 pageNum:(unsigned long)arg2;
- (void)OnStoreListChanged:(id)arg1 withRet:(int)arg2 withReqType:(unsigned long)arg3 Response:(id)arg4;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(int)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(int)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(int)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)viewDidTransitionToNewSize;
- (void)viewDidLayoutSubviews;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (void)setupChartsContainerWithHeaderView:(id)arg1;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)clickDesignerEmojiEntrance;
- (void)clickEmotionCharts;
- (void)adjustContentInsetAndSearchBarMask;
- (void)tryInitViewOfSearchController;
- (void)reloadAdsFromMgr;
- (void)reloadData;
- (void)configDesignerEmojiEntranceView;
- (void)configBanner;
- (void)configHeaderView;
- (void)configCollectionView;
- (void)configData;
- (void)configViews;
- (void)changeBannerToNextPage;
- (void)initBannerPageTimer;
- (void)stopBannerPageTimer;
- (void)clearSearchDisplayController;
- (BOOL)shouldInteractivePop;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithEmotionScene:(unsigned long)arg1 AndParentViewController:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

