//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMResourceReport : NSObject
{
}

+ (id)getNetworkType;
+ (void)ReportWithId:(unsigned long)arg1 key:(unsigned long)arg2 type:(unsigned long)arg3 subType:(unsigned long)arg4 version:(unsigned long)arg5 network:(id)arg6;

@end

