//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface MMScrollActionSheetItem : NSObject
{
    BOOL _disable;
    UIImage *_iconImg;
    NSString *_title;
    id _userInfo;
    float _alpha;
}

@property(nonatomic) float alpha; // @synthesize alpha=_alpha;
@property(nonatomic) BOOL disable; // @synthesize disable=_disable;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImage *iconImg; // @synthesize iconImg=_iconImg;
- (void).cxx_destruct;
- (id)init;

@end

