//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPickerView.h"

#import "MMActionSheetCustomPickerPotocol.h"
#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSDate, NSMutableArray, NSString;

@interface MMScheduleDatePickerView : UIPickerView <UIPickerViewDelegate, UIPickerViewDataSource, MMActionSheetCustomPickerPotocol>
{
    NSDate *_currentDate;
    id _scheduleDelegate;
    NSMutableArray *_dayComponents;
    NSMutableArray *_timeComponents;
    NSMutableArray *_normalTimeComponents;
    NSMutableArray *_todayTimeComponents;
    int _lastSelectDay;
}

@property(nonatomic) int lastSelectDay; // @synthesize lastSelectDay=_lastSelectDay;
@property(retain, nonatomic) NSMutableArray *todayTimeComponents; // @synthesize todayTimeComponents=_todayTimeComponents;
@property(retain, nonatomic) NSMutableArray *normalTimeComponents; // @synthesize normalTimeComponents=_normalTimeComponents;
@property(retain, nonatomic) NSMutableArray *timeComponents; // @synthesize timeComponents=_timeComponents;
@property(retain, nonatomic) NSMutableArray *dayComponents; // @synthesize dayComponents=_dayComponents;
@property(nonatomic) __weak id scheduleDelegate; // @synthesize scheduleDelegate=_scheduleDelegate;
@property(retain, nonatomic) NSDate *currentDate; // @synthesize currentDate=_currentDate;
- (void).cxx_destruct;
- (id)selectedDate;
- (void)pickerView:(id)arg1 didSelectRow:(int)arg2 inComponent:(int)arg3;
- (id)pickerView:(id)arg1 viewForRow:(int)arg2 forComponent:(int)arg3 reusingView:(id)arg4;
- (id)titleForRow:(int)arg1 forComponent:(int)arg2;
- (float)pickerView:(id)arg1 rowHeightForComponent:(int)arg2;
- (float)pickerView:(id)arg1 widthForComponent:(int)arg2;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (int)daysInThisMonth;
- (id)getDayString:(id)arg1 AfterMonth:(unsigned long)arg2 inDay:(unsigned long)arg3;
- (id)getDayStringAfterDay:(unsigned long)arg1;
- (void)initData;
- (void)didAddSubview:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

