//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "EmoticonCustomManageAddLogicDelegate.h"
#import "EmotionCollectionFooterViewDelegate.h"
#import "EmotionDesignerEmojiTipsViewControllerDelegate.h"
#import "MMStoreEmotionTagSelectDelegate.h"
#import "StoreEmotionGetDesignerEmojiListCgiDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class EmojiInfo, EmojiTag, EmoticonCustomManageAddLogic, EmoticonStoreReportInfo, EmotionBannerSet, EmotionCollectionFooterView, NSArray, NSString, StoreEmotionGetDesignerEmojiListCgi, StoreEmotionPageShareLogic, UICollectionView;

@interface MMStoreEmotionDesignerEmojiViewController : MMUIViewController <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, EmotionCollectionFooterViewDelegate, StoreEmotionGetDesignerEmojiListCgiDelegate, EmotionDesignerEmojiTipsViewControllerDelegate, EmoticonCustomManageAddLogicDelegate, MMStoreEmotionTagSelectDelegate>
{
    long m_numOfItemInOneLine;
    UICollectionView *m_collectionView;
    EmotionCollectionFooterView *m_collectionFooterView;
    StoreEmotionGetDesignerEmojiListCgi *m_getAllDesignerEmojisCgi;
    StoreEmotionGetDesignerEmojiListCgi *m_curGetDesignerEmojisCgi;
    NSArray *m_tagsList;
    EmojiTag *m_lastSelectedTag;
    unsigned long m_designerUin;
    NSString *m_keyword;
    unsigned long long m_searchId;
    EmotionBannerSet *m_bannerSet;
    unsigned int m_designerEmojiMode;
    EmojiInfo *m_operatingEmoji;
    EmoticonCustomManageAddLogic *m_emoticonAddLogic;
    StoreEmotionPageShareLogic *m_shareLogic;
    EmoticonStoreReportInfo *_reportInfo;
}

+ (BOOL)canShowDesignerEmoji;
@property(retain, nonatomic) EmoticonStoreReportInfo *reportInfo; // @synthesize reportInfo=_reportInfo;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(int)arg3;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)MMRefreshCollectionFooterDidTriggerRefresh:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)AddEmoticonFinishedWithWrap:(id)arg1 IsSuccessed:(BOOL)arg2;
- (void)onSendDesignerEmojiWithMd5:(id)arg1;
- (void)onSaveDesignerEmojiWithMd5:(id)arg1;
- (void)switchToGetDesignerEmojiListCgi:(id)arg1;
- (void)onSelectTag:(id)arg1;
- (void)onSelectShowAllTag;
- (void)onCancelTagSelect;
- (void)onGetDesignerEmojiListFailedWithBannerSetId:(unsigned int)arg1;
- (void)onGetDesignerEmojiListFailedWithTagId:(unsigned int)arg1;
- (void)onGetDesignerEmojiListFailedWithKeyword:(id)arg1;
- (void)onGetDesignerEmojiListFailedWithDesignerUin:(unsigned long)arg1;
- (void)onGetDesignerEmojiListFailed;
- (void)onGetDesignerEmojiListSuccessedWithBannerSetId:(unsigned int)arg1 DesignerEmojiList:(id)arg2 hasMore:(BOOL)arg3;
- (void)onGetDesignerEmojiListSuccessedWithTagId:(unsigned int)arg1 DesignerEmojiList:(id)arg2 hasMore:(BOOL)arg3;
- (void)onGetDesignerEmojiListSuccessedWithKeyword:(id)arg1 Tags:(id)arg2 DesignerEmojiList:(id)arg3 hasMore:(BOOL)arg4;
- (void)onGetDesignerEmojiListSuccessedWithDesignerUin:(unsigned long)arg1 Tags:(id)arg2 DesignerEmojiList:(id)arg3 hasMore:(BOOL)arg4;
- (void)onGetDesignerEmojiListSuccessedWithTags:(id)arg1 DesignerEmojiList:(id)arg2 hasMore:(BOOL)arg3;
- (void)onClickTagIcon;
- (void)onOperate:(id)arg1;
- (void)onClose;
- (BOOL)isInSearchMode;
- (BOOL)isInTagMode;
- (void)configShareEntrance;
- (void)configTagsEntrance;
- (void)updateCollectionLayout:(id)arg1;
- (void)configCollectionView;
- (void)initView;
- (void)viewDidTransitionToNewSize;
- (void)viewDidLoad;
- (id)initWithBannerSet:(id)arg1;
- (id)initWithEmojiTag:(id)arg1;
- (id)initWithDesignerUin:(unsigned long)arg1;
- (id)initWithKeyword:(id)arg1 searchId:(unsigned long long)arg2;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

