//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBaseContactInfoAssist.h"

#import "BrandProfileFooterViewDelegate.h"
#import "BrandProfileHeaderViewDelegate.h"
#import "BrandProfileSettingViewControllerDelegate.h"
#import "IBrandAttrMgrExt.h"
#import "IHDHeadImageViewExt.h"
#import "IWCDeviceBrandMgrExt.h"
#import "UIActionSheetDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class BrandProfileCacheItem, BrandProfileFooterView, BrandProfileFuwu, BrandProfileHeaderView, BrandProfileReporter, MMHDHeadImageView, MMTableView, NSMutableArray, NSString, WCADPageWrap, WOAPPrivacyConfirmLogic;

@interface NewBrandUserContactInfoAssist : CBaseContactInfoAssist <UITableViewDataSource, UITableViewDelegate, UIActionSheetDelegate, IBrandAttrMgrExt, BrandProfileHeaderViewDelegate, BrandProfileFooterViewDelegate, BrandProfileSettingViewControllerDelegate, IHDHeadImageViewExt, IWCDeviceBrandMgrExt>
{
    BOOL _isJustAddedContact;
    BOOL _isFetching;
    BrandProfileCacheItem *_cacheItem;
    BrandProfileReporter *_reporter;
    NSMutableArray *_weappInfoList;
    NSMutableArray *_weappIconList;
    BrandProfileFuwu *_selectedFuwu;
    unsigned int _selectedFuwuIdx;
    MMTableView *_tableView;
    BrandProfileHeaderView *_headerView;
    BrandProfileFooterView *_footerView;
    MMHDHeadImageView *_hdAvatarView;
    WCADPageWrap *_profilePageWrap;
    WOAPPrivacyConfirmLogic *_privacyConfirmLogic;
    NSString *_searchKeyword;
    unsigned long _searchFromIndex;
    NSString *_searchExtraParamsString;
}

@property(retain, nonatomic) NSString *searchExtraParamsString; // @synthesize searchExtraParamsString=_searchExtraParamsString;
@property(nonatomic) unsigned long searchFromIndex; // @synthesize searchFromIndex=_searchFromIndex;
@property(retain, nonatomic) NSString *searchKeyword; // @synthesize searchKeyword=_searchKeyword;
- (void).cxx_destruct;
- (unsigned long)transToReportScene;
- (void)profileDestory;
- (void)recordProfilePageWrap;
- (void)deleteAllMessage;
- (BOOL)isInCustomAlertMode;
- (float)getTextFieldTopMarginVerifyLogic:(id)arg1;
- (id)getAlertMessageForVerifyLogic:(id)arg1;
- (id)getAlertTitleForVerifyLogic:(id)arg1;
- (void)newMessageWithContact:(id)arg1 afterDelay:(double)arg2;
- (void)handleAddedContact;
- (void)contactAddContactOk:(id)arg1;
- (void)onWebUrlClicked:(id)arg1;
- (void)onWCDeviceUnbindEnd:(id)arg1 Error:(id)arg2;
- (void)onWCDeviceBindEnd:(id)arg1 Error:(id)arg2;
- (BOOL)isDeviceBound;
- (BOOL)hasDeviceUserData;
- (void)onUnfocusButtonClicked:(id)arg1;
- (void)onEnterButtonClicked:(id)arg1;
- (void)finallyAddToContacts;
- (void)onFocusButtonClicked:(id)arg1;
- (void)onBrandAvatarClicked:(struct CGRect)arg1;
- (void)realNoFocus;
- (void)showActionSheetForNoFocus;
- (void)openSettingView;
- (void)openSepcialWeappWithUserName:(id)arg1 fromScene:(unsigned int)arg2;
- (void)openSepcialWeappWithJsonString:(id)arg1;
- (void)openMaterialView;
- (void)opLogTopSession:(BOOL)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)showActionSheetForRightButton;
- (void)updateNavigationBarRightButton;
- (void)reloadTableView;
- (void)onFetchBizProfile:(id)arg1 respInfoList:(id)arg2;
- (BOOL)hasLoadingView;
- (BOOL)hasWeappList;
- (void)filterWeappList;
- (void)fetchArticleList;
- (void)openWeappListView;
- (void)openWebView:(id)arg1;
- (void)showActionSheetForSubFuwuList:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)createWeappListCell;
- (id)createFuwuInfoCell:(id)arg1;
- (id)createArticleCountCell;
- (id)createTextInfoCell:(id)arg1;
- (id)createArticleInfoCell:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onContactUpdated;
- (void)reloadView;
- (void)initFooterView;
- (void)initHeaderView;
- (id)GetTableView;
- (void)initTableView;
- (id)initWithContact:(id)arg1 delegate:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

