//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBaseContactInfoAssist.h"

#import "IAutoSetRemarkExt.h"
#import "IAutoSetStrangerAttributeExt.h"
#import "IHDHeadImageViewExt.h"
#import "ILinkEventExt.h"
#import "IOpenImResourceMgrExt.h"
#import "MMCPLabelDelegate.h"
#import "RichTextLayoutDelegate.h"
#import "SendVerifyMsgViewControllerDelegate.h"

@class CContact, ContactRelatedGroupLogic, MMTableViewInfo, MMURLHandler, NSString, SendVerifyMsgLogicController;

@interface OpenIMContactInfoAssist : CBaseContactInfoAssist <MMCPLabelDelegate, IAutoSetRemarkExt, IAutoSetStrangerAttributeExt, SendVerifyMsgViewControllerDelegate, ILinkEventExt, RichTextLayoutDelegate, IHDHeadImageViewExt, IOpenImResourceMgrExt>
{
    BOOL m_bFirstBecomeFriend;
    MMTableViewInfo *m_tableViewInfo;
    CContact *m_chatContact;
    unsigned long m_uiVerify;
    NSString *m_cpKeyForNickname;
    NSString *m_cpKeyForChatRoomDisplayName;
    NSString *m_cpKeyForSignature;
    BOOL m_isNickNameUnsafe;
    BOOL m_isChatRoomDisplayNameUnsafe;
    BOOL m_isSignatureUnsafe;
    SendVerifyMsgLogicController *m_sendVerifylogicVC;
    ContactRelatedGroupLogic *m_relatedGroupLogic;
    NSString *m_InviteUserName;
    MMURLHandler *m_urlHandler;
    BOOL _m_bDisableAllOperation;
}

@property(nonatomic) BOOL m_bDisableAllOperation; // @synthesize m_bDisableAllOperation=_m_bDisableAllOperation;
- (void).cxx_destruct;
- (void)reportContactInfoComeWithReportScene:(int)arg1;
- (void)reportContactInfoItemClickWithCellInfo:(id)arg1;
- (void)reportContactInfoViewEnter;
- (void)onRestoreCPLabel:(id)arg1;
- (void)updateCPState;
- (id)init;
- (void)contactSendReplyOk:(id)arg1;
- (void)contactSendRequestOk:(id)arg1;
- (void)contactAddContactOk:(id)arg1;
- (void)handleAddedContact;
- (void)onVerifyContactOk;
- (void)onRelpyContact:(id)arg1;
- (void)onVerifyContact:(id)arg1 opcode:(unsigned long)arg2;
- (void)doAddContact;
- (void)onOpenIMNormalClicked:(id)arg1;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onStartChat:(id)arg1;
- (void)onNewMessage:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)doDeleteContact;
- (void)onAction;
- (void)opBlackList:(id)arg1;
- (void)onOpenVoiceVoipView;
- (void)onOpenVoipView;
- (void)onExposeByRecommand;
- (void)doAddToBlackList;
- (void)addToBlackList:(id)arg1;
- (void)removeFromBlackList;
- (void)showRightButton;
- (void)initFooterView;
- (void)initPrivacyTipsLabel;
- (void)initQuitRoomTipsLabel;
- (void)initBlackListTipsLabel;
- (void)initFooterBtnArea;
- (void)updateToBigSendMsgBtn;
- (void)initBlackAndExposeContactBtn;
- (void)initExposeBtn;
- (void)initAddContactBtn;
- (void)initVerifyBtn;
- (void)initSayHelloBtn;
- (void)onSayHelloToContact;
- (void)onOpenVoipActionSheet:(id)arg1;
- (BOOL)initVoipBtn;
- (void)initSendMsgBtn;
- (void)initDeleteBtn;
- (void)reloadTableView;
- (BOOL)checkISNeedShowIMSource;
- (id)makeOpenIMSourceSection;
- (id)makeOpenIMIntroSection;
- (id)makeOpenIMInfoSection;
- (void)initData;
- (void)makeEditRemarkNameCell:(id)arg1 CellInfo:(id)arg2;
- (BOOL)shouldOpenNewLineAtY:(float)arg1 withLineHeight:(float)arg2 richTextView:(id)arg3;
- (void)makeSourceCell:(id)arg1 CellInfo:(id)arg2;
- (void)makePhoneCell:(id)arg1 CellInfo:(id)arg2 title:(id)arg3 phoneList:(id)arg4 autoresizingMask:(unsigned int)arg5;
- (void)makePhoneCell:(id)arg1 CellInfo:(id)arg2;
- (void)makeMoreCell:(id)arg1 CellInfo:(id)arg2;
- (void)makeOpenIMSeparator:(id)arg1 CellInfo:(id)arg2;
- (void)makeOpenIMPhoneCell:(id)arg1 CellInfo:(id)arg2;
- (void)makeOpenIMNormalCell:(id)arg1 CellInfo:(id)arg2;
- (void)makeLeftValueCell:(id)arg1 CellInfo:(id)arg2;
- (void)makeCellTitle:(id)arg1 Title:(id)arg2 MaxWidth:(float)arg3 AutoresizingMask:(unsigned int)arg4;
- (void)makeCellTitle:(id)arg1 Title:(id)arg2 MaxWidth:(float)arg3;
- (void)makeHeadCell:(id)arg1 CellInfo:(id)arg2;
- (id)makeHeadSmallLabel:(id)arg1 Y:(float)arg2 text:(id)arg3 cpKey:(id)arg4 inUnsafe:(BOOL)arg5 withPrefixTitle:(id)arg6;
- (id)makeHeadSmallLabel:(id)arg1 Y:(float)arg2 text:(id)arg3 cpKey:(id)arg4 inUnsafe:(BOOL)arg5;
- (void)opEditRemarkName;
- (void)tryHandleLink:(id)arg1;
- (void)tryCall:(id)arg1;
- (void)onSocialInfoHandle;
- (void)updateFooterView;
- (BOOL)isShowAddFriendScene;
- (BOOL)isFromQRCode;
- (id)getInfoDisplayName;
- (BOOL)isNeedVerify;
- (BOOL)isShowExposeButton;
- (BOOL)isShowBlackAction;
- (BOOL)isNeedShowRightBtn;
- (void)initTableView;
- (id)GetTableView;
- (BOOL)isFromStrangeScene;
- (void)dealloc;
- (void)loadLocalContactData;
- (void)onHDHeadImageDidDisappear;
- (void)onHDHeadImageWillAppear;
- (void)onGetOpenImResourceDone:(id)arg1;
- (id)initWithContact:(id)arg1 andVerify:(unsigned long)arg2 delegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

