//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "PBCoding.h"

@class NSString;

@interface PhoneItemInfo : NSObject <PBCoding, NSCoding>
{
    NSString *phoneNum;
    BOOL bFromHash;
    int index;
}

+ (void)initialize;
@property(nonatomic) int index; // @synthesize index;
@property(nonatomic) BOOL bFromHash; // @synthesize bFromHash;
@property(retain, nonatomic) NSString *phoneNum; // @synthesize phoneNum;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (const map_69681069 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

