//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IRsaCertMgrExt.h"
#import "PBMessageObserverDelegate.h"

@class NSString, ProtobufCGIWrap;

@interface RsaCGIWrapLogic : NSObject <PBMessageObserverDelegate, IRsaCertMgrExt>
{
    unsigned long m_cert_error_count;
    ProtobufCGIWrap *m_pbCGIWrap;
    unsigned long m_uiFlag;
    unsigned long m_uiEventID;
}

@property(nonatomic) unsigned long m_uiEventID; // @synthesize m_uiEventID;
@property(nonatomic) unsigned long m_uiFlag; // @synthesize m_uiFlag;
@property(retain, nonatomic) ProtobufCGIWrap *m_pbCGIWrap; // @synthesize m_pbCGIWrap;
- (void).cxx_destruct;
- (void)dealloc;
- (void)OnRsaCertFail;
- (void)OnRsaCertCGIAgain;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)stopLogic;
- (void)startLogicAgain;
- (BOOL)startLogic;
- (id)getKey;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

