//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class MMTableView, NSString, ScanHistoryLogicHelper;

@interface ScanHistoryViewController : MMUIViewController <WCActionSheetDelegate, UITableViewDelegate, UITableViewDataSource>
{
    MMTableView *_tableView;
    ScanHistoryLogicHelper *_helperLogic;
}

- (void).cxx_destruct;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)realCleanAll;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)onCleanAction:(id)arg1;
- (void)showEmptyView;
- (void)OnReturn;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

