//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView;

@protocol SelectAttachmentViewDataSource <NSObject>

@optional
- (NSString *)appIDAtIndex:(unsigned long)arg1;
- (NSString *)descriptionForAttachmentAtIndex:(unsigned long)arg1;
- (UIView *)viewForAttachmentAtIndex:(unsigned long)arg1;
- (unsigned int)numberOfCols;
- (unsigned int)numberOfRows;
- (unsigned int)numberOfAttachment;
@end

