//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "contactVerifyLogicDelegate.h"

@class CContact, CContactVerifyLogic, CMessageWrap, MMUIViewController, NSString, SendVerifyMsgViewController;

@interface SendVerifyMsgLogicController : NSObject <contactVerifyLogicDelegate>
{
    MMUIViewController *m_parentVC;
    BOOL canOnCancel;
    SendVerifyMsgViewController *m_vc;
    CContactVerifyLogic *m_oContactVerifyLogic;
    BOOL _m_bVerifyToMe;
    BOOL _m_needAnimationPopAfterOK;
    CContact *_m_oVerifyContact;
    id <SendVerifyMsgViewControllerDelegate> _m_delegate;
    CContact *_m_oChatContact;
    CMessageWrap *_m_oSourceMsg;
    int _m_qrCodeAddFriendScene;
}

@property(nonatomic) BOOL m_needAnimationPopAfterOK; // @synthesize m_needAnimationPopAfterOK=_m_needAnimationPopAfterOK;
@property(nonatomic) int m_qrCodeAddFriendScene; // @synthesize m_qrCodeAddFriendScene=_m_qrCodeAddFriendScene;
@property(retain, nonatomic) CMessageWrap *m_oSourceMsg; // @synthesize m_oSourceMsg=_m_oSourceMsg;
@property(retain, nonatomic) CContact *m_oChatContact; // @synthesize m_oChatContact=_m_oChatContact;
@property(nonatomic) BOOL m_bVerifyToMe; // @synthesize m_bVerifyToMe=_m_bVerifyToMe;
@property(nonatomic) __weak id <SendVerifyMsgViewControllerDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
@property(retain, nonatomic) CContact *m_oVerifyContact; // @synthesize m_oVerifyContact=_m_oVerifyContact;
- (void).cxx_destruct;
- (void)contactAddContactOk:(id)arg1;
- (void)contactSendRequestOk:(id)arg1;
- (void)onContactVerifyFail;
- (void)onDismiss;
- (void)onCancel;
- (void)startLogic;
- (id)initWithParentVC:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

