//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IContactMgrExt.h"
#import "IMMNewSessionMgrExt.h"
#import "IMsgExt.h"
#import "MMService.h"

@class Log_IMOperation, NSMutableArray, NSString, WCStatTimerHelper;

@interface SessionActionStatMgr : MMService <IContactMgrExt, IMMNewSessionMgrExt, IMsgExt, MMService>
{
    NSMutableArray *_actionList;
    BOOL _bDidEnterChatRoom;
    unsigned long _uiStayWebViewTime;
    WCStatTimerHelper *_oStatTimerHelper;
    struct map<unsigned long, NSMutableDictionary *, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, NSMutableDictionary *>>> _mapExpourseTypeToDic;
    Log_IMOperation *_Log_IMOperation;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)OnAddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnChangeNotifyStatus:(id)arg1 withStatus:(BOOL)arg2;
- (void)onSessionTopStatusChanged:(id)arg1 bTop:(BOOL)arg2;
- (void)reportLogIMOperation:(id)arg1;
- (id)strAppendKeyValue:(id)arg1 key:(id)arg2 value:(id)arg3;
- (void)addIMBehaviorContactOp:(id)arg1 contactOpType:(int)arg2;
- (void)addIMBehaviorContactExpose:(id)arg1 scene:(unsigned int)arg2;
- (void)reportMsgOperation:(id)arg1;
- (void)addIMBehaviorMsgOp:(unsigned long)arg1 appMsgInnerType:(unsigned long)arg2 msgOpType:(int)arg3;
- (void)startRecordIMOperation;
- (void)initIMOperation;
- (BOOL)needUploadIMOperationPB;
- (BOOL)needUploadIMOperationKV;
- (void)logAppMessageExpourse:(id)arg1;
- (BOOL)isMessageWrapInExp:(id)arg1;
- (void)logExpMessageClick:(id)arg1 mediaState:(int)arg2;
- (void)logExpMessageExpourse:(id)arg1 mediaState:(int)arg2;
- (void)uploadActionList;
- (void)tryUploadActionList;
- (void)exitChatRoom:(id)arg1 beginTime:(unsigned long)arg2 unreadCount:(unsigned long)arg3;
- (void)recordStayWebViewTimeInMS:(unsigned long long)arg1;
- (void)enterChatRoom;
- (id)getPosterUserNameWithMsgWrap:(id)arg1;
- (id)getFromChatRoomWithMsgWrap:(id)arg1;
- (void)clearExposureMsgIdDic;
- (void)markExposuredWithMessageId:(unsigned long long)arg1 expourseType:(unsigned int)arg2;
- (BOOL)hadExposuredWithMessageId:(unsigned long long)arg1 expourseType:(unsigned int)arg2;
- (int)getSessionTypeWithContact:(id)arg1;
- (unsigned long)getMaxCacheLogCount;
- (unsigned long)getMaxCacheTime;
- (BOOL)saveSessionActionCache;
- (BOOL)tryLoadSessionActionCache;
- (void)dealloc;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (id)pathForSessionActionCache;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

