//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ShakeMgrExt.h"

@class ShakeBeaconLogicController, ShakeMusicLogicController, ShakePeopleLogicController, ShakeTvLogicController;

@interface ShakeLogicProxy : MMObject <ShakeMgrExt>
{
    int m_logicType;
    id <ShakeLogicProxyDelegate> m_delegate;
    ShakePeopleLogicController *m_shakePeopleLogic;
    ShakeMusicLogicController *m_shakeMusicLogic;
    ShakeBeaconLogicController *m_shakeBeaconLogic;
    ShakeTvLogicController *m_shakeTvLogic;
}

- (void).cxx_destruct;
- (void)SetShakeList:(id)arg1 andScene:(unsigned long)arg2;
- (void)updateShakeLocation;
- (id)getMsgForState:(unsigned long)arg1;
- (BOOL)isShowBannerView;
- (void)shakeTerminate;
- (void)shakeReset;
- (void)shakeStop;
- (BOOL)shakeReport;
- (int)getShakeLogicType;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;
- (void)onShakeMusicStorageChanged;
- (void)OnShakeShareCountChanged;
- (void)onShakePageStorageChanged;
- (void)onShakeStatusChanged;
- (void)onShakePeopleStorageChanged;
- (int)GetLogicTypeFromStatus;

@end

