//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "ShakeMsgNotifyMgrDelegate.h"

@class NSString, ShakeBeaconStorage, ShakeMsgNotifyMgr, ShakeMusicStorage, ShakePeopleStorage, ShakeTvStorage;

@interface ShakeMgr : MMService <ShakeMsgNotifyMgrDelegate, MMService>
{
    int m_shakeType;
    ShakePeopleStorage *m_peopleStorage;
    ShakeMusicStorage *m_musicStorage;
    ShakeTvStorage *m_tvStorage;
    ShakeBeaconStorage *m_beaconStorage;
    int m_peopleStorageRefCount;
    int m_pageStorageRefCount;
    int m_musicStorageRefCount;
    int m_tvStorageRefCount;
    int m_shakeShareStorageRefCount;
    int m_beaconStorageRefCount;
    ShakeMsgNotifyMgr *m_shakeMsgNotifyMgr;
}

- (void).cxx_destruct;
- (void)onShakeMsgUnreadCountChanged;
- (void)insertMsgItem:(id)arg1;
- (void)deleteAllMessages;
- (void)deleteMessageItem:(id)arg1;
- (void)markMessageListRead:(id)arg1;
- (id)getMessagesFrom:(id)arg1 maxCount:(unsigned long)arg2;
- (id)getUnreadMsgPidDesc;
- (id)getLastestUnreadMessage;
- (id)getUnreadMessages;
- (unsigned int)getUnreadMessageCount;
- (BOOL)hasUnreadMessages;
- (BOOL)onServiceMemoryWarning;
- (id)getShakeBackgroundView;
- (void)endMusicStorage;
- (void)beginMusicStorage;
- (void)endPeopleStorage;
- (void)beginPeopleStorage;
- (void)endTvStorage;
- (void)beginTvStorage;
- (void)endBeaconStorage;
- (void)beginBeaconStorage;
- (void)clearBeaconStorage;
- (void)saveBeaconStorage:(BOOL)arg1;
- (id)getBeaconStorage;
- (void)LoadBeaconStorage;
- (void)ClearTvStorage;
- (void)SaveTvStorage:(BOOL)arg1;
- (id)getTvStorage;
- (void)LoadTvStorage;
- (void)ClearMusicStorage;
- (void)SaveMusicStorage:(BOOL)arg1;
- (id)getMusicStorage;
- (void)LoadMusicStorage;
- (void)ClearPeopleStorage;
- (void)SavePeopleStorage:(BOOL)arg1;
- (id)getPeopleStorage;
- (void)LoadPeopleStorage;
- (void)setSoundStatus:(int)arg1;
- (int)getSoundStatus;
- (void)NotifyStatusChanged;
- (BOOL)canShowShakeTV;
- (BOOL)isShakeMusicOversea;
- (BOOL)canShowShakeMusic;
- (int)getShakeType;
- (void)shakeSwitch:(int)arg1;
- (void)dealloc;
- (id)init;
- (void)onServiceReloadData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

