//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ShareConfirmViewDelegate.h"

@class CMessageWrap, NSData, NSDictionary, NSString, ShareConfirmView;

@interface ShareMessageConfirmLogicHelper : MMObject <ShareConfirmViewDelegate>
{
    ShareConfirmView *_confirmView;
    CMessageWrap *_msgWrap;
    id <ShareMessageConfirmLogicHelperDelegate> _delegate;
    NSData *_imageData;
    NSString *_thumbImageUrl;
    unsigned long _scene;
    BOOL _isShowTextView;
    BOOL _isAddMessage;
    BOOL _isAddTextMessage;
    BOOL _isShowSendSuccessView;
    unsigned long _style;
    BOOL _hasBeenHidden;
    NSDictionary *_userData;
}

@property(retain, nonatomic) NSDictionary *userData; // @synthesize userData=_userData;
@property(nonatomic) BOOL isShowSendSuccessView; // @synthesize isShowSendSuccessView=_isShowSendSuccessView;
@property(nonatomic) BOOL isAddTextMessage; // @synthesize isAddTextMessage=_isAddTextMessage;
@property(nonatomic) BOOL isAddMessage; // @synthesize isAddMessage=_isAddMessage;
@property(retain, nonatomic) NSString *thumbImageUrl; // @synthesize thumbImageUrl=_thumbImageUrl;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(retain, nonatomic) CMessageWrap *msgWrap; // @synthesize msgWrap=_msgWrap;
@property(nonatomic) __weak id <ShareMessageConfirmLogicHelperDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)OnStayAtWeChat:(id)arg1;
- (void)OnBackToApp:(id)arg1;
- (void)OnError:(id)arg1;
- (void)OnCancel:(id)arg1;
- (void)OnSend:(id)arg1;
- (void)shareAppMessage;
- (void)rotateToOrientaion:(int)arg1;
- (void)rotateToCurrentOrietation;
- (void)hideConfirmView;
- (void)showConfirmView;
- (void)showConfirmViewWithInputText:(id)arg1;
- (void)showConfirmViewWithInputText:(id)arg1 showText:(id)arg2;
- (void)setConfirmViewStyle:(int)arg1;
- (void)dealloc;
- (id)initWithMessageWrap:(id)arg1 isShowTextView:(BOOL)arg2 andAppScene:(unsigned long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

