//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface SightCameraTopToolView : UIView
{
    BOOL _isRecording;
    int _flashMode;
    UIButton *_closeButton;
    unsigned int _toolItems;
    UIButton *_cameraSwitchButton;
    CDUnknownBlockType _switchCameraBlock;
    CDUnknownBlockType _closeButtonBlock;
}

+ (int)torchModeWithToolFlashMode:(int)arg1;
+ (int)flashModeWithToolFlashMode:(int)arg1;
@property(copy, nonatomic) CDUnknownBlockType closeButtonBlock; // @synthesize closeButtonBlock=_closeButtonBlock;
@property(copy, nonatomic) CDUnknownBlockType switchCameraBlock; // @synthesize switchCameraBlock=_switchCameraBlock;
@property(retain, nonatomic) UIButton *cameraSwitchButton; // @synthesize cameraSwitchButton=_cameraSwitchButton;
@property(nonatomic) unsigned int toolItems; // @synthesize toolItems=_toolItems;
@property(nonatomic) BOOL isRecording; // @synthesize isRecording=_isRecording;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) int flashMode; // @synthesize flashMode=_flashMode;
- (void).cxx_destruct;
- (void)switchCamera;
- (void)onCloseButtonClicked;
- (void)updateCameraAccessibility;
- (void)setupView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 toolItems:(unsigned int)arg2;
- (void)rotateToOrientation:(int)arg1;
@property(nonatomic) int orientation;

@end

