//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SimpleAudioBufferDelegate <NSObject>
- (double)simpleRateForBuffer;
- (unsigned long)channlesPerFrame;
- (unsigned long)framesPerPacket;
- (unsigned long)bitsPerChannel;
- (void)onAudioBufferPlayEnd;
- (unsigned long)fillPcmBuffer:(short *)arg1 bufferSize:(unsigned long)arg2;
@end

