//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "StoreEmotionUploadMyPanelListCgiDelegate.h"

@class NSArray, NSString, StoreEmotionUploadMyPanelListCgi;

@interface StoreEmotionBackupLogicObject : MMObject <StoreEmotionUploadMyPanelListCgiDelegate>
{
    BOOL m_hasCheckFileExist;
    BOOL _stopFileMagration;
    BOOL _m_isActive;
    BOOL _m_hasStartLogic;
    StoreEmotionUploadMyPanelListCgi *_uploadCgi;
    id <StoreEmotionBackupLogicObjectDelegate> _delegate;
    NSArray *_needUploadPids;
}

@property(nonatomic) BOOL m_hasStartLogic; // @synthesize m_hasStartLogic=_m_hasStartLogic;
@property(nonatomic) BOOL m_isActive; // @synthesize m_isActive=_m_isActive;
@property(retain, nonatomic) NSArray *needUploadPids; // @synthesize needUploadPids=_needUploadPids;
@property(nonatomic) __weak id <StoreEmotionBackupLogicObjectDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) StoreEmotionUploadMyPanelListCgi *uploadCgi; // @synthesize uploadCgi=_uploadCgi;
@property(nonatomic) BOOL stopFileMagration; // @synthesize stopFileMagration=_stopFileMagration;
@property(readonly, nonatomic) BOOL hasCheckFileExist; // @synthesize hasCheckFileExist=m_hasCheckFileExist;
- (void).cxx_destruct;
- (void)onStoreEmotionUploadMyPanelListCgiFailed;
- (void)onStoreEmotionUploadMyPanelListCgiOk;
- (id)getStoreEmotionList;
- (BOOL)checkIfNeedBackup;
- (BOOL)canStartCgiNow;
- (void)startInternalLogic;
- (BOOL)checkFileExistWithEmoticonList:(id)arg1 needCheckThumb:(BOOL)arg2;
- (void)onCheckFileExistFinished;
- (void)asyncMigrateFilesOrCheckFileExist;
- (void)backupSortedEmo:(id)arg1;
- (BOOL)isActive;
- (void)startLogicWithNeedCheckFileExist:(BOOL)arg1;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

