//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableArray;

@interface TLDSensorRecordModel : NSObject <NSCoding>
{
    int _sceneType;
    int _actionType;
    float _duration;
    float _leftDuration;
    NSMutableArray *_records;
    double _startTimestamp;
    double _lastTimestamp;
    double _nextUnitTimestamp;
}

+ (id)recordModelBySceneType:(int)arg1 actionType:(int)arg2 duration:(float)arg3;
@property(retain, nonatomic) NSMutableArray *records; // @synthesize records=_records;
@property(nonatomic) float leftDuration; // @synthesize leftDuration=_leftDuration;
@property(nonatomic) float duration; // @synthesize duration=_duration;
@property(nonatomic) double nextUnitTimestamp; // @synthesize nextUnitTimestamp=_nextUnitTimestamp;
@property(nonatomic) double lastTimestamp; // @synthesize lastTimestamp=_lastTimestamp;
@property(nonatomic) double startTimestamp; // @synthesize startTimestamp=_startTimestamp;
@property(nonatomic) int actionType; // @synthesize actionType=_actionType;
@property(nonatomic) int sceneType; // @synthesize sceneType=_sceneType;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)getRecords;
- (int)uniqueId;
- (void)stopRecord;
- (BOOL)isFinished;
- (void)addRecordByAccelerometer:(id)arg1 gyro:(id)arg2 gravity:(id)arg3 interval:(float)arg4 timestamp:(double)arg5;
- (id)init;

@end

