//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSData, NSDictionary, NSMutableArray, NSString;

@interface UrlInfo : NSObject <NSCopying>
{
    NSString *m_nsRequestUrl;
    NSData *m_dtResponseData;
    NSString *m_nsRefer;
    BOOL m_bGetMethod;
    NSData *m_dtBodyData;
    NSDictionary *m_dicReq;
    NSDictionary *m_dicResp;
    BOOL m_bCdn;
    NSString *m_nsRequestUrlSuffix;
    unsigned long m_uiRecvTime;
    unsigned long m_uiRetCode;
    unsigned long m_uiDataSize;
    unsigned long m_uiDnsCostTime;
    unsigned long m_uiConnectCostTime;
    unsigned long m_uiSendCostTime;
    unsigned long m_uiWaitResponseCostTime;
    unsigned long m_uiReceiveCostTime;
    NSString *m_nsClientIP;
    NSString *m_nsServerIP;
    unsigned long m_uiDnsType;
    NSString *m_host;
    NSString *m_nsXErrno;
    NSMutableArray *m_aryReceiveData;
    NSString *m_fileMd5;
    BOOL m_bSupportValidateMd5;
    BOOL m_bContinueReceive;
    NSString *m_filePath;
    BOOL m_useDCIP;
    BOOL m_fromSns;
    BOOL m_useXorEncrypt;
    unsigned long long m_xorEncryKey;
    unsigned int m_uiXEncIdx;
    NSString *m_nsXEnc;
    NSString *m_nsXEncToken;
    unsigned long m_uiReqestCSeq;
    unsigned long m_uiResponseCSeq;
}

@property(nonatomic) unsigned long m_uiResponseCSeq; // @synthesize m_uiResponseCSeq;
@property(nonatomic) unsigned long m_uiReqestCSeq; // @synthesize m_uiReqestCSeq;
@property(nonatomic) unsigned int m_uiXEncIdx; // @synthesize m_uiXEncIdx;
@property(retain, nonatomic) NSString *m_nsXEncToken; // @synthesize m_nsXEncToken;
@property(retain, nonatomic) NSString *m_nsXEnc; // @synthesize m_nsXEnc;
@property(nonatomic) unsigned long long m_xorEncryKey; // @synthesize m_xorEncryKey;
@property(retain, nonatomic) NSMutableArray *m_aryReceiveData; // @synthesize m_aryReceiveData;
@property(nonatomic) BOOL m_useXorEncrypt; // @synthesize m_useXorEncrypt;
@property(nonatomic) BOOL m_fromSns; // @synthesize m_fromSns;
@property(nonatomic) BOOL m_useDCIP; // @synthesize m_useDCIP;
@property(nonatomic) BOOL m_bSupportValidateMd5; // @synthesize m_bSupportValidateMd5;
@property(retain, nonatomic) NSString *m_fileMd5; // @synthesize m_fileMd5;
@property(retain, nonatomic) NSString *m_filePath; // @synthesize m_filePath;
@property(nonatomic) BOOL m_bContinueReceive; // @synthesize m_bContinueReceive;
@property(retain, nonatomic) NSString *m_nsXErrno; // @synthesize m_nsXErrno;
@property(retain, nonatomic) NSString *m_nsRequestUrlSuffix; // @synthesize m_nsRequestUrlSuffix;
@property(retain, nonatomic) NSString *m_host; // @synthesize m_host;
@property(nonatomic) unsigned long m_uiDnsType; // @synthesize m_uiDnsType;
@property(retain, nonatomic) NSString *m_nsServerIP; // @synthesize m_nsServerIP;
@property(retain, nonatomic) NSString *m_nsClientIP; // @synthesize m_nsClientIP;
@property(nonatomic) unsigned long m_uiReceiveCostTime; // @synthesize m_uiReceiveCostTime;
@property(nonatomic) unsigned long m_uiWaitResponseCostTime; // @synthesize m_uiWaitResponseCostTime;
@property(nonatomic) unsigned long m_uiSendCostTime; // @synthesize m_uiSendCostTime;
@property(nonatomic) unsigned long m_uiConnectCostTime; // @synthesize m_uiConnectCostTime;
@property(nonatomic) unsigned long m_uiDnsCostTime; // @synthesize m_uiDnsCostTime;
@property(nonatomic) unsigned long m_uiDataSize; // @synthesize m_uiDataSize;
@property(nonatomic) unsigned long m_uiRetCode; // @synthesize m_uiRetCode;
@property(nonatomic) unsigned long m_uiRecvTime; // @synthesize m_uiRecvTime;
@property(nonatomic) BOOL m_bCdn; // @synthesize m_bCdn;
@property(retain, nonatomic) NSDictionary *m_dicResp; // @synthesize m_dicResp;
@property(retain, nonatomic) NSDictionary *m_dicReq; // @synthesize m_dicReq;
@property(retain, nonatomic) NSData *m_dtBodyData; // @synthesize m_dtBodyData;
@property(nonatomic) BOOL m_bGetMethod; // @synthesize m_bGetMethod;
@property(retain, nonatomic) NSString *m_nsRefer; // @synthesize m_nsRefer;
@property(retain, nonatomic) NSData *m_dtResponseData; // @synthesize m_dtResponseData;
@property(retain, nonatomic) NSString *m_nsRequestUrl; // @synthesize m_nsRequestUrl;
- (void).cxx_destruct;
- (id)GenStatStringWithDataType:(int)arg1;
- (id)GenStatString;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

