//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSMutableDictionary, NSString;

@interface VoiceReminderMgr : MMService <MMService, PBMessageObserverDelegate, IMsgExt>
{
    NSMutableDictionary *_dicRemindId;
}

- (void).cxx_destruct;
- (void)OnAddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)deleteRemindMsgs:(id)arg1;
- (void)dealloc;
- (id)init;
- (BOOL)shouldNotifyRemindMsg:(id)arg1;
- (void)doRemindMsgsOp:(unsigned long)arg1 arrRemindId:(id)arg2;
- (void)onRemindMsgsOpReturn:(id)arg1 Event:(unsigned long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

