//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VoiceDetectResult : NSObject
{
    BOOL isSilient_;
    BOOL isNoisy_;
    BOOL isToLoudly_;
}

@property(nonatomic) BOOL isToLoudly; // @synthesize isToLoudly=isToLoudly_;
@property(nonatomic) BOOL isNoisy; // @synthesize isNoisy=isNoisy_;
@property(nonatomic) BOOL isSilient; // @synthesize isSilient=isSilient_;
- (id)init;

@end

