//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class WAAppStateChangedContextInfo, WAAppTask;

@interface WAAppTaskRunningStateEnterBackgroundContext : MMObject
{
    WAAppTask *_task;
    unsigned int _reason;
    WAAppStateChangedContextInfo *_contextInfo;
}

@property(retain, nonatomic) WAAppStateChangedContextInfo *contextInfo; // @synthesize contextInfo=_contextInfo;
@property(nonatomic) unsigned int reason; // @synthesize reason=_reason;
@property(nonatomic) __weak WAAppTask *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (id)description;
- (BOOL)isForbidTriggerSuspendTimer;
- (void)backgroundReceiveBackgroundCheck;
- (void)backgroundInteruptUniqueSource:(unsigned int)arg1;

@end

