//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonMessageViewModel.h"

@interface WAAppMessageBaseViewModel : CommonMessageViewModel
{
}

+ (BOOL)canCreateMessageViewModelWithMessageWrap:(id)arg1;
- (id)additionalAccessibilityDescription;
- (id)sourceTag;
- (id)sourceIcon;
- (id)sourceTitle;
- (BOOL)isShowSourceView;
- (id)appIconUrl;
- (id)desc;
- (id)title;
- (unsigned int)getWAAppState;
- (unsigned long)getWAAppVersion;
- (unsigned long)getWAAppServiceType;
- (unsigned long)getWAAppType;
- (id)getWAAppPath;
- (id)getWAAppID;
- (id)getWAAppName;
- (id)getWAAppUsername;
- (id)getWAAppContact;

@end

