//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMKernelExt.h"
#import "MMService.h"
#import "MMTipsViewControllerDelegate.h"
#import "WAAppOperateLogicDelegate.h"

@class NSString, WAAppOperateLogic;

@interface WAAppItemManager : MMService <WAAppOperateLogicDelegate, MMKernelExt, MMTipsViewControllerDelegate, MMService>
{
    WAAppOperateLogic *m_operateLogic;
    unsigned long m_localUpdateTimeOfLastVisibleItem;
    unsigned long m_updateTimeOfFirstVisibleItem;
    unsigned long m_remoteUpdateTimeOfLastVisibleItem;
    unsigned long m_biggestUpdateTimeOfStarItem;
    unsigned long m_showOutErrTime;
}

+ (unsigned int)getAppUserStateByUsername:(id)arg1;
+ (unsigned int)getAppUserStateByUsername:(id)arg1 appType:(unsigned long)arg2;
- (void).cxx_destruct;
- (void)saveShowOutInfoToLocal:(id)arg1;
- (id)getShowOutInfoFromLocal;
- (id)fetchLocalShowOutData;
- (void)onGetShowOutDataFromSvr:(id)arg1 errCode:(int)arg2;
- (void)getShowOutItemsFromSvrInScene:(unsigned long)arg1;
- (void)onClickTipsBtn:(id)arg1 Index:(int)arg2 withText:(id)arg3 withTipsVC:(id)arg4;
- (void)showUserGuideWithSessionId:(id)arg1;
- (void)clearState;
- (id)getCurrentAppStarItemsInLimits:(unsigned long)arg1;
- (void)handleUnStarOperation:(id)arg1 errCode:(int)arg2;
- (void)handleStarOperation:(id)arg1 errCode:(int)arg2;
- (void)onOprationExcuted:(id)arg1 errCode:(int)arg2;
- (void)unStarWeAppItem:(id)arg1 needPinToHistoryTop:(BOOL)arg2;
- (void)starWeAppItem:(id)arg1;
- (id)getAllAppStarItems;
- (BOOL)isItemStared:(id)arg1;
- (void)onDeleteWeAppItemSilently:(id)arg1;
- (void)onDeleteWeAppItemByUsername:(id)arg1 debugType:(unsigned long)arg2;
- (void)onDeleteWeAppItem:(id)arg1;
- (void)onOpenWeAppItem:(id)arg1 scene:(unsigned int)arg2 sessionId:(id)arg3 isAlreadyRunning:(BOOL)arg4 isUpdateMainFrameTask:(BOOL)arg5;
- (id)getLatestAppListItemWithMaxUpdateTime:(unsigned long)arg1 minUpdateTime:(unsigned long)arg2 includeStar:(BOOL)arg3;
- (id)getLatestAppListItemWithMaxUpdateTime:(unsigned long)arg1 minUpdateTime:(unsigned long)arg2;
- (id)getLatestAppListItemOverUpdateTime:(unsigned long)arg1 includeStar:(BOOL)arg2;
- (id)getLatestAppListItemOverUpdateTime:(unsigned long)arg1;
- (void)updateFirstVisibleItemUpdateTimeIfNeededWithListItems:(id)arg1;
- (id)getLatestAppListItemWithCount:(unsigned long)arg1 includeStar:(BOOL)arg2;
- (id)getLatestAppListItemWithCount:(unsigned long)arg1;
- (id)getAllAppListItemByUsername:(id)arg1;
- (id)getAllAppListItemsIsIncludeStar:(BOOL)arg1;
- (id)getAllAppListItems;
- (id)getAllAppContactListItemsWithAppType:(unsigned long)arg1;
- (id)getAllGameAppContactListItems;
- (id)getAllNormalAppContactListItems;
- (id)getAllAppContactListItems;
- (id)preCheckStarAppList:(id)arg1;
- (id)preCheckAppList:(id)arg1;
- (void)onGetLastestAppItemsFromSvrByRecordList:(id)arg1 scene:(unsigned long)arg2 hasMore:(BOOL)arg3 errCode:(int)arg4;
- (void)onGetLastestAppItemsFromSvrByStarList:(id)arg1 scene:(unsigned long)arg2 errCode:(int)arg3;
- (void)onAuthOK;
- (void)onServiceReloadData;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)getStarAppItemsFromSvrInScene:(unsigned long)arg1;
- (void)getLastestUsageAppItemsFromSvrInScene:(unsigned long)arg1;
- (void)getLastestUsageRecordInfoByUpdateTime:(unsigned long)arg1;
- (unsigned long)getValidStarBiggestUpdateTime;
- (unsigned long)getValidListTopUpdateTime;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

