//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WAAppBrandUpdateWxaUsageListDeleteAppInfo : NSObject
{
    NSString *_username;
    NSString *_appId;
    unsigned long _appType;
}

@property(nonatomic) unsigned long appType; // @synthesize appType=_appType;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
- (void).cxx_destruct;

@end

