//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@protocol WAAudioSource <NSObject>
@property(nonatomic) __weak id <WAAudioSourceDelegate> delegate;
@property(nonatomic) BOOL loop;
@property(nonatomic) float currentTime;
@property(nonatomic) float duration;
@property(nonatomic) int state;
@property(copy, nonatomic) NSString *src;
@property(copy, nonatomic) NSString *audioId;
- (BOOL)isPaused;
- (BOOL)isPlaying;
- (void)setPlaybackRate:(float)arg1;
- (void)setVolume:(float)arg1;
- (void)setLooping:(BOOL)arg1;
- (void)seek:(double)arg1;
- (void)stop;
- (void)forcePause;
- (void)pause;
- (void)play;
- (id)initWithAudioId:(NSString *)arg1 src:(NSString *)arg2 fileData:(NSData *)arg3;
@end

