//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "MMTipsViewControllerDelegate.h"

@class NSString, WAContactGetter;

@interface WAJSEventHandler_updateApp : WAJSEventHandler_BaseEvent <MMTipsViewControllerDelegate>
{
    WAContactGetter *_contactGetter;
    unsigned long _latestVersion;
}

@property(nonatomic) unsigned long latestVersion; // @synthesize latestVersion=_latestVersion;
- (void).cxx_destruct;
- (void)endWithSuccess:(BOOL)arg1 error:(id)arg2;
- (void)markUpdateAppRunning:(BOOL)arg1;
- (BOOL)isUpdateAppRunning;
- (void)handleJSEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

