//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@protocol WAJSCoreServiceRemoteDelegate <NSObject>
- (void)remoteNetworkRequest:(NSString *)arg1 taskID:(NSString *)arg2 header:(NSDictionary *)arg3;
- (void)remoteDomEvent:(NSString *)arg1 webViewID:(unsigned long)arg2;
- (void)remoteCallInterfaceResult:(NSString *)arg1 callID:(unsigned long)arg2;
- (void)remoteSetupContextWithConfigureJS:(NSString *)arg1 publibVersion:(unsigned long)arg2 publibMD5:(NSString *)arg3 threeJSMD5:(NSString *)arg4 completionHandler:(void (^)(void))arg5;
- (void)remoteEvaluateJavascript:(NSString *)arg1;
- (void)endDebug;
- (void)alterEndReason:(NSString *)arg1;
- (void)beginDebugWithRoomID:(NSString *)arg1 pkgInfo:(NSString *)arg2 channelType:(unsigned long)arg3 proxyPort:(unsigned long)arg4 supportCompressAlgo:(unsigned long)arg5;
@end

