//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class MMUIViewController, NSString, UICollectionView, UIView, WAPopOverTaskBarlogic;

@interface WAPopOverTaskBarView : MMUIView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    BOOL _isNeedBackToChatButton;
    id <WAPopOverTaskBarViewDelegate> _taskBarViewDelegate;
    MMUIViewController *_containerVC;
    UIView *_contentView;
    UICollectionView *_taskCollectionView;
    WAPopOverTaskBarlogic *_taskBarLogic;
}

@property(retain, nonatomic) WAPopOverTaskBarlogic *taskBarLogic; // @synthesize taskBarLogic=_taskBarLogic;
@property(retain, nonatomic) UICollectionView *taskCollectionView; // @synthesize taskCollectionView=_taskCollectionView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak MMUIViewController *containerVC; // @synthesize containerVC=_containerVC;
@property(nonatomic) BOOL isNeedBackToChatButton; // @synthesize isNeedBackToChatButton=_isNeedBackToChatButton;
@property(nonatomic) __weak id <WAPopOverTaskBarViewDelegate> taskBarViewDelegate; // @synthesize taskBarViewDelegate=_taskBarViewDelegate;
- (void).cxx_destruct;
- (void)onMainFrameTaskItemUpdated;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (BOOL)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)taskItemAtRowIndex:(int)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (float)calCollectionViewHeight;
- (void)layoutTaskCollectionView;
- (void)layoutContentView;
- (void)reloadData;
- (void)initTaskCollectionView;
- (void)initContentView;
- (void)initView;
- (void)layoutSubviews;
- (void)moveToLeftMostTaskItem;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithPopOverTaskBarLogic:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

