//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMKernelExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, WAPrefetchGetCodeLogic;

@interface WAPrefetchMgr : MMService <MMKernelExt, PBMessageObserverDelegate, MMService>
{
    NSMutableDictionary *_queue;
    WAPrefetchGetCodeLogic *_getCodeLogic;
    NSMutableArray *_arrFetching;
    NSMutableArray *_arrWaiting;
}

@property(retain, nonatomic) NSMutableArray *arrWaiting; // @synthesize arrWaiting=_arrWaiting;
@property(retain, nonatomic) NSMutableArray *arrFetching; // @synthesize arrFetching=_arrFetching;
@property(retain, nonatomic) WAPrefetchGetCodeLogic *getCodeLogic; // @synthesize getCodeLogic=_getCodeLogic;
@property(retain, nonatomic) NSMutableDictionary *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)executeBlockCgiRequestCmd:(id)arg1;
- (void)executeIssueDecryptCmd:(id)arg1;
- (void)executeIssueLaunchCmd:(id)arg1;
- (void)executeIssueContactCmd:(id)arg1;
- (void)executeGetCodeCmd:(id)arg1;
- (void)executeUpdateVersionCmd:(id)arg1;
- (void)executeGetContactCmd:(id)arg1;
- (id)popCmd;
- (void)executeCmds;
- (void)pushCmd:(id)arg1;
- (unsigned int)preCheckSequenceForCmd:(id)arg1;
- (void)preProcessBlockCgiRequestCmd:(id)arg1;
- (void)preProcessIssueDecryptCmd:(id)arg1;
- (void)preProcessIssueLaunchCmd:(id)arg1;
- (void)preProcessIssueContactCmd:(id)arg1;
- (void)preProcessGetCodeCmd:(id)arg1;
- (void)preProcessUpdateVersionCmd:(id)arg1;
- (void)preProcessGetContactCmd:(id)arg1;
- (BOOL)checkRespInfoIsValid:(id)arg1;
- (void)handleBatchSyncVersionRespList:(id)arg1;
- (void)handlePushWxACmdMsg:(id)arg1;
- (void)handleBatchSyncVersion:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (id)fetchNeedSyncUsageInfoAndClearOutdatedUsageInfo;
- (BOOL)sendRequest:(id)arg1 Retry:(unsigned long)arg2;
- (BOOL)requestVersionSyncForUsernameList:(id)arg1;
- (void)checkWaitingQueue;
- (void)syncVersion;
- (void)cancelHeartBeatCheck;
- (void)realHeartBeatCheckWeappVersion;
- (void)heartBeatCheckWeappVersion;
- (void)onAuthOK;
- (void)onServiceEnterBackground;
- (void)onServiceEnterForeground;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

