//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "MMKernelExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"
#import "WAPackageDownloadLogicDelegate.h"

@class NSString, WAPackageDownloadLogic, WAPackageInfoCacheLogic, WAPackageSweeperLogic, WAPublicResInfo, WAPublicResInfoStorage;

@interface WAPublicResCacheMgr : MMService <WAPackageDownloadLogicDelegate, PBMessageObserverDelegate, IMsgExt, MMKernelExt, MMService>
{
    WAPackageDownloadLogic *_pkgDownloadLogic;
    WAPackageInfoCacheLogic *_pkgInfoCacheLogic;
    WAPackageSweeperLogic *_pkgSweeperLogic;
    NSString *_curDownloadUrlStr;
    BOOL _bIsDownloading;
    BOOL _bIsLoadedFileInfo;
    WAPublicResInfoStorage *m_resInfoStorage;
    WAPublicResInfo *_curServerRetInfo;
    long long _startDownloadTime;
    CDUnknownBlockType _syncUpdatePubLibHandler;
    BOOL needUnpackBeforeNewTaskBegin;
}

@property BOOL needUnpackBeforeNewTaskBegin; // @synthesize needUnpackBeforeNewTaskBegin;
- (void).cxx_destruct;
- (void)tryCloseBackgroundTaskAndRestartPreloadTask;
- (void)tryUnpackNewPubData;
- (void)processPublicPkgUpdateNotifyVersion:(unsigned long)arg1 pkgUrl:(id)arg2 patchUrl:(id)arg3 md5:(id)arg4 isForceUpdate:(BOOL)arg5 scene:(unsigned int)arg6 updateType:(unsigned long)arg7;
- (void)parseNotifyMsg:(id)arg1;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)updatePublicResPkgWithScene:(unsigned int)arg1;
- (void)removeDustPublicPkgWithVersion:(unsigned long long)arg1;
- (void)reportPatchUpdateKvInfo:(BOOL)arg1 debugMode:(unsigned int)arg2 publicInfo:(id)arg3 isPatch:(BOOL)arg4 pkgSize:(unsigned int)arg5;
- (void)reportKvInfo:(BOOL)arg1 debugMode:(BOOL)arg2 downloadPercent:(unsigned int)arg3 eventID:(unsigned int)arg4;
- (void)onDownloadTaskCompletion:(int)arg1 taskUrl:(id)arg2 filePath:(id)arg3;
- (void)onDownloadTaskProgress:(float)arg1 remainingTime:(unsigned int)arg2 totalLength:(unsigned int)arg3 taskUrl:(id)arg4;
- (void)syncHandlerActionWithRet:(BOOL)arg1;
- (BOOL)downloadDebugPublicPkgWithInfo:(id)arg1;
- (BOOL)downloadPublicPkgWithUrl:(id)arg1 patchUrl:(id)arg2;
- (BOOL)isDownloading;
- (BOOL)isNeedDownloadPublicDebugModePkg:(id)arg1;
- (void)asyncUpdatePublicResPkgFromLaunchWithInfo:(id)arg1;
- (void)syncUpdatePublicResPkgFromLaunchWithInfo:(id)arg1 completeHandler:(CDUnknownBlockType)arg2;
- (void)tryUpdatePublicResPkg;
- (id)getCurrentPublicReleaseInfo;
- (id)getPublicForceLocalCacheData:(unsigned int)arg1;
- (id)getPublicRelativePath:(unsigned int)arg1;
- (id)getPublicLocalCacheData:(unsigned int)arg1;
- (id)getLocalCacheDataWithRelativePath:(id)arg1 version:(unsigned int)arg2;
- (BOOL)loadPublicPkgInfoLocalCache:(unsigned int)arg1 version:(unsigned int)arg2;
- (BOOL)verifyLocalCacheChecksum:(id)arg1 debugModeType:(unsigned int)arg2 version:(unsigned int)arg3;
- (void)saveResInfoStorage:(id)arg1;
- (void)loadResInfoStorage;
- (void)onServiceEnterBackground;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)onAuthOK;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

