//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ILinkEventExt.h"
#import "PBMessageObserverDelegate.h"
#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"
#import "WARedEnvelopesShareViewControllerDelegate.h"
#import "WCBizPickerViewDelegate.h"
#import "WCPayPlathbPayMoneyLogicDelegate.h"

@class MMTableView, MMTextView, NSArray, NSString, RichTextView, UIButton, UILabel, UIView, WCBizPickerView, WCRedEnvelopesMakeRedEnvelopesViewLayout, WCUITextField;

@interface WARedEnvelopesMakeViewController : MMUIViewController <UITextFieldDelegate, UITextViewDelegate, ILinkEventExt, UIPickerViewDelegate, UIPickerViewDataSource, WCBizPickerViewDelegate, PBMessageObserverDelegate, WCPayPlathbPayMoneyLogicDelegate, WARedEnvelopesShareViewControllerDelegate>
{
    BOOL m_bCanHandleScrollViewDidChangedEvent;
    BOOL m_bError;
    BOOL m_bNomalMoney;
    BOOL m_bScopeAll;
    unsigned long m_uiSelectCount;
    int m_inputErrorType;
    NSString *m_appID;
    NSArray *m_arrScope;
    NSString *m_defaultWishing;
    NSString *m_sendID;
    id <WARedEnvelopesMakeViewControllerDelegate> m_delegate;
    WCRedEnvelopesMakeRedEnvelopesViewLayout *_m_layout;
    UIView *_m_navigationBackgroundView;
    MMTableView *_tableView;
    UIView *_moneyView;
    WCUITextField *_moneyTextField;
    RichTextView *_richTextView;
    UIView *_countView;
    WCUITextField *_countTextField;
    UIView *_visibleView;
    MMTextView *_textView;
    UILabel *_amountLabel;
    UILabel *_unitLabel;
    UIButton *_redEnvelopesButton;
    UIView *_errorView;
    UILabel *_errorLabel;
    WCBizPickerView *_pickerView;
    UIButton *_scopeBtn;
}

@property(retain, nonatomic) UIButton *scopeBtn; // @synthesize scopeBtn=_scopeBtn;
@property(retain, nonatomic) WCBizPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(retain, nonatomic) UILabel *errorLabel; // @synthesize errorLabel=_errorLabel;
@property(retain, nonatomic) UIView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) UIButton *redEnvelopesButton; // @synthesize redEnvelopesButton=_redEnvelopesButton;
@property(retain, nonatomic) UILabel *unitLabel; // @synthesize unitLabel=_unitLabel;
@property(retain, nonatomic) UILabel *amountLabel; // @synthesize amountLabel=_amountLabel;
@property(retain, nonatomic) MMTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIView *visibleView; // @synthesize visibleView=_visibleView;
@property(retain, nonatomic) WCUITextField *countTextField; // @synthesize countTextField=_countTextField;
@property(retain, nonatomic) UIView *countView; // @synthesize countView=_countView;
@property(retain, nonatomic) RichTextView *richTextView; // @synthesize richTextView=_richTextView;
@property(retain, nonatomic) WCUITextField *moneyTextField; // @synthesize moneyTextField=_moneyTextField;
@property(retain, nonatomic) UIView *moneyView; // @synthesize moneyView=_moneyView;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *m_navigationBackgroundView; // @synthesize m_navigationBackgroundView=_m_navigationBackgroundView;
@property(retain, nonatomic) WCRedEnvelopesMakeRedEnvelopesViewLayout *m_layout; // @synthesize m_layout=_m_layout;
@property(nonatomic) __weak id <WARedEnvelopesMakeViewControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (long)totalAmount;
- (long)perMinValue;
- (long)perPersonMaxValue;
- (unsigned long)totalNum;
- (void)adjustAmountLabel;
- (void)checkDataError;
- (void)hideErrorViewWithAnimation;
- (void)hideErrorView;
- (void)showErrorView:(id)arg1 ErrorType:(int)arg2;
- (void)keyboardWillShow:(id)arg1;
- (void)hidekeyboard;
- (void)handleTap:(id)arg1;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (BOOL)textViewShouldEndEditing:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (void)resetToCanHandleScrollViewChangedEnvent;
- (void)textFieldDidChanged:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (BOOL)textFieldShouldEndEditing:(id)arg1;
- (BOOL)textFieldShouldBeginEditing:(id)arg1;
- (void)WCBizPickerViewDidComplete:(id)arg1;
- (id)pickerView:(id)arg1 viewForRow:(int)arg2 forComponent:(int)arg3 reusingView:(id)arg4;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (void)plathbPayFail;
- (void)plathbPaySucc;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)startPayMoney:(id)arg1;
- (void)onScopeBtnClick;
- (void)OnMakeWCRedEnvelopesButtonClick;
- (void)onLeftBarButtonDone;
- (void)setupUI;
- (id)navigationBarBackgroundColor;
- (void)initNavigationBar;
- (void)setColorTitle:(id)arg1 TextColor:(id)arg2;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithAppID:(id)arg1 arrScope:(id)arg2 defaultWishing:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

