//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WARemoteDebugRecvQueue : NSObject
{
    NSMutableArray *_recvIntervalList;
    unsigned long _currRecvSeq;
    unsigned long _prevRecvSeq;
    unsigned long _accumulateCount;
    id <WARemoteDebugRecvQueueDelegate> _delegate;
}

@property(nonatomic) __weak id <WARemoteDebugRecvQueueDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)clearAccumulateCount;
- (unsigned long)getIntervalRecvCount;
- (unsigned long)getCurrRecvSeq;
- (void)logRecvIntervalList;
- (void)handleFirstRecvInterval;
- (void)mergeMessages:(id)arg1 cmdID:(unsigned long)arg2;
- (void)dealloc;
- (id)init;

@end

