//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportWebViewMenuActionItem : WAReportBaseItem
{
    unsigned int _actionType;
    NSString *_actionNote;
    unsigned long _actionTimeStamp;
    unsigned int _actionResult;
    int _errcode;
}

@property(nonatomic) int errcode; // @synthesize errcode=_errcode;
@property(nonatomic) unsigned int actionResult; // @synthesize actionResult=_actionResult;
@property(nonatomic) unsigned long actionTimeStamp; // @synthesize actionTimeStamp=_actionTimeStamp;
@property(copy, nonatomic) NSString *actionNote; // @synthesize actionNote=_actionNote;
@property(nonatomic) unsigned int actionType; // @synthesize actionType=_actionType;
- (void).cxx_destruct;
- (id)reportString;

@end

