//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CContact, NSString, UINavigationController, WASessionContentViewController;

@protocol WASessionContentLogicHandlerDelegate <NSObject>
- (NSString *)getFromPagePath;
- (NSString *)getFatherAppid;
- (unsigned int)getDebugMode;
- (unsigned long)getAppVersion;
- (NSString *)getSessionSceneID;
- (NSString *)getSessionContentPageID;
- (unsigned int)getSessionContentEnterScene;
- (WASessionContentViewController *)getSessionContentViewController;
- (UINavigationController *)getSessionContentNavigationController;
- (CContact *)getSessionContentContact;
@end

