//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMsgContentViewController.h"

#import "MsgImgFullScreenViewControllerDelegate.h"

@class NSString, WAAppIdToUsernameTransfer;

@interface WASessionContentViewController : BaseMsgContentViewController <MsgImgFullScreenViewControllerDelegate>
{
    WAAppIdToUsernameTransfer *_appIdTransfer;
    NSString *_sceneID;
}

@property(copy, nonatomic) NSString *sceneID; // @synthesize sceneID=_sceneID;
- (void).cxx_destruct;
- (id)getWASessionContentDelegate;
- (id)getTitleView:(id)arg1 withSubTitle:(id)arg2 tailImage:(id)arg3;
- (void)updateTitleAndSubTitleView:(id)arg1;
- (void)updateTitleView:(id)arg1;
- (id)getRightBarButton;
- (void)PreviewImage:(id)arg1 soundable:(BOOL)arg2 snapshotView:(id)arg3 needEdit:(BOOL)arg4;
- (void)headerImageClicked:(id)arg1;
- (void)filterShowMenuItem:(id)arg1 sender:(id)arg2;
- (void)onWeAppSessionMsgBtnClick:(id)arg1;
- (void)onWeAppSessionMsgBtnHide;
- (BOOL)isHiddenInputChangeButton;
- (void)initAllowVoiceInput;
- (void)initAllowShareCard;
- (BOOL)canShowScheduleEntry;
- (BOOL)canShowEnterpriseBrandEntry;
- (BOOL)canShowLocation;
- (BOOL)canShowFavEntry;
- (BOOL)hasGroupPayEntry;
- (BOOL)hasCardPkgEntry;
- (BOOL)hasRedEnvelopesEntry;
- (BOOL)hasTransferMoneyEntry;
- (BOOL)hasServiceEntry;
- (void)viewDidBePoped:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

