//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUIButton, MMUILabel, NSString, UIActivityIndicatorView, UIImageView, UILongPressGestureRecognizer, UIView, WAPopOverTaskBarlogic, WAPopOverView, WAWebViewController;

@interface WAWebViewMutiFuncMenuView : MMUIView
{
    NSString *_normalLastNavTitle;
    MMUILabel *_normalTitleView;
    BOOL _isActivityIndicatorAnimating;
    UIActivityIndicatorView *_activityIndicatorView;
    MMUIButton *_returnButton;
    UIView *_menuView;
    MMUIButton *_menuMoreButton;
    MMUIButton *_menuExitButton;
    BOOL _isMenuHidden;
    MMUIButton *_menuStateButton;
    UIImageView *_menuIconView;
    UILongPressGestureRecognizer *_moreLongPressRecognizer;
    BOOL _isTrigerMoreLongPress;
    UILongPressGestureRecognizer *_longPressRecognizer;
    WAPopOverTaskBarlogic *_popOverLogic;
    WAPopOverView *_popOverView;
    BOOL _canShowShare;
    id <WAWebViewMutiFuncMenuViewDelegate> _delegate;
    WAWebViewController *_webview;
    int _navMode;
    int _contentMode;
    int _menuState;
}

@property(nonatomic) int menuState; // @synthesize menuState=_menuState;
@property(nonatomic) BOOL canShowShare; // @synthesize canShowShare=_canShowShare;
@property(nonatomic) int contentMode; // @synthesize contentMode=_contentMode;
@property(nonatomic) int navMode; // @synthesize navMode=_navMode;
@property(nonatomic) __weak WAWebViewController *webview; // @synthesize webview=_webview;
@property(nonatomic) __weak id <WAWebViewMutiFuncMenuViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onLongPressExitItem:(id)arg1;
- (void)onLongPressMoreItem:(id)arg1;
- (id)pluginWeAppMsg;
- (id)pluginVideoPlayer;
- (BOOL)isSupportVisualEffect;
- (id)stateButton;
- (id)menuView;
- (void)onReturn;
- (void)onExit;
- (void)onMore;
- (id)copyMenuView;
- (void)changeMenuStateToRecordingVideo;
- (void)changeMenuStateToRecordingVoice;
- (void)changeMenuStateToLocation;
- (void)changeMenuStateToNormal;
- (void)onWebViewDidAppear;
- (void)fsmenu_udpateContent;
- (void)fsnormal_layoutContent;
- (void)fsnormal_updateContent;
- (void)setMenuTitleViewLoading:(BOOL)arg1;
- (void)setMenuViewCapsuleHidden:(BOOL)arg1;
- (void)setMenuNavTitle:(id)arg1;
- (void)setMenuNavBackgroundColor:(id)arg1;
- (void)layoutSubviews;
- (void)updateMenuViewWithWebContentMode:(int)arg1 navMode:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

