//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAWebViewPluginBase.h"

#import "IRecordPermissionCheckExt.h"
#import "IVOIPUILogicMgrExt.h"
#import "IWebviewRecorderManagerExt.h"
#import "MultiTalkMgrExt.h"
#import "UIAlertViewDelegate.h"

@class NSString;

@interface WAWebViewPlugin_Recorder : WAWebViewPluginBase <IRecordPermissionCheckExt, IWebviewRecorderManagerExt, UIAlertViewDelegate, IVOIPUILogicMgrExt, MultiTalkMgrExt>
{
    BOOL _isCheckingPermission;
    id <IWAWebViewPluginDelegate> _resultDelegate;
    unsigned int _duration;
}

@property(nonatomic) unsigned int duration; // @synthesize duration=_duration;
@property(nonatomic) BOOL isCheckingPermission; // @synthesize isCheckingPermission=_isCheckingPermission;
@property(nonatomic) __weak id <IWAWebViewPluginDelegate> resultDelegate; // @synthesize resultDelegate=_resultDelegate;
- (void).cxx_destruct;
- (void)onBeginMultiTalk;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)onFinishedRecord:(id)arg1 ErrCode:(int)arg2 stopReason:(int)arg3;
- (void)onRecordTimeTooShort;
- (void)onStartRecord:(int)arg1;
- (void)OnRecordDenied;
- (void)OnRecordPermissioned;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)updateWebviewTitle;
- (void)realStartRecord;
- (BOOL)handleEvent:(unsigned int)arg1 userInfo:(id)arg2;
- (void)stopRecorder;
- (void)startRecorderForDuration:(unsigned int)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

