//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCAccountBaseViewController.h"

@class NSString, UIButton;

@interface WCAccountBindPhoneSetPrivateViewController : WCAccountBaseViewController
{
    BOOL m_bAgreementMobileCanBeFound;
    BOOL m_bAgreementPushFriendToMe;
    NSString *m_nsHeaderWording;
    id <WCAccountBindPhoneSetPrivateViewControllerDelegate> m_delegate;
    UIButton *m_pushFriendToMeBtn;
    UIButton *m_mobileCanBeFoundBtn;
}

- (void).cxx_destruct;
- (void)setDelegate:(id)arg1;
- (void)viewDidLoad;
- (void)initTableView;
- (void)onPushFriendToMeAgreementClick;
- (void)onMobileCanBeFoundAgreementClick;
- (void)setPushFriendToMe:(BOOL)arg1;
- (void)setAgreeMobileCanBeFound:(BOOL)arg1;
- (void)initNavigationBar;
- (void)onNext;

@end

