//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextViewDelegate.h"

@class MMTableView, NSString, UILabel, UITextView, WCADQuestionExp, WCDataItem;

@interface WCAdvertiseUnlikeViewController : MMUIViewController <UITextViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    WCDataItem *_dataItem;
    WCADQuestionExp *_oExp;
    UILabel *m_wordCountLabel;
    MMTableView *m_tableView;
    UITextView *m_textView;
}

- (void).cxx_destruct;
- (void)onReasonSend;
- (void)onCancel;
- (void)updateWordCount:(int)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithDataItem:(id)arg1 Exp:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

