//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface WCAdFeedDisplayInfo : NSObject <NSCoding>
{
    int contentDisplayType;
    int mediaDisplayMode;
    int basicRemWidth;
    int basicRootFontSize;
    float mediaDisplayWidth;
    float mediaDisplayHeight;
    NSString *mediaIconUrl;
    float mediaIconWidth;
    float mediaIconHeight;
    float mediaIconPaddingRight;
    float mediaIconPaddingBottom;
}

@property(nonatomic) float mediaIconPaddingBottom; // @synthesize mediaIconPaddingBottom;
@property(nonatomic) float mediaIconPaddingRight; // @synthesize mediaIconPaddingRight;
@property(nonatomic) float mediaIconHeight; // @synthesize mediaIconHeight;
@property(nonatomic) float mediaIconWidth; // @synthesize mediaIconWidth;
@property(retain, nonatomic) NSString *mediaIconUrl; // @synthesize mediaIconUrl;
@property(nonatomic) float mediaDisplayHeight; // @synthesize mediaDisplayHeight;
@property(nonatomic) float mediaDisplayWidth; // @synthesize mediaDisplayWidth;
@property(nonatomic) int basicRootFontSize; // @synthesize basicRootFontSize;
@property(nonatomic) int basicRemWidth; // @synthesize basicRemWidth;
@property(nonatomic) int mediaDisplayMode; // @synthesize mediaDisplayMode;
@property(nonatomic) int contentDisplayType; // @synthesize contentDisplayType;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

