//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface WCAppInfo : NSObject <NSCoding>
{
    NSString *appID;
    NSString *appName;
    NSString *version;
    NSString *installUrl;
    NSString *fromUrl;
    BOOL isForceUpdate;
    BOOL clickable;
}

@property(nonatomic) BOOL clickable; // @synthesize clickable;
@property(nonatomic) BOOL isForceUpdate; // @synthesize isForceUpdate;
@property(retain, nonatomic) NSString *fromUrl; // @synthesize fromUrl;
@property(retain, nonatomic) NSString *installUrl; // @synthesize installUrl;
@property(retain, nonatomic) NSString *version; // @synthesize version;
@property(retain, nonatomic) NSString *appName; // @synthesize appName;
@property(retain, nonatomic) NSString *appID; // @synthesize appID;
- (void).cxx_destruct;
- (BOOL)isValid;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

