//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCBizUtil : NSObject
{
}

+ (unsigned long)transferTinyAppEnterSceneToPayChannel:(unsigned int)arg1;
+ (BOOL)isShowTransToBankCardEntry;
+ (BOOL)isSystemPushSoundOpen;
+ (unsigned long long)getCorrectUIntValueFromDouble:(double)arg1;
+ (id)getContactDisplayName:(id)arg1;
+ (BOOL)isNetworkConnected;
+ (id)getGeneralActionLocation;
+ (id)getActionLocation;
+ (void)reportLocationAlert:(int)arg1 type:(int)arg2;
+ (id)parseRealnameGuideInfo:(id)arg1 alertViewScene:(int)arg2;
+ (void)logRealnameAction:(int)arg1;
+ (id)getBankResource:(id)arg1;
+ (void)logBannerUserAction:(int)arg1 bannerType:(int)arg2;
+ (void)playCoinSound;
+ (void)bizReportBannerUserAction:(int)arg1 bannType:(int)arg2;
+ (id)GetWCBizMainWindow;
+ (void)SetWCBizMainWindow:(id)arg1;
+ (void)ClearWCBizMainWindow;
+ (id)getTempFullPathOfYearHBImageForSender:(id)arg1;
+ (id)getFullPathOfYearHBImageWithFileId:(id)arg1 userName:(id)arg2;
+ (id)imageWithColor:(id)arg1;
+ (unsigned long)convertTenpayCmdIdToNewCGI:(unsigned long)arg1 payScene:(unsigned long)arg2;
+ (id)convertCGIEnumToString:(unsigned long)arg1;
+ (void)logOfflinePayGetToken:(int)arg1;
+ (void)logUserAction:(int)arg1;
+ (void)logLoanMoneyAction:(int)arg1;
+ (void)logTransferAction:(int)arg1;
+ (id)feeSymbolFromType:(id)arg1;
+ (id)feeTextFromType:(id)arg1 fee:(int)arg2;
+ (BOOL)isEmptyKey:(id)arg1 inDictionary:(id)arg2;
+ (BOOL)isDomesticOrderWithMulitOrderDetail:(id)arg1;
+ (BOOL)isDomesticUserWithCardUserFlag:(unsigned long)arg1;
+ (BOOL)isOverseasUserWithCardUserFlag:(unsigned long)arg1;
+ (BOOL)isDomesticCardWithCardBankTag:(unsigned long)arg1;
+ (BOOL)isOverseasCardWithCardBankTag:(unsigned long)arg1;
+ (unsigned long)differntCharactorCountCompareString:(id)arg1 WithOriginalString:(id)arg2;
+ (id)getAddressBookTelphoneNumberDictionary;
+ (id)validWCMallPhoneNumber:(id)arg1;
+ (id)dictionaryWithDecodedComponets:(id)arg1 separator:(id)arg2;
+ (id)stringWithFormEncodedComponentsAscending:(id)arg1 ascending:(BOOL)arg2 skipempty:(BOOL)arg3 separator:(id)arg4;
+ (id)getWCBizLoginTitle:(id)arg1 MaxWidth:(float)arg2;
+ (id)getWCBizAuthTitle:(id)arg1 MaxWidth:(float)arg2;
+ (id)getTitleViewWithTitle:(id)arg1 SubTitle:(id)arg2 LandscapeMode:(BOOL)arg3 MaxWidth:(float)arg4;
+ (id)getTitleViewWithTitle:(id)arg1 LandscapeMode:(BOOL)arg2 MaxWidth:(float)arg3;
+ (id)getWCBizLoginTitle:(id)arg1 LandscapeMode:(BOOL)arg2 MaxWidth:(float)arg3;
+ (id)getWCBizAuthTitle:(id)arg1 LandscapeMode:(BOOL)arg2 MaxWidth:(float)arg3;
+ (id)getSaveStyleBarItemTitle:(id)arg1 target:(id)arg2 sel:(SEL)arg3;
+ (id)getWCPayQRCodeGetCodeCgiCachePath;
+ (id)getWCPayRewardCodeImageTempDownloadDataPath;
+ (id)getWCPayRewardCodeImageDataPath;
+ (id)getWCPayRewardCodeImageForderPath;
+ (id)getWCPayLQTEnteranceInfoPath;
+ (id)getWCPayWebImageDefaultCacheFolderPath;
+ (id)getWCPayFunctionActivityFolderPath;
+ (id)getWCPayBankIconCacheFolderPath;
+ (id)getWCPayCgiResponseCachePathWith:(id)arg1;
+ (id)getWCPayDigitalCrtPath;
+ (id)getWCPayRealnameWordingPath;
+ (id)getWCPayMessageResourceFolder;
+ (id)getWCPayBankImageResourceFolder;
+ (id)getWCPayBankResourcePath;
+ (id)getWCPayPayManagePath;
+ (id)getWCRedEnvelopesLastRadomHBSelctedCountPath;
+ (id)getWCRedEnvelopesUserInfoPath;
+ (id)getWCMallFunctionListPath;
+ (id)getWCPayServerDynamicWordingPath;
+ (id)getFiltedTruthName:(id)arg1;
+ (id)getCreditCardHadViewFilePath;
+ (id)getWCAddressStageDataFilePath;
+ (id)getWCMallShowedInActivityCellProductId;
+ (id)getWCMallShowedBannerId;
+ (id)getWCMallShowedProductId;
+ (id)getWCMallShowedRedCodePath;
+ (id)getWCMallShowedNewPath;
+ (id)getWCMallTicketsListPath;
+ (id)getWCMallLatestActivityTipsPath;
+ (id)getWCMallTelephoneDictionaryPath;
+ (id)getWCMallTelephoneListPath;
+ (id)getWCAddressYiXunFilePath;
+ (id)getWCAddressFilePath;
+ (id)getWCPayLoanEntryInfoPath;
+ (id)getWCPayTransferedUserListPath;
+ (id)getWCPayNoticeInfoPath;
+ (id)getWCPayLQTInfoPath;
+ (id)getWCPayBalancePath;
+ (id)getBindQueryNewApplyNewCardInfoWithScene:(int)arg1;
+ (id)getBindQueryNewPayMenuArrayInfoPathWithScene:(int)arg1;
+ (id)getWCPaySwitchInfoPath;
+ (id)getWCPayUserInfoPath;
+ (id)getWCPayCreditCardShowedNewInfoPath;
+ (id)getWCPayOfflinePayCardListDataPath;
+ (id)getWCPayOfflinePayShowedNewInfoPath;
+ (id)getWCPayOfflinePayQueryUsrerInfoPath;
+ (id)getWCPayOfflinePayQueryInfoPath;
+ (id)getWCPayOfflinePayOfflineGetMsgConfigPath;
+ (id)getWCPayOfflinePayOrderIdStatePath;
+ (id)getWCPayOfflinePayUserUinPath;
+ (id)getWCPayOfflinePayFreezeInfoPath;
+ (id)getWCPayOfflinePayDeviceIDPath;
+ (id)getWCPayUserPrivacyInfoPath;
+ (id)getWCPayOfflinePayCrtPath;
+ (id)getWCPayAvalibleCardBinInfoPath;
+ (id)getWCPayAllScenePayCardListPath;
+ (id)getWCPayPayCardListPath;
+ (id)getWCPaySettingPath;
+ (id)getWCBizImgCachedPath:(id)arg1;
+ (BOOL)isBindCardInfoFull:(id)arg1;
+ (id)getHeaderTipView:(id)arg1;
+ (id)getHeaderErrorTipView:(id)arg1;
+ (float)getFooterTipViewHeight:(id)arg1;
+ (id)getFooterTipView:(id)arg1;
+ (id)getFooterErrorTipView:(id)arg1;
+ (id)getStringFromBindCardInfo:(id)arg1;
+ (id)getCardTypeName:(id)arg1;
+ (BOOL)isShouldShowSetPasswordTipsView:(id)arg1;
+ (BOOL)IsWCGroupPayAppServiceInPlane:(id)arg1;
+ (BOOL)IsWCRedEnvelopesAppServiceInPlane:(id)arg1;
+ (BOOL)IsWCPayTransferAppServiceInPlane:(id)arg1;
+ (unsigned char)GetWCPayVersion;

@end

