//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCCardDataSource.h"
#import "WCTTableCoding.h"

@class NSString, WCCardDataCardInfo, WCCardDataCardTPInfo, WCCardDataShareInfo;

@interface WCCardData : MMObject <WCTTableCoding, WCCardDataSource>
{
    BOOL isAutoIncrement;
    WCCardDataCardTPInfo *cardTPInfo;
    WCCardDataCardInfo *cardInfo;
    WCCardDataShareInfo *shareInfo;
    NSString *jsonStrForTest;
    int uiLayoutType;
    NSString *layoutAnnounce;
    NSString *layoutTitle;
    NSString *encryptCode;
    NSString *labelWording;
    unsigned long localCardId;
    NSString *cardId;
    NSString *cardTpId;
    unsigned long beginTime;
    unsigned long endTime;
    unsigned long stateFlag;
    unsigned long updateSeq;
    unsigned long localUpdateSeq;
    unsigned long updateTime;
    unsigned long localUpdateTime;
    unsigned long isDynamicCode;
    NSString *cardTPInfoForDB;
    NSString *cardInfoForDB;
    NSString *shareInfoForDB;
    unsigned long IntRes1;
    unsigned long IntRes2;
    unsigned long IntRes3;
    NSString *StrRes1;
    NSString *StrRes2;
    NSString *StrRes3;
    long long lastInsertedRowID;
}

+ (id)getShareInfoStr:(id)arg1;
+ (id)getCardInfoStr:(id)arg1;
+ (id)getCardTPInfoStr:(id)arg1;
+ (void)parseShareInfoDic:(id)arg1 ToShareInfo:(id)arg2;
+ (void)parseCardInfoDic:(id)arg1 ToCardInfo:(id)arg2;
+ (void)parseCardTPInfoDic:(id)arg1 ToCardTpInfo:(id)arg2;
+ (const struct WCTProperty *)StrRes3;
+ (const struct WCTProperty *)StrRes2;
+ (const struct WCTProperty *)StrRes1;
+ (const struct WCTProperty *)IntRes3;
+ (const struct WCTProperty *)IntRes2;
+ (const struct WCTProperty *)IntRes1;
+ (const struct WCTProperty *)shareInfoForDB;
+ (const struct WCTProperty *)cardInfoForDB;
+ (const struct WCTProperty *)cardTPInfoForDB;
+ (const struct WCTProperty *)isDynamicCode;
+ (const struct WCTProperty *)localUpdateTime;
+ (const struct WCTProperty *)updateTime;
+ (const struct WCTProperty *)localUpdateSeq;
+ (const struct WCTProperty *)updateSeq;
+ (const struct WCTProperty *)stateFlag;
+ (const struct WCTProperty *)endTime;
+ (const struct WCTProperty *)beginTime;
+ (const struct WCTProperty *)cardTpId;
+ (const struct WCTProperty *)cardId;
+ (const struct WCTProperty *)localCardId;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(nonatomic) long long lastInsertedRowID; // @synthesize lastInsertedRowID;
@property(nonatomic) BOOL isAutoIncrement; // @synthesize isAutoIncrement;
@property(retain, nonatomic) NSString *StrRes3; // @synthesize StrRes3;
@property(retain, nonatomic) NSString *StrRes2; // @synthesize StrRes2;
@property(retain, nonatomic) NSString *StrRes1; // @synthesize StrRes1;
@property(nonatomic) unsigned long IntRes3; // @synthesize IntRes3;
@property(nonatomic) unsigned long IntRes2; // @synthesize IntRes2;
@property(nonatomic) unsigned long IntRes1; // @synthesize IntRes1;
@property(retain, nonatomic) NSString *shareInfoForDB; // @synthesize shareInfoForDB;
@property(retain, nonatomic) NSString *cardInfoForDB; // @synthesize cardInfoForDB;
@property(retain, nonatomic) NSString *cardTPInfoForDB; // @synthesize cardTPInfoForDB;
@property(nonatomic) unsigned long isDynamicCode; // @synthesize isDynamicCode;
@property(nonatomic) unsigned long localUpdateTime; // @synthesize localUpdateTime;
@property(nonatomic) unsigned long updateTime; // @synthesize updateTime;
@property(nonatomic) unsigned long localUpdateSeq; // @synthesize localUpdateSeq;
@property(nonatomic) unsigned long updateSeq; // @synthesize updateSeq;
@property(nonatomic) unsigned long stateFlag; // @synthesize stateFlag;
@property(nonatomic) unsigned long endTime; // @synthesize endTime;
@property(nonatomic) unsigned long beginTime; // @synthesize beginTime;
@property(retain, nonatomic) NSString *cardTpId; // @synthesize cardTpId;
@property(retain, nonatomic) NSString *cardId; // @synthesize cardId;
@property(nonatomic) unsigned long localCardId; // @synthesize localCardId;
@property(retain, nonatomic) NSString *labelWording; // @synthesize labelWording;
@property(retain, nonatomic) NSString *encryptCode; // @synthesize encryptCode;
@property(retain, nonatomic) NSString *layoutTitle; // @synthesize layoutTitle;
@property(retain, nonatomic) NSString *layoutAnnounce; // @synthesize layoutAnnounce;
@property(nonatomic) int uiLayoutType; // @synthesize uiLayoutType;
@property(retain, nonatomic) NSString *jsonStrForTest; // @synthesize jsonStrForTest;
@property(retain, nonatomic) WCCardDataShareInfo *shareInfo; // @synthesize shareInfo;
@property(retain, nonatomic) WCCardDataCardInfo *cardInfo; // @synthesize cardInfo;
@property(retain, nonatomic) WCCardDataCardTPInfo *cardTPInfo; // @synthesize cardTPInfo;
- (void).cxx_destruct;
- (id)getCardTpInfo;
- (id)getCardInfo;
- (id)getCardTpId;
- (id)getCardId;
- (void)loadDataForTest;
- (void)parseFromJSONDic:(id)arg1;
- (void)parseFromJSONStr:(id)arg1;
- (void)dealloc;
- (void)setupDataBeforeWriteDB;
- (void)setupDataFromDB;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

