//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ILinkEventExt.h"
#import "IWCCardPkgExt.h"
#import "IWCShareCardPkgExt.h"
#import "MMRefreshTableFooterDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCCardChooseItemViewDelegate.h"

@class MMTableView, MMUIView, NSData, NSMutableArray, NSString, UIButton, UILabel, UIScrollView, UIView, UrlLabel, WCCardAvailableSeed, WCCardChooseEmptyView, WCTimeLineFooterView;

@interface WCCardChooseViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, IWCCardPkgExt, MMRefreshTableFooterDelegate, WCCardChooseItemViewDelegate, IWCShareCardPkgExt, ILinkEventExt>
{
    WCCardAvailableSeed *_availableSeed;
    BOOL _isLoading;
    NSMutableArray *_cardList;
    NSMutableArray *_shareCardList;
    MMTableView *_tableView;
    WCCardChooseEmptyView *_emptyView;
    UIScrollView *_loadingView;
    UIButton *_confirmBtn;
    UIView *_bottomContentView;
    UILabel *_bottomTipsLabel;
    UrlLabel *_bottomUrlLabel;
    struct map<int, WCCardChooseViewSectionType, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, WCCardChooseViewSectionType>>> _sectionIndexToType;
    WCTimeLineFooterView *_tableFooterView;
    MMUIView *_tableDefaultFooterView;
    NSData *_controlBuff;
    NSMutableArray *_chooseInfoLists;
    id <WCCardChooseViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <WCCardChooseViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onLinkClicked:(id)arg1 backupUrl:(id)arg2 withRect:(struct CGRect)arg3;
- (void)showEmptyView;
- (void)showLoadingView;
- (void)showTableView;
- (void)onMarkShareCardError;
- (void)onMarkedResponse:(BOOL)arg1 success:(BOOL)arg2 andMarkUser:(id)arg3 markCardId:(id)arg4 expiredTime:(float)arg5 payQRCodeWording:(id)arg6;
- (void)onGetAvailableCardInfo:(id)arg1 isEnd:(BOOL)arg2 buff:(id)arg3 ErrCode:(int)arg4;
- (void)onConfirmBtnPress:(id)arg1;
- (void)onLeftButtonOP;
- (void)loadCellSubView:(id)arg1 chooseInfo:(id)arg2;
- (BOOL)bIsSupportMultiSelect;
- (void)onWCCardChooseInfo:(id)arg1;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)initEmptyView;
- (void)initLoadingView;
- (void)initTableView;
- (void)initData;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithCardAvailableSeed:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

