//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCCanvasComponent.h"

#import "VoiceComponentExt.h"
#import "WCCanvasImageLoaderObserver.h"
#import "WCNetworkMediaCoreDelegate.h"

@class MMProgressViewEx, MMUILabel, NSString, UIButton, UIImageView, UIView, WCNetworkMediaCore, WCNetworkMediaSlider;

@interface WCCanvasStreamVideoComponent : WCCanvasComponent <WCNetworkMediaCoreDelegate, VoiceComponentExt, WCCanvasImageLoaderObserver>
{
    BOOL _streamVideoThumbReady;
    BOOL _isFirstInit;
    BOOL _isLastPlaying;
    BOOL _shouldPlayAtBegin;
    MMProgressViewEx *_loadingView;
    MMUILabel *_durationLabel;
    UIView *_bottomView;
    MMUILabel *_currentLabel;
    WCNetworkMediaSlider *_sliderView;
    UIButton *_playButton;
    UIButton *_detailButton;
    UIButton *_voiceControlButton;
    UIButton *_m_hideBtn;
    UIView *_m_maskView;
    UIButton *_m_initPlayButton;
    UIView *_m_initPlayMaskView;
    UIImageView *_m_previewImageView;
    WCNetworkMediaCore *_mediaCore;
    id _timeObserverToken;
    struct CGSize _videoSize;
}

+ (struct CGSize)calcSizeForCanvasItem:(id)arg1 dataItem:(id)arg2 orientation:(int)arg3;
@property(retain, nonatomic) id timeObserverToken; // @synthesize timeObserverToken=_timeObserverToken;
@property(nonatomic) BOOL shouldPlayAtBegin; // @synthesize shouldPlayAtBegin=_shouldPlayAtBegin;
@property(nonatomic) BOOL isLastPlaying; // @synthesize isLastPlaying=_isLastPlaying;
@property(nonatomic) BOOL isFirstInit; // @synthesize isFirstInit=_isFirstInit;
@property(nonatomic) BOOL streamVideoThumbReady; // @synthesize streamVideoThumbReady=_streamVideoThumbReady;
@property(nonatomic) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(retain, nonatomic) WCNetworkMediaCore *mediaCore; // @synthesize mediaCore=_mediaCore;
@property(retain, nonatomic) UIImageView *m_previewImageView; // @synthesize m_previewImageView=_m_previewImageView;
@property(retain, nonatomic) UIView *m_initPlayMaskView; // @synthesize m_initPlayMaskView=_m_initPlayMaskView;
@property(retain, nonatomic) UIButton *m_initPlayButton; // @synthesize m_initPlayButton=_m_initPlayButton;
@property(retain, nonatomic) UIView *m_maskView; // @synthesize m_maskView=_m_maskView;
@property(retain, nonatomic) UIButton *m_hideBtn; // @synthesize m_hideBtn=_m_hideBtn;
@property(retain, nonatomic) UIButton *voiceControlButton; // @synthesize voiceControlButton=_voiceControlButton;
@property(retain, nonatomic) UIButton *detailButton; // @synthesize detailButton=_detailButton;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) WCNetworkMediaSlider *sliderView; // @synthesize sliderView=_sliderView;
@property(retain, nonatomic) MMUILabel *currentLabel; // @synthesize currentLabel=_currentLabel;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) MMUILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) MMProgressViewEx *loadingView; // @synthesize loadingView=_loadingView;
- (void).cxx_destruct;
- (void)onVoiceComponentHasPlayWithSound:(id)arg1;
- (BOOL)shouldForbidDelegateShowArrowDown;
- (void)ImageDidFail:(id)arg1;
- (void)ImageDidLoad:(id)arg1 Url:(id)arg2;
- (void)onMediaCore:(id)arg1 VideoSizeUpdate:(struct CGSize)arg2;
- (void)onMediaCore:(id)arg1 DarutionUpdate:(double)arg2;
- (void)onMediaCore:(id)arg1 CacheDarutionChange:(double)arg2;
- (void)onMediaCore:(id)arg1 StateChange:(int)arg2;
- (BOOL)shouldAutoPlayStreamVideo;
- (void)tryShowDownArrowAnimate;
- (void)hideControlViewsAndTryShowArrowAnimate;
- (void)hideControlViews;
- (void)showControlViewsWithAutoHide;
- (void)showControlViews;
- (void)onInitPlayButtonClick;
- (void)onVoiceIconBtnClick:(id)arg1;
- (void)onHideClick;
- (void)onShowDetail:(id)arg1;
- (void)onPlayClick:(id)arg1;
- (void)onPlaySliderChange:(id)arg1;
- (void)onSliderChange:(id)arg1;
- (BOOL)isInSafeArea;
- (void)componentWillEnterForeground;
- (void)componentDidEnterBackground;
- (void)retryToLoadVideo;
- (id)stringFromTimeInterval:(double)arg1;
- (void)updateSubviewsFrame:(int)arg1;
- (void)updateVideoFrame:(int)arg1;
- (void)refreshCurrentTime;
- (BOOL)isControlViewsHidden;
- (void)tryPlayStreamVideo;
- (void)componentWillStopState:(BOOL)arg1;
- (void)componentWillResumeState:(BOOL)arg1;
- (void)componentHasApperedInMainScreenWithFactor:(float)arg1;
- (void)componentWillDisappearInMainScreen:(BOOL)arg1;
- (void)componentDidFullyApperaInMainScreen:(BOOL)arg1;
- (void)configureWithCanvasItem:(id)arg1 dataItem:(id)arg2 orientation:(int)arg3;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

