//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface WCFeedExposureItem : MMObject <PBCoding>
{
    NSString *nsFeedId;
    unsigned long uiCreateTime;
    unsigned long uiCount;
    NSString *appId;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *appId; // @synthesize appId;
@property(nonatomic) unsigned long uiCount; // @synthesize uiCount;
@property(nonatomic) unsigned long uiCreateTime; // @synthesize uiCreateTime;
@property(retain, nonatomic) NSString *nsFeedId; // @synthesize nsFeedId;
- (void).cxx_destruct;
- (const map_69681069 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

