//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FullScreenViewController.h"

#import "EditImageForwardAndEditLogicDelegate.h"
#import "ForwardMessageLogicDelegate.h"
#import "IVOIPUILogicMgrExt.h"
#import "MMExposeViewControllerDelegate.h"
#import "ShareDataToOpenSDKControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WCImageFullScreenViewContainerDelegate.h"
#import "WCPayControlMgrExt.h"
#import "WCShareAuthViewControllerExt.h"
#import "scrollViewDelegate.h"

@class EditImageForwardAndEditLogicController, ForwardMessageLogicController, MMScrollView, NSArray, NSMutableArray, NSString, ShareDataToOpenSDKController, UIPageControl, UIView;

@interface WCImageFullScreenViewController : FullScreenViewController <UIScrollViewDelegate, scrollViewDelegate, WCImageFullScreenViewContainerDelegate, IVOIPUILogicMgrExt, MMExposeViewControllerDelegate, ShareDataToOpenSDKControllerDelegate, ForwardMessageLogicDelegate, WCShareAuthViewControllerExt, EditImageForwardAndEditLogicDelegate, WCPayControlMgrExt>
{
    UIView *m_fakeScreenView;
    NSArray *m_arrOriginView;
    struct CGRect m_originImageRectInScreen;
    BOOL m_isAnimating;
    MMScrollView *m_scrollView;
    UIPageControl *m_pageCtrl;
    UIView *m_blackMask;
    NSArray *m_arrMediaDataWrap;
    NSArray *m_arrMediaData;
    NSMutableArray *m_arrImage;
    unsigned long m_iCurIndex;
    BOOL m_hasScroll;
    int m_lastDeviceOrientation;
    BOOL m_isAnimationShowing;
    BOOL m_isRotating;
    BOOL m_forbidPreloadImg;
    ShareDataToOpenSDKController *m_shareDataToOpenSDKController;
    ForwardMessageLogicController *m_forwardMsgLogic;
    unsigned long _startTime;
    EditImageForwardAndEditLogicController *m_editImageLogicController;
    BOOL m_isAllowRotate;
    float m_lastScreenWidth;
    id <WCImageFullScreenViewControllerDelegate> m_delegate;
}

@property(nonatomic) __weak id <WCImageFullScreenViewControllerDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) unsigned long m_iCurIndex; // @synthesize m_iCurIndex;
- (void).cxx_destruct;
- (unsigned int)preferredScreenEdgesDeferringSystemGestures;
- (void)onForwardMessageCancelInEditView;
- (void)onForwardMessageSendOKInEditView;
- (float)onBeforeForwardMessageAndReturnDelayTime:(id)arg1;
- (void)onDismissEditView;
- (void)onShowingEditView;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)touchesEnded_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)onShareToOpenSDKWithDataItem:(id)arg1 mediaItem:(id)arg2;
- (void)onPushViewController:(id)arg1 animated:(BOOL)arg2;
- (id)onGetViewController;
- (void)onExposeWithDataItem:(id)arg1;
- (void)onContainerDidZoomWithScale:(float)arg1 andIndex:(unsigned long)arg2;
- (void)onLongPressedEditImage:(id)arg1 atPath:(id)arg2 withFavItem:(id)arg3 editAtFirst:(BOOL)arg4;
- (void)onLongPressedWithMediaItem:(id)arg1;
- (void)onLongPressedAddFav:(id)arg1;
- (void)captureScreen;
- (void)hideWithoutAnimation;
- (void)animationHideWithRotate;
- (void)hideVCAnimation;
- (void)onAnimateFadeOut;
- (void)onContainerAnimationHideStop;
- (void)onWindowHide;
- (void)onContainerAnimationHideStart;
- (void)onContainerAnimationShowStop;
- (void)onContainerAnimationShowStart;
- (void)animationHideStop;
- (BOOL)shouldHideContainerOnRotate;
- (BOOL)isContainerVisible:(id)arg1;
- (void)shouldHideFullScreenForWCPay;
- (void)onTryHideWCImageFullScreen;
- (void)onShareDataToOpenSDKCancel;
- (void)onExposeComplete;
- (void)onExposeCancel;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (id)getCurrentViewController;
- (id)getVisibleViewController;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)getCurMediaItemWrap;
- (void)downloadImage;
- (void)setMediaDataArray:(id)arg1 originView:(id)arg2 index:(unsigned long)arg3 needEdit:(BOOL)arg4;
- (void)setMediaDataArray:(id)arg1 mediaDataWrapArray:(id)arg2 originView:(id)arg3 index:(unsigned long)arg4 needEdit:(BOOL)arg5;
- (void)showVCAnimation;
- (void)resetScrollView;
- (void)clearStatus;
- (void)viewDidLayoutSubviews;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldRotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

