//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCOpLog : NSObject
{
}

- (BOOL)modSnsBlackList:(id)arg1 modType:(int)arg2 syncNow:(BOOL)arg3;
- (BOOL)changeSnsPrivacySetting:(int)arg1 sync:(BOOL)arg2;
- (BOOL)changeShowRecent:(int)arg1 sync:(BOOL)arg2;
- (BOOL)changeStrangerRight:(BOOL)arg1 sync:(BOOL)arg2;
- (id)init;

@end

