//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IWCOutFacadeExt.h"
#import "InviteFriendLogicDelegate.h"
#import "MMImageLoaderObserver.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class MMTableView, MMTimer, MMUIImageView, MMUILabel, MMUIView, NSArray, NSMutableArray, NSMutableDictionary, NSString, UIButton, UIImageView, UISearchDisplayController, UIView, WCOActivityMsgInfo, WCOutInviteFriendLogic, WCOutPhoneContact;

@interface WCOutContactViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, IWCOutFacadeExt, WCActionSheetDelegate, UISearchBarDelegate, UISearchDisplayDelegate, InviteFriendLogicDelegate, MMImageLoaderObserver>
{
    MMTableView *m_tableView;
    MMUIView *m_noDataView;
    UIImageView *redDotView;
    UIButton *m_callBtn;
    NSMutableDictionary *m_allContactsDic;
    NSMutableArray *m_sectionKeyArray;
    NSMutableDictionary *m_nonAddressBookContactsDic;
    NSMutableDictionary *m_contactToArchiveDic;
    NSMutableArray *m_lastCallArchives;
    float m_lastScrollViewOffset;
    MMTimer *m_hideIndexTitleTimer;
    long m_lastScrollTime;
    NSString *m_curLanguage;
    WCOutPhoneContact *m_selectedContactInActionSheet;
    NSArray *m_phoneArrayShowInActionSheet;
    BOOL _bShowIndexTitle;
    BOOL _isSearching;
    NSArray *_fliterContacts;
    UISearchDisplayController *_m_searchDisplayController;
    NSString *_searchText;
    WCOutInviteFriendLogic *_inviteFriendLogic;
    MMUILabel *_balanceLabel;
    MMUILabel *_packageLabel;
    MMUILabel *_discountLabel;
    UIButton *_callbtn;
    UIView *_activityView;
    MMUIImageView *_activityImgView;
    WCOActivityMsgInfo *_activityInfo;
}

@property(retain, nonatomic) WCOActivityMsgInfo *activityInfo; // @synthesize activityInfo=_activityInfo;
@property(retain, nonatomic) MMUIImageView *activityImgView; // @synthesize activityImgView=_activityImgView;
@property(retain, nonatomic) UIView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UIButton *callbtn; // @synthesize callbtn=_callbtn;
@property(retain, nonatomic) MMUILabel *discountLabel; // @synthesize discountLabel=_discountLabel;
@property(retain, nonatomic) MMUILabel *packageLabel; // @synthesize packageLabel=_packageLabel;
@property(retain, nonatomic) MMUILabel *balanceLabel; // @synthesize balanceLabel=_balanceLabel;
@property(retain, nonatomic) WCOutInviteFriendLogic *inviteFriendLogic; // @synthesize inviteFriendLogic=_inviteFriendLogic;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
@property(retain, nonatomic) UISearchDisplayController *m_searchDisplayController; // @synthesize m_searchDisplayController=_m_searchDisplayController;
@property(retain, nonatomic) NSArray *fliterContacts; // @synthesize fliterContacts=_fliterContacts;
@property(nonatomic) BOOL isSearching; // @synthesize isSearching=_isSearching;
@property(nonatomic) BOOL bShowIndexTitle; // @synthesize bShowIndexTitle=_bShowIndexTitle;
- (void).cxx_destruct;
- (void)ImageDidFail:(id)arg1;
- (void)ImageDidLoad:(id)arg1 Url:(id)arg2;
- (void)onTryBtnClick:(id)arg1;
- (void)onBackClick:(id)arg1;
- (void)configActivityView;
- (float)getAccountCellHeight;
- (id)getPackageTitle;
- (id)getActivityTips;
- (id)getbalanceLabelText;
- (void)refreshbalanceLabel;
- (void)didReceiveCouponResponse;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (BOOL)searchBarShouldBeginEditing:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)search:(id)arg1;
- (id)allContacts;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)updateNewxmlInfo;
- (void)addNewCall:(id)arg1;
- (void)updateWCOutContactsInfo;
- (void)updateWCOutContacts:(id)arg1;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)clearSelectStauts;
- (void)rightCallBtnClicked:(id)arg1 event:(id)arg2;
- (id)lastCallCellAtRow:(unsigned int)arg1;
- (id)tableView:(id)arg1 filtercontactCellAtIndexPath:(id)arg2;
- (id)contactCellAtIndexPath:(id)arg1;
- (id)accountCellAtIndexpath:(id)arg1;
- (void)onCellBtnClick:(id)arg1;
- (id)KeypadAndContactCellAtIndexpath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)hideIndexTitle;
- (void)onClickBottomBtn;
- (void)OnOpenAccount;
- (void)deleteRecentCallItemAtIndex:(int)arg1;
- (void)showWellcomeTips;
- (void)showProfileForContact:(id)arg1 AndIsFromLastCallContact:(BOOL)arg2;
- (void)configureBackBarButtomItem;
- (void)configCallBtn;
- (void)configFooterViewWithCount:(unsigned int)arg1;
- (void)configTableView;
- (void)configNoDataHintsLabel;
- (BOOL)showAccount;
- (void)configRecentCallContacts;
- (void)configAccuntSection;
- (void)configSearchDisplayController;
- (void)configData;
- (void)configRightBarButtonItem;
- (void)configView;
- (void)configModel;
- (void)viewWillAppear:(BOOL)arg1;
- (void)initDeepLinkConfig;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

