//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IWCOutFacadeExt.h"
#import "InviteFriendLogicDelegate.h"
#import "SendVerifyMsgViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "contactVerifyLogicDelegate.h"

@class CContactVerifyLogic, MMHDHeadImageView, MMTableView, NSArray, NSMutableArray, NSString, WCOutInviteFriendLogic, WCOutPhoneContact;

@interface WCOutContactProfileViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, IWCOutFacadeExt, contactVerifyLogicDelegate, SendVerifyMsgViewControllerDelegate, InviteFriendLogicDelegate>
{
    WCOutPhoneContact *m_contact;
    MMTableView *m_tableView;
    NSMutableArray *m_sectionKeyArray;
    NSMutableArray *m_cellKeyForOtherSectionArray;
    NSArray *m_recentCallLists;
    NSArray *m_phoneLists;
    float m_nameLabel_X;
    BOOL m_isShowAllRecentCallCell;
    BOOL m_isShowGreenBtn;
    CContactVerifyLogic *m_oContactVerifyLogic;
    MMHDHeadImageView *m_HDHeadImageView;
    WCOutInviteFriendLogic *_inviteFriendLogic;
}

@property(retain, nonatomic) WCOutInviteFriendLogic *inviteFriendLogic; // @synthesize inviteFriendLogic=_inviteFriendLogic;
- (void).cxx_destruct;
- (void)updateWCOutContactsInfo;
- (void)updateWCOutContacts:(id)arg1;
- (void)addNewCall:(id)arg1;
- (void)onSendVerifyMsgCancel;
- (void)onSendVerifyMsgOK;
- (void)onContactVerifyFillVerifyMsg:(id)arg1;
- (void)contactAddContactOk:(id)arg1;
- (void)contactSendRequestOk:(id)arg1;
- (void)onContactVerifyFail;
- (int)numberOfRowForRecentCallSection;
- (id)recentCallCellAtRow:(unsigned int)arg1;
- (id)phoneWithLabelCellAtRow:(unsigned int)arg1 InTableView:(id)arg2;
- (id)baseInfoCellWithInfo:(id)arg1;
- (id)showAllRecentCallCell;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (BOOL)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (BOOL)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)showAllRecentCallItems;
- (void)savePhoneNumToAddressBook;
- (void)didPressedInviteBtn;
- (void)didPressedAddFriendButton;
- (void)configModel;
- (id)getFirstPhoneNumber;
- (void)configTableViewFooterView;
- (void)configTableViewHeaderView;
- (void)configTableView;
- (void)configData;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithWCOutPhoneContact:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

