//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCPayNoticeBannerDelegate.h"

@class MMTableView, NSDictionary, NSMutableDictionary, NSMutableOrderedSet, NSString;

@interface WCPayNewOrderHistoryViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, WCPayNoticeBannerDelegate>
{
    BOOL _isLoadingMore;
    BOOL _couldLoadMore;
    NSString *_orderListExtBuffer;
    NSDictionary *m_dicBanners;
    NSMutableOrderedSet *_sections;
    NSMutableDictionary *_rollDictionary;
    MMTableView *_tableView;
    NSMutableDictionary *_monthFees;
}

@property(retain, nonatomic) NSMutableDictionary *monthFees; // @synthesize monthFees=_monthFees;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableDictionary *rollDictionary; // @synthesize rollDictionary=_rollDictionary;
@property(retain, nonatomic) NSMutableOrderedSet *sections; // @synthesize sections=_sections;
- (void).cxx_destruct;
- (id)getNoticeBanner;
- (void)banner:(id)arg1 clickWithUrl:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)itemFromIndexPath:(id)arg1;
- (id)actualfeeTextFromItem:(id)arg1;
- (id)feeTextFromItem:(id)arg1;
- (id)timeTextFromItem:(id)arg1;
- (id)monthFeeTextFromMonthTimeInterval:(double)arg1;
- (id)sectionNameFromTimeInterval:(double)arg1;
- (int)timeIntervalInMonthly:(double)arg1;
- (void)mergeMonthFeeFromMonthInfos:(id)arg1 toDictionary:(id)arg2;
- (void)mergeResponse:(id)arg1 toDictionary:(id)arg2;
- (unsigned int)currentCount;
- (void)handleDeleteOrderResponse:(id)arg1 error:(id)arg2 indexPath:(id)arg3;
- (void)deleteOrderIndexPath:(id)arg1;
- (void)handleGetOrderResponse:(id)arg1 error:(id)arg2;
- (void)getOrdersWithOffset:(unsigned int)arg1;
- (id)getBottomView;
- (void)setupView;
- (void)reloadData;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

