//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCBaseControlLogicDeleagte.h"
#import "WCPayAddPayCardDelegate.h"
#import "WCPayLQTClickPurchaseCgiDelegate.h"
#import "WCPayLQTClickRedeemCgiDelegate.h"
#import "WCPayLQTMoneyViewControllerDelegate.h"
#import "WCPayLQTPreRedeemFundCgiDelegate.h"
#import "WCPayLQTPurchaseFundCgiDelegate.h"
#import "WCPayLQTQryPurchaaseResultCgiDelegate.h"
#import "WCPayLQTRedeemFundCgiDelegate.h"
#import "WCPayLQTTransSuccessViewControllerDelegate.h"
#import "WCPayPaidSuccessStatusViewControllerDelegate.h"
#import "WCPayPayMoneyLogicDelegate.h"

@class NSString, PreRedeemFundRes, PurchaseFundRes, WCPayLQTClickPurchaseCgi, WCPayLQTClickRedeemCgi, WCPayLQTPreRedeemFundCgi, WCPayLQTPurchaseFundCgi, WCPayLQTQryPurchaseResultCgi, WCPayLQTRedeemFundCgi, WCPayPayMoneyLogic;

@interface WCPayLQTMoneyControlLogic : WCPayControlLogic <WCPayLQTPurchaseFundCgiDelegate, WCPayLQTQryPurchaaseResultCgiDelegate, WCPayLQTRedeemFundCgiDelegate, WCPayLQTMoneyViewControllerDelegate, WCPayPayMoneyLogicDelegate, WCPayLQTTransSuccessViewControllerDelegate, WCBaseControlLogicDeleagte, WCPayLQTPreRedeemFundCgiDelegate, WCPayAddPayCardDelegate, WCPayLQTClickRedeemCgiDelegate, WCPayPaidSuccessStatusViewControllerDelegate, WCPayLQTClickPurchaseCgiDelegate>
{
    id <WCPayLQTMoneyControlLogicDelegate> _logicDelegate;
    WCPayLQTPurchaseFundCgi *_prepayCgi;
    WCPayLQTQryPurchaseResultCgi *_payResultQryCgi;
    WCPayLQTPreRedeemFundCgi *_preRedeemFundCgi;
    WCPayLQTRedeemFundCgi *_redeemFundCgi;
    WCPayLQTClickRedeemCgi *_clickRedeemCgi;
    WCPayLQTClickPurchaseCgi *_clickPurchaseCgi;
    WCPayPayMoneyLogic *_payMoneyLogic;
    PurchaseFundRes *_purchaseResp;
    PreRedeemFundRes *_preRedeemResp;
    NSString *_bindSerialFromNewCard;
}

@property(retain, nonatomic) NSString *bindSerialFromNewCard; // @synthesize bindSerialFromNewCard=_bindSerialFromNewCard;
@property(retain, nonatomic) PreRedeemFundRes *preRedeemResp; // @synthesize preRedeemResp=_preRedeemResp;
@property(retain, nonatomic) PurchaseFundRes *purchaseResp; // @synthesize purchaseResp=_purchaseResp;
@property(retain, nonatomic) WCPayPayMoneyLogic *payMoneyLogic; // @synthesize payMoneyLogic=_payMoneyLogic;
@property(retain, nonatomic) WCPayLQTClickPurchaseCgi *clickPurchaseCgi; // @synthesize clickPurchaseCgi=_clickPurchaseCgi;
@property(retain, nonatomic) WCPayLQTClickRedeemCgi *clickRedeemCgi; // @synthesize clickRedeemCgi=_clickRedeemCgi;
@property(retain, nonatomic) WCPayLQTRedeemFundCgi *redeemFundCgi; // @synthesize redeemFundCgi=_redeemFundCgi;
@property(retain, nonatomic) WCPayLQTPreRedeemFundCgi *preRedeemFundCgi; // @synthesize preRedeemFundCgi=_preRedeemFundCgi;
@property(retain, nonatomic) WCPayLQTQryPurchaseResultCgi *payResultQryCgi; // @synthesize payResultQryCgi=_payResultQryCgi;
@property(retain, nonatomic) WCPayLQTPurchaseFundCgi *prepayCgi; // @synthesize prepayCgi=_prepayCgi;
@property(nonatomic) __weak id <WCPayLQTMoneyControlLogicDelegate> logicDelegate; // @synthesize logicDelegate=_logicDelegate;
- (void).cxx_destruct;
- (id)genCardInfoFromBindQueryRecard:(id)arg1;
- (void)onAddPayCardResult:(BOOL)arg1 newCardBindSerial:(id)arg2;
- (void)alertViewConfirmClick;
- (BOOL)gotoViewController:(id)arg1;
- (void)onPayMoneyLogicDidStop;
- (void)startPayMoneyLogicWithReqkey:(id)arg1;
- (void)addBalanceInfoInfoCardList:(id)arg1;
- (void)onGetLQTClickPurchaseCgiResp:(id)arg1;
- (void)sendClickPurchaseCgi:(BOOL)arg1;
- (void)onGetLQTClickRedeemCgiResp:(id)arg1;
- (void)sendClickRedeemCgi:(BOOL)arg1;
- (void)OnRetryPayMoneyFromPwdError;
- (void)onGetLQTRedeemFundResp:(id)arg1;
- (void)sendRedeemRequestWithFee:(unsigned long)arg1 pwdEnString:(id)arg2;
- (void)onGetLQTPreRedeemFundResp:(id)arg1;
- (void)sendPreRedeemRequestWithFee:(unsigned long)arg1;
- (void)onGetLQTQryPurchaseResultResp:(id)arg1;
- (void)sendQryPurchaseResultFromSvr;
- (void)onGetLQTPurchaseFundResp:(id)arg1;
- (void)sendLQTPrePayRquestWithMoney:(unsigned long)arg1;
- (void)statusViewControlleDidClickDone:(id)arg1;
- (void)onTransSuccessViewControllerConfirmBtnClick;
- (void)onMoneyViewControllerClickAddNewCard;
- (void)onMoneyViewControllerActionWithAmount:(id)arg1 pwdEnString:(id)arg2;
- (void)onMoneyViewControllerActionWithAmount:(id)arg1;
- (void)onMoneyViewControllerBack;
- (void)startLogic;
- (void)stopLogic;
- (id)initWithMoneyScene:(unsigned int)arg1 controlData:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

