//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class MMTableView, NSString;

@interface WCPayLQTDetailViewController : WCPayBaseViewController <UITableViewDelegate, UITableViewDataSource, WCActionSheetDelegate>
{
    BOOL _bIsClosingAccount;
    id <WCPayLQTDetailViewControllerDelegate> _delegate;
    MMTableView *_tableView;
}

@property(nonatomic) BOOL bIsClosingAccount; // @synthesize bIsClosingAccount=_bIsClosingAccount;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <WCPayLQTDetailViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)incomeCoverBtnClick;
- (void)gainRateCoverBtnClick;
- (void)handleClickLQTTinyApp;
- (BOOL)hasTinyAppEnterance;
- (void)bannerBtnClick;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)fetchBtnClick;
- (void)saveBtnClick;
- (void)footerButtonClick;
- (void)rightBarButtonClick;
- (void)leftBarButtonClick;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)makeTinyAppContent:(id)arg1;
- (void)makeSepbarCellContent:(id)arg1;
- (void)makeDetailEnteranceContent:(id)arg1 indexPath:(id)arg2;
- (void)makeDetailMainContent:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)setupTableFooterView;
- (void)setupTableHeaderView;
- (void)setupContentView;
- (float)tableViewTinyAppContentHeight;
- (float)tableViewOtherContentHeight;
- (float)tableViewMainContentHeight;
- (void)refreshViewWithData:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewWillPop:(BOOL)arg1;
- (BOOL)useTransparentNavibar;
- (void)viewDidBePoped:(BOOL)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

