//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMMLanguageMgrExt.h"
#import "MMPackageDownloadMgrExt.h"
#import "MMService.h"

@class NSMutableDictionary, NSString;

@interface WCPayWordingHelpMgr : MMService <MMService, MMPackageDownloadMgrExt, IMMLanguageMgrExt>
{
    unsigned long _lastUpdateTime;
    NSMutableDictionary *_serverDefaultWordingDict;
    NSMutableDictionary *_validityDynamicWordingDict;
    NSMutableDictionary *_phoneNumberDynamicWordingDict;
    NSMutableDictionary *_cvvCodeDynamicWordingDict;
}

@property(retain, nonatomic) NSMutableDictionary *cvvCodeDynamicWordingDict; // @synthesize cvvCodeDynamicWordingDict=_cvvCodeDynamicWordingDict;
@property(retain, nonatomic) NSMutableDictionary *phoneNumberDynamicWordingDict; // @synthesize phoneNumberDynamicWordingDict=_phoneNumberDynamicWordingDict;
@property(retain, nonatomic) NSMutableDictionary *validityDynamicWordingDict; // @synthesize validityDynamicWordingDict=_validityDynamicWordingDict;
@property(retain, nonatomic) NSMutableDictionary *serverDefaultWordingDict; // @synthesize serverDefaultWordingDict=_serverDefaultWordingDict;
@property(nonatomic) unsigned long lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
- (void).cxx_destruct;
- (id)getCVVCodeWoring:(id)arg1;
- (BOOL)isShowCVVCode:(id)arg1;
- (id)getCardNumberInputSafetyInstructionDescWording;
- (id)getCardNumberInputSafetyTipWording;
- (BOOL)isShowCardNumberInputSafetyTip;
- (id)getCardNumberInputTipWording;
- (BOOL)isShowCardNumberInputTip;
- (id)getSmsVerifyCodeWording;
- (id)getSmsVerifyCodeTipWording;
- (BOOL)isShowSmsVerifyCode;
- (id)getPhoneNumberWording:(id)arg1;
- (BOOL)isShowPhoneNumber:(id)arg1;
- (id)getValidityWording:(id)arg1;
- (BOOL)isShowValidity:(id)arg1;
- (id)getPersonalInfoWording;
- (BOOL)isShowPersonalInfo;
- (BOOL)writeToFile:(id)arg1 data:(id)arg2;
- (void)saveWCPayWording:(id)arg1;
- (BOOL)loadAndUpdateWCPayWording;
- (void)onPackageListUpdated:(id)arg1;
- (void)tryDownloadWCPayWording;
- (void)receiveWordingContent:(id)arg1;
- (void)onLanguageChange;
- (void)dealloc;
- (void)initData;
- (id)init;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

