//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCPayF2FUtil : NSObject
{
}

+ (void)reportFacingReceiveIDKeyWithKeyValue:(unsigned long)arg1;
+ (id)dateYearAndMonthAndDayFormat:(id)arg1;
+ (id)dateYearAndMonthFormat:(id)arg1;
+ (id)dateYearOnlyFormat:(id)arg1;
+ (id)getDateAndTimeDisplayContentWithTimestamp:(unsigned long long)arg1;
+ (id)getDateDisplayContentWithTimestamp:(unsigned long long)arg1 timeFormat:(unsigned int)arg2;
+ (unsigned int)getTimeFormatFromSvrRetType:(unsigned int)arg1;

@end

