//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPaySecurityBaseControlLogic.h"

#import "MMPatternLockLogicDelegate.h"
#import "MMTipsViewControllerDelegate.h"
#import "WCPayCloseWalletLockCgiDelegate.h"
#import "WCPayPayPwdViewControllerDelegate.h"
#import "WCPayTouchLockSettingLogicDelegate.h"
#import "WCPayWalletLockSettingViewControllerDelegate.h"

@class NSString, WCPayCloseWalletLockCgi, WCPayWalletLockSettingViewController;

@interface WCPayWalletLockSettingLogic : WCPaySecurityBaseControlLogic <WCPayWalletLockSettingViewControllerDelegate, MMPatternLockLogicDelegate, WCPayCloseWalletLockCgiDelegate, MMTipsViewControllerDelegate, WCPayPayPwdViewControllerDelegate, WCPayTouchLockSettingLogicDelegate>
{
    id <WCPayWalletLockSettingLogicDelegate> _delegate;
    unsigned long _patternLockLogicTag;
    WCPayCloseWalletLockCgi *_closeWalletLockCgi;
    WCPayWalletLockSettingViewController *_settingVC;
}

@property(retain, nonatomic) WCPayWalletLockSettingViewController *settingVC; // @synthesize settingVC=_settingVC;
@property(retain, nonatomic) WCPayCloseWalletLockCgi *closeWalletLockCgi; // @synthesize closeWalletLockCgi=_closeWalletLockCgi;
@property(nonatomic) unsigned long patternLockLogicTag; // @synthesize patternLockLogicTag=_patternLockLogicTag;
@property(nonatomic) __weak id <WCPayWalletLockSettingLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)OnVerifyPayPassword:(id)arg1;
- (void)closeWalletLockCgi:(id)arg1 didFailWithError:(id)arg2;
- (void)closeWalletLockCgi:(id)arg1 didGetResponse:(id)arg2;
- (void)touchLockSettingLogicSetupSuccess:(id)arg1;
- (BOOL)needCancelPopAnimation;
- (void)onPatternLockLogicOperateSuccess;
- (void)onPatternLockLogicOperateCancel;
- (id)getEnteranceViewContoller;
- (void)VerifyPayPwdNext:(id)arg1;
- (void)PayPwdRightActionBack;
- (void)PayPwdBack;
- (void)onClickTipsBtn:(id)arg1 Index:(int)arg2 tipTag:(int)arg3;
- (void)walletLockVCClickModifyPatternLock:(id)arg1;
- (void)walletLockVCClickClose:(id)arg1;
- (void)walletLockVCClickPatternLock:(id)arg1;
- (void)walletLockVCClickTouchLock:(id)arg1;
- (void)showPasswordVC;
- (void)WCPayViewControllerDidBeRemoved:(id)arg1;
- (void)startLogic;
- (id)initWithData:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

