//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCRadioButtonGroupDelegate.h"

@class MMTableView, NSArray, NSMutableArray, NSString, UIButton, UILabel, UIView;

@interface WCProductSKULogicController : MMObject <UITableViewDelegate, UITableViewDataSource, WCRadioButtonGroupDelegate>
{
    id <WCProductSKULogicControllerDelegate> _delegate;
    NSArray *_skuAttrTable;
    NSArray *_skuInfoTable;
    NSMutableArray *_skuResult;
    NSMutableArray *_tableDatas;
    unsigned int _purchaseCount;
    unsigned int _stockCount;
    unsigned int _leftBuyQuantity;
    MMTableView *_tableView;
    UIView *_lineImageView;
    UIButton *_reduceButton;
    UIButton *_increaseButton;
    UILabel *_purchaseCountLabel;
    UILabel *_stockCountLabel;
    UILabel *_tipLabel;
    BOOL _isShowCaution;
}

@property(nonatomic) __weak id <WCProductSKULogicControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getStockCountStr;
- (id)getPurchaseCountStr;
- (unsigned int)getTotleStockCount;
- (id)getGroupID:(id)arg1 contactButtonID:(id)arg2;
- (id)getResultItemFromItemValue:(id)arg1;
- (id)buttonIDConvertArr2String:(id)arg1;
- (id)sortButtonIDList:(id)arg1;
- (id)powerSet:(id)arg1;
- (id)selectedGroupIDContactButtonIDListFilterGroupID:(id)arg1;
- (id)selectedGroupIDContactButtonIDList;
- (id)getSelectedGroupNameAndButtonNameList;
- (id)getSelectedButtonNameList;
- (void)addSkuInfo2SKUResult:(id)arg1 forCombItemValue:(id)arg2;
- (id)getSKUIDList:(id)arg1;
- (id)buttonIDCombine:(id)arg1;
- (id)filterNOStockSKUInfo:(id)arg1;
- (void)increasePurchaseCount;
- (void)reducePurchaseCount;
- (void)animationFadeTipLabel;
- (void)updateUIInfoPriceAndStockCount:(id)arg1;
- (void)radioButtonGroup:(id)arg1 selectedIndex:(int)arg2;
- (void)showCaution;
- (void)updateStockCount:(id)arg1;
- (BOOL)canIncreaseAndUpdateTipLabelWording;
- (void)updateIncreaseButton;
- (void)updateReduceButton;
- (void)updatePurchaseCountLabel;
- (void)updateSKUAttrItemState:(id)arg1;
- (void)makeCountCell:(id)arg1;
- (void)makeSKUAttrCell:(id)arg1 withAttrItem:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)initStockCount;
- (void)initSKUDisplayInfo;
- (void)loadTableData;
- (void)loadSKUData;
- (BOOL)isNOStock;
- (id)isSKUSelectFinish;
- (BOOL)isSKUNOStartSelect;
- (unsigned int)getPurchaseCount;
- (id)getFinalSelectedGroupNameButtonNameList;
- (id)getFinalSelectedButtonNames;
- (id)getFinalSelectedGroupIDButtonIDs;
- (float)getTableViewHeight;
- (void)loadSKUSubView:(id)arg1 withScrollEnabled:(BOOL)arg2 contentInset:(struct UIEdgeInsets)arg3;
- (id)initWithProductInfo:(id)arg1;
- (void)clearSKUStateInfo;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

