//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCRedEnvelopesWelcomePageLayout : NSObject
{
}

- (float)bottomSceneImageMarginBottomWithFlag:(unsigned long)arg1;
- (id)bottomSceneImageWithFlag:(unsigned long)arg1;
- (float)middleSceneImageMarginBottomWithFlag:(unsigned long)arg1;
- (id)middleSceneImageWithFlag:(unsigned long)arg1;
- (float)topSceneImageMarginTopWithFlag:(unsigned long)arg1;
- (id)topSceneImageWithFlag:(unsigned long)arg1;
- (float)bottomTitleMarginBottomWithFlag:(unsigned long)arg1;
- (id)bottomTitleColorWithFlag:(unsigned long)arg1;
- (id)navigationTitleColorWithFlag:(unsigned long)arg1;
- (float)normalButtonHeightWithFlag:(unsigned long)arg1;
- (float)randomButtonHeightWithFlag:(unsigned long)arg1;
- (float)normalButtonMarginLeftWithFlag:(unsigned long)arg1;
- (float)randomButtonMarginLeftWithFlag:(unsigned long)arg1;
- (float)normalButtonTitleFontWithFlag:(unsigned long)arg1;
- (float)randomButtonTitleFontWithFlag:(unsigned long)arg1;
- (float)normalButtonMarginTopWithFlag:(unsigned long)arg1;
- (float)randomButtonMarginTopWithFlag:(unsigned long)arg1;
- (id)normalButtonTitleColorWithFlag:(unsigned long)arg1;
- (id)randomButtonTitleColorWithFlag:(unsigned long)arg1;
- (id)normalButtonHLImageWithFlag:(unsigned long)arg1;
- (id)normalButtonImageWithFlag:(unsigned long)arg1;
- (id)randomButtonHLImageWithFlag:(unsigned long)arg1;
- (id)randomButtonImageWithFlag:(unsigned long)arg1;
- (float)topBackgroundImageMarginTopWithFlag:(unsigned long)arg1;
- (id)topBackgroundImageWithFlag:(unsigned long)arg1;
- (id)totalBackgroundColorWithFlag:(unsigned long)arg1;
- (id)init;

@end

