//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSMutableDictionary, NSString;

@interface WCSCheckBehaviorMgr : MMService <MMService>
{
    NSMutableDictionary *_dicTextFieldCheck;
}

- (void).cxx_destruct;
- (id)getTextFieldCheckData:(unsigned int)arg1;
- (void)removeTextFieldCheck:(unsigned int)arg1;
- (void)pauseTextFieldCheck:(unsigned int)arg1;
- (void)stopTextFieldCheck:(unsigned int)arg1;
- (void)startTextFieldCheck:(unsigned int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

