//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "CAAnimationDelegate.h"

@class NSString;

@interface WCTimelineTipView : MMUIView <CAAnimationDelegate>
{
    id <WCTimelineTipViewDelegate> _delegate;
    BOOL _showTipNow;
    BOOL _closeTipNow;
    BOOL _hidingTip;
}

+ (id)showTipWithDelegate:(id)arg1 parentView:(id)arg2 content:(id)arg3;
@property(nonatomic) BOOL showTipNow; // @synthesize showTipNow=_showTipNow;
@property(nonatomic) __weak id <WCTimelineTipViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showTipView:(float)arg1 withAnimationTimes:(id)arg2 AnimationValues:(id)arg3;
- (void)closeTipView:(BOOL)arg1;
- (void)showTipView:(BOOL)arg1;
- (void)hideTipView:(BOOL)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (id)getAnimationLayer;
- (void)performBgAction;
- (void)initView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

