//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "WCActionSheetDelegate.h"
#import "WCCommentViewFBDelegate.h"

@class NSMutableArray, NSString, UIImageView, UINavigationController, UIView, WCDataItem;

@interface WCTimeLineCommentCellView : MMUIView <WCActionSheetDelegate, WCCommentViewFBDelegate>
{
    int _iSection;
    int _iRow;
    WCDataItem *_mainDataItem;
    UINavigationController *_navigationController;
    id <WCTimeLineCommentCellViewDelegate> m_delegate;
    id <ILinkEventExt> m_urlDelegate;
    UIImageView *m_commentContainer;
    UIView *m_likeContainer;
    UIView *m_lineView;
    NSMutableArray *m_arrCommentView;
    BOOL m_bHaveActionSheet;
}

+ (float)getCommentViewLeftMarginCurOri;
+ (float)getCellHeightForDataItem:(id)arg1 RowIndex:(int)arg2;
+ (id)getNickNameForDataItem:(id)arg1;
@property(nonatomic) __weak id <ILinkEventExt> m_urlDelegate; // @synthesize m_urlDelegate;
@property(nonatomic) __weak id <WCTimeLineCommentCellViewDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(retain, nonatomic) WCDataItem *mainDataItem; // @synthesize mainDataItem=_mainDataItem;
@property(nonatomic) int iRow; // @synthesize iRow=_iRow;
@property(nonatomic) int iSection; // @synthesize iSection=_iSection;
- (void).cxx_destruct;
- (void)onRestoreCommentCellView:(id)arg1;
- (void)onReloadCommentCellView:(id)arg1;
- (void)onCommentViewClicked:(id)arg1;
- (void)dealloc;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)showCommentOption:(id)arg1;
- (void)deleteComment:(unsigned int)arg1;
- (void)initView;
- (void)initLineView;
- (void)initLikeContainer;
- (void)initCommentContainer;
- (id)getShowComment;
- (BOOL)isShowLikeCell;
- (id)initWithUrlDelegate:(id)arg1;
- (void)layoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

