//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@interface WCUITextField : UITextField
{
    BOOL m_bRestrictShareMenu;
    float m_fPlaceholderFontSize;
}

@property(nonatomic) float m_fPlaceholderFontSize; // @synthesize m_fPlaceholderFontSize;
@property(nonatomic) BOOL m_bRestrictShareMenu; // @synthesize m_bRestrictShareMenu;
- (void)dealloc;
- (void)drawPlaceholderInRect:(struct CGRect)arg1;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)init;

@end

