//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSMutableArray, NSString;

@interface WePkgRegularConfig : MMObject
{
    NSString *_nsPkgId;
    NSString *_nsAppId;
    unsigned long _uiPkgType;
    NSString *_nsEnteranceDomain;
    NSString *_nsCurrentEnabledVersion;
    unsigned long _uiLastUnusedSeconds;
    unsigned long _uiCheckIntervalSeconds;
    unsigned long _uiLastUsedTimestamp;
    NSString *_nsCheckResponseMd5;
    NSString *_nsCharSet;
    unsigned long _uiCheckUpdateSuccessTime;
    NSString *_nsBigPackageMd5;
    NSString *_nsBigPackageDownloadUrl;
    unsigned long _uiBigPackageDownloadNetworkType;
    unsigned long _uiBigPackageSizeInBytes;
    NSMutableArray *_atomicSingleFileList;
    NSMutableArray *_nonAtomicSingleFileList;
}

+ (id)regularConfigFromTableItem:(id)arg1;
@property(retain, nonatomic) NSMutableArray *nonAtomicSingleFileList; // @synthesize nonAtomicSingleFileList=_nonAtomicSingleFileList;
@property(retain, nonatomic) NSMutableArray *atomicSingleFileList; // @synthesize atomicSingleFileList=_atomicSingleFileList;
@property(nonatomic) unsigned long uiBigPackageSizeInBytes; // @synthesize uiBigPackageSizeInBytes=_uiBigPackageSizeInBytes;
@property(nonatomic) unsigned long uiBigPackageDownloadNetworkType; // @synthesize uiBigPackageDownloadNetworkType=_uiBigPackageDownloadNetworkType;
@property(retain, nonatomic) NSString *nsBigPackageDownloadUrl; // @synthesize nsBigPackageDownloadUrl=_nsBigPackageDownloadUrl;
@property(retain, nonatomic) NSString *nsBigPackageMd5; // @synthesize nsBigPackageMd5=_nsBigPackageMd5;
@property(nonatomic) unsigned long uiCheckUpdateSuccessTime; // @synthesize uiCheckUpdateSuccessTime=_uiCheckUpdateSuccessTime;
@property(retain, nonatomic) NSString *nsCharSet; // @synthesize nsCharSet=_nsCharSet;
@property(retain, nonatomic) NSString *nsCheckResponseMd5; // @synthesize nsCheckResponseMd5=_nsCheckResponseMd5;
@property(nonatomic) unsigned long uiLastUsedTimestamp; // @synthesize uiLastUsedTimestamp=_uiLastUsedTimestamp;
@property(nonatomic) unsigned long uiCheckIntervalSeconds; // @synthesize uiCheckIntervalSeconds=_uiCheckIntervalSeconds;
@property(nonatomic) unsigned long uiLastUnusedSeconds; // @synthesize uiLastUnusedSeconds=_uiLastUnusedSeconds;
@property(retain, nonatomic) NSString *nsCurrentEnabledVersion; // @synthesize nsCurrentEnabledVersion=_nsCurrentEnabledVersion;
@property(retain, nonatomic) NSString *nsEnteranceDomain; // @synthesize nsEnteranceDomain=_nsEnteranceDomain;
@property(nonatomic) unsigned long uiPkgType; // @synthesize uiPkgType=_uiPkgType;
@property(retain, nonatomic) NSString *nsAppId; // @synthesize nsAppId=_nsAppId;
@property(retain, nonatomic) NSString *nsPkgId; // @synthesize nsPkgId=_nsPkgId;
- (void).cxx_destruct;
- (id)debugDescription;
- (BOOL)hasValidContent;
- (BOOL)hasBigPackage;
- (id)generateTableItem;

@end

