//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface WePkgUpdateConfig : MMObject
{
    BOOL _bClearAllPkgExceptCurrentEnabledVersion;
    BOOL _bIsReadyForOperation;
    BOOL _bBigPackageDownloadSuccess;
    NSString *_nsPkgId;
    NSString *_nsAppId;
    unsigned long _uiPkgType;
    NSString *_nsEnteranceDomain;
    NSString *_nsCurrentEnabledVersion;
    unsigned long _uiLastUnusedSeconds;
    unsigned long _uiCheckIntervalSeconds;
    NSString *_nsCheckResonseMd5;
    NSString *_nsCharSet;
    unsigned long _uiCheckUpdateSuccessTime;
    NSString *_nsBigPackageMd5;
    NSString *_nsBigPackageDownloadUrl;
    unsigned long _uiBigPackageDownloadNetworkType;
    unsigned long _uiBigPackageSizeInBytes;
    unsigned long _uiAtomicSingleFileTotalCount;
    NSMutableArray *_atomicSingleFileListNeedDownload;
    NSMutableArray *_atomicSingleFileListDownloadSuccessed;
    NSMutableDictionary *_file2DownloadFailCount;
}

+ (id)updateConfigFromTableItem:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *file2DownloadFailCount; // @synthesize file2DownloadFailCount=_file2DownloadFailCount;
@property(retain, nonatomic) NSMutableArray *atomicSingleFileListDownloadSuccessed; // @synthesize atomicSingleFileListDownloadSuccessed=_atomicSingleFileListDownloadSuccessed;
@property(retain, nonatomic) NSMutableArray *atomicSingleFileListNeedDownload; // @synthesize atomicSingleFileListNeedDownload=_atomicSingleFileListNeedDownload;
@property(nonatomic) unsigned long uiAtomicSingleFileTotalCount; // @synthesize uiAtomicSingleFileTotalCount=_uiAtomicSingleFileTotalCount;
@property(nonatomic) BOOL bBigPackageDownloadSuccess; // @synthesize bBigPackageDownloadSuccess=_bBigPackageDownloadSuccess;
@property(nonatomic) unsigned long uiBigPackageSizeInBytes; // @synthesize uiBigPackageSizeInBytes=_uiBigPackageSizeInBytes;
@property(nonatomic) unsigned long uiBigPackageDownloadNetworkType; // @synthesize uiBigPackageDownloadNetworkType=_uiBigPackageDownloadNetworkType;
@property(retain, nonatomic) NSString *nsBigPackageDownloadUrl; // @synthesize nsBigPackageDownloadUrl=_nsBigPackageDownloadUrl;
@property(retain, nonatomic) NSString *nsBigPackageMd5; // @synthesize nsBigPackageMd5=_nsBigPackageMd5;
@property(nonatomic) unsigned long uiCheckUpdateSuccessTime; // @synthesize uiCheckUpdateSuccessTime=_uiCheckUpdateSuccessTime;
@property(retain, nonatomic) NSString *nsCharSet; // @synthesize nsCharSet=_nsCharSet;
@property(retain, nonatomic) NSString *nsCheckResonseMd5; // @synthesize nsCheckResonseMd5=_nsCheckResonseMd5;
@property(nonatomic) BOOL bIsReadyForOperation; // @synthesize bIsReadyForOperation=_bIsReadyForOperation;
@property(nonatomic) BOOL bClearAllPkgExceptCurrentEnabledVersion; // @synthesize bClearAllPkgExceptCurrentEnabledVersion=_bClearAllPkgExceptCurrentEnabledVersion;
@property(nonatomic) unsigned long uiCheckIntervalSeconds; // @synthesize uiCheckIntervalSeconds=_uiCheckIntervalSeconds;
@property(nonatomic) unsigned long uiLastUnusedSeconds; // @synthesize uiLastUnusedSeconds=_uiLastUnusedSeconds;
@property(retain, nonatomic) NSString *nsCurrentEnabledVersion; // @synthesize nsCurrentEnabledVersion=_nsCurrentEnabledVersion;
@property(retain, nonatomic) NSString *nsEnteranceDomain; // @synthesize nsEnteranceDomain=_nsEnteranceDomain;
@property(nonatomic) unsigned long uiPkgType; // @synthesize uiPkgType=_uiPkgType;
@property(retain, nonatomic) NSString *nsAppId; // @synthesize nsAppId=_nsAppId;
@property(retain, nonatomic) NSString *nsPkgId; // @synthesize nsPkgId=_nsPkgId;
- (void).cxx_destruct;
- (id)debugDescription;
- (BOOL)shouldReadyForUpdate;
- (id)generateTableItem;

@end

