//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"
#import "WNParaObjectViewDelegate.h"
#import "WNParaTextViewDelegate.h"
#import "WNTodoHeaderViewDelegate.h"

@class MMUIView, NSString, WNParaObjectBaseView, WNParaTextView, WNParagraphInfo;

@interface WNParagraphCellView : UIView <WNTodoHeaderViewDelegate, UITextViewDelegate, WNParaObjectViewDelegate, WNParaTextViewDelegate>
{
    BOOL m_bIsLongPressHandled;
    BOOL m_bIsLongPressCanceled;
    BOOL m_touchEnded;
    WNParaObjectBaseView *_objectView;
    WNParaTextView *_mainTextView;
    UIView *_selectedToRemoveView;
    UIView *_selectedAllView;
    MMUIView *_leftParaStyleView;
    BOOL bMannalSetStyle;
    float m_textHeight;
    struct _NSRange _cacheSelectRange;
    WNParagraphInfo *paraInfo;
    id <WNParaCellViewDelegate> delegate;
}

@property(nonatomic) __weak id <WNParaCellViewDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) WNParagraphInfo *paraInfo; // @synthesize paraInfo;
- (void).cxx_destruct;
- (BOOL)canEdit;
- (void)setBecomeFirstResponse;
- (void)onTouchDownInObject;
- (void)onTouchDownInRightText;
- (void)onTouchDownInLeftText;
- (void)onTouchEnd:(id)arg1;
- (void)onTouchBegin:(id)arg1;
- (void)LongPressEvents;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (BOOL)isTouchInView:(id)arg1;
- (BOOL)isTouchInRightTextView:(id)arg1;
- (BOOL)isTouchInLeftTextView:(id)arg1;
- (BOOL)isTouchInObjectView:(id)arg1;
- (void)onCheckChanged:(BOOL)arg1;
- (void)onWNTextViewAttrTextChanged;
- (BOOL)shouldHandleSelectAllByself;
- (BOOL)isTextViewMenuEnable;
- (void)onTextViewTouched:(int)arg1;
- (void)onTextViewMenuPaste;
- (void)onSelectAll;
- (void)onSelectText:(struct _NSRange)arg1;
- (void)onSelectObject;
- (void)textViewDidChangeSelection:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textViewShouldEndEditing:(id)arg1;
- (void)textViewHandleLink:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (void)onStopRecordAlertViewWillShow;
- (id)getFavItem;
- (id)getViewController;
- (void)onSendLocationToFriend:(id)arg1 ViewController:(id)arg2;
- (id)getDataArray;
- (void)onObjectContentChanged:(id)arg1;
- (void)onObjectHeightChanged;
- (void)updataTableViewHeight;
- (void)onTextViewHeightChange:(float)arg1;
- (void)scrollToCursorStartForTextView:(id)arg1;
- (void)scrollToCursorEndForTextView:(id)arg1;
- (void)scrollToCursorRect:(struct CGRect)arg1;
- (void)scrollToVisibleArea;
- (void)setContent:(id)arg1 withSelectRange:(struct _NSRange)arg2;
- (void)setContent:(id)arg1;
- (id)stringAfterCursor;
- (id)stringBeforeCursor;
- (id)getFirstResponderTextView;
- (void)restoreKeyboard;
- (void)backupKeyboard;
- (void)hideKeyboard;
- (void)showKeyboard;
- (void)showKeyboardWithSelectionRange:(struct _NSRange)arg1;
- (struct _NSRange)selectedRange;
- (void)updateRemoveSelectedView;
- (void)setTodoView:(BOOL)arg1;
- (void)changeToTodoView:(BOOL)arg1;
- (void)changeToOlLiView;
- (void)changeToUlLiView;
- (void)changeToMainTextViewFromLiView;
- (void)changeToTextCellWithAttrText:(id)arg1;
- (void)changeToTextCell;
- (void)changeToOtherObject:(id)arg1;
- (void)showTextViewInRight;
- (BOOL)isTextViewInRight;
- (void)showTextViewInLeft;
- (BOOL)isTextViewInLeft;
- (void)resizeMainTextView;
- (BOOL)needNewObjectView;
- (void)buildObjectView;
- (void)resizeCellView;
- (void)configMainTextView;
- (id)getWNTextView:(struct CGRect)arg1;
- (void)layoutView;
- (id)tableView;
- (id)getObjectView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

