//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WXCDeviceInfo : NSObject
{
}

+ (BOOL)is736hScreen;
+ (BOOL)is414wScreen;
+ (BOOL)is667hScreen;
+ (BOOL)is375wScreen;
+ (BOOL)is480hScreen;
+ (BOOL)is320wScreen;
+ (BOOL)is568hScreen;
+ (BOOL)isiOS5plus;
+ (BOOL)isiOS5_1plus;
+ (BOOL)isiOS6plus;
+ (BOOL)isiOS6_1plus;
+ (BOOL)isiOS7plus;
+ (BOOL)isiOS8plus;
+ (BOOL)isiOS7_1plus;
+ (BOOL)isiPadMini;
+ (BOOL)isiPad4;
+ (BOOL)isiPad3;
+ (BOOL)isiPad2;
+ (BOOL)isiPad1;
+ (BOOL)isiPad;
+ (BOOL)isiPodTouch5;
+ (BOOL)isiPodTouch4;
+ (BOOL)isiPodTouch3;
+ (BOOL)isiPodTouch2;
+ (BOOL)isiPodTouch1;
+ (BOOL)isiPodTouch;
+ (BOOL)isiPhone5C;
+ (BOOL)isiPhone5S;
+ (BOOL)isiPhone5;
+ (BOOL)isiPhone4S;
+ (BOOL)isiPhone4;
+ (BOOL)isiPhone3GS;
+ (BOOL)isiPhone3G;
+ (BOOL)isiPhone2G;
+ (BOOL)isiPhone;
+ (long long)FreeDiskSpaceSize;
+ (long long)TotalDiskSpaceSize;
+ (id)DCache;
+ (id)DBus;
+ (id)DMemory;
+ (id)DCPU;
+ (id)DSystem;
+ (id)DModel;
+ (id)modelPlatform;

@end

