//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString, NSURL, UIView<YYWebViewInterface>, WebViewA8KeyLogicImpl;

@protocol WXCustomWebViewControllerProtocol <NSObject>
@property(nonatomic) __weak id <WXCustomWebViewControllerDelegate> m_delegate;
@property(nonatomic) BOOL m_bIsJsapiUploadVideoUploading;
@property(retain, nonatomic) UIView<YYWebViewInterface> *webView;
@property(readonly, nonatomic) BOOL m_bOfflinePage;
@property(readonly, nonatomic) WebViewA8KeyLogicImpl *m_a8KeyLogicImpl;
@property(retain, nonatomic) NSMutableDictionary *m_extraInfo;
@property(readonly, nonatomic) NSString *m_initUrl;
- (void)goToURL:(NSURL *)arg1;
- (NSString *)getShareUrl;
- (unsigned char)getPermissionWithName:(NSString *)arg1;
- (void)startupPreVerifyJSAPI:(NSDictionary *)arg1 failHandleBlock:(void (^)(NSDictionary *))arg2;
- (void)sendEventToJSBridge:(NSString *)arg1 Param:(NSDictionary *)arg2;
- (void)forceShowCloseButton;
- (void)doJsApiInitEvent;
- (void)setDisableWebAlertView:(BOOL)arg1;
- (BOOL)allowFayByImage;
- (BOOL)allowShareByImage;
- (BOOL)allowScanQRCodeByImage;
- (unsigned long)getCurrentScene;
- (NSDictionary *)extraInfo;
- (NSString *)getInitUrl;
- (NSString *)getCurrentAppId;
- (NSString *)getCurrentUrl;
@end

