//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

@class MMLoadingView;

@interface WXGClearCacheUIViewController : MMUIViewController
{
    MMLoadingView *_loadingView;
    unsigned long _cacheMask;
}

@property(nonatomic) unsigned long cacheMask; // @synthesize cacheMask=_cacheMask;
@property(retain, nonatomic) MMLoadingView *loadingView; // @synthesize loadingView=_loadingView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithCacheMask:(unsigned long)arg1;

@end

