//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BackupInfoItem, NSMutableSet, NSString, WXGMapTableObject;

@interface WXGImportMessageHelper : NSObject
{
    BOOL m_bShouldImport;
    NSMutableSet *m_setChatName;
    WXGMapTableObject *m_mediaPathMapTable;
    BackupInfoItem *m_currentRecoverInfo;
    NSString *m_folderPath;
    NSString *m_tmpFolderPath;
    unsigned int m_currentMaxTime;
    unsigned int m_currentMinTime;
    id <WXGImportMessageHelperDelegate> _delegate;
}

+ (id)splitMsgListIDArray:(id)arg1;
@property(nonatomic) __weak id <WXGImportMessageHelperDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getOneEmptyInfoItem;
- (BOOL)p_addContactListChat;
- (BOOL)p_renameFilesInMediaDictinary:(id)arg1;
- (BOOL)p_renameMediaFiles;
- (void)p_analysisiHasMeidaType:(unsigned long)arg1;
- (BOOL)p_handleBufferForBakChatMsgItem:(id)arg1 withMessageWrap:(id)arg2;
- (void)p_handleChatName:(id)arg1;
- (BOOL)p_addMsgFromMsgList:(id)arg1 withStartTime:(unsigned int)arg2 withEndTime:(unsigned int)arg3 textOnly:(BOOL)arg4;
- (BOOL)internalRecoverMessage:(id)arg1 withSessionName:(id)arg2 withStartTime:(unsigned int)arg3 withEndTime:(unsigned int)arg4 textOnly:(BOOL)arg5;
- (BOOL)internalRecoverMessage:(id)arg1 withSessionName:(id)arg2 withStartTime:(unsigned int)arg3 withEndTime:(unsigned int)arg4;
- (unsigned int)getCurrentMinMsgTime;
- (unsigned int)getCurrentMaxMsgTime;
- (id)getCurrentRecoverInfo;
- (void)stopImport;
- (id)initWithMsgListFolderPath:(id)arg1 withTmpFolderPath:(id)arg2;
- (id)init;

@end

