//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WXTalkLog : NSObject
{
    NSString *logStr;
    unsigned long logId;
}

@property(nonatomic) unsigned long logId; // @synthesize logId;
@property(retain, nonatomic) NSString *logStr; // @synthesize logStr;
- (void).cxx_destruct;
- (void)dealloc;

@end

