//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, NSURLRequest, UIScrollView;

@protocol YYWebViewInterface <NSObject>
@property(nonatomic) BOOL mediaPlaybackRequiresUserAction;
@property(nonatomic) BOOL allowsInlineMediaPlayback;
@property(nonatomic) BOOL scalesPageToFit;
@property(readonly, nonatomic, getter=isLoading) BOOL loading;
@property(readonly, nonatomic, getter=canGoForward) BOOL canGoForward;
@property(readonly, nonatomic, getter=canGoBack) BOOL canGoBack;
@property(nonatomic) BOOL allowsBackForwardNavigationGestures;
@property(readonly, nonatomic) NSURLRequest *request;
@property(readonly, nonatomic) UIScrollView *scrollView;
@property(nonatomic) __weak id <YYWebViewDelegate> wvDelegate;
- (void)enableJavaScriptPopup:(BOOL)arg1;
- (void)evaluateJavaScriptFromString:(NSString *)arg1 completionBlock:(void (^)(NSString *, NSError *))arg2;
- (void)goForward;
- (void)goBack;
- (void)stopLoading;
- (void)reload;
- (void)loadHTMLString:(NSString *)arg1 baseURL:(NSURL *)arg2;
- (void)loadRequest:(NSURLRequest *)arg1;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id <YYWebViewDelegate>)arg2;
@end

